<div class="padder">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="page-head">
	    <h3><?php echo $this->__('Submit Migration Info') ?></h3>
	</div>
	
	<div class="box simple_contact">

	    <fieldset class="group-select">
	        <h4 class="legend">				Your migration information has been submitted.  Please allow up to 24 hours for us to complete it.  Once completed we will notify by sending you a migration ready for review email.</h4>
	        <p></p>                                                                                                 
                           
	    </fieldset>

	</div>
</div>