<?php
/**
 * @brief Defines the html for show Credit Card Dashbord
 * @category Magento CardConnect Payment Module
 * @author CardConnect
 * @copyright Portions copyright 2014 CardConnect
 * @copyright Portions copyright Magento 2014
 * @license GPL v2, please see LICENSE.txt
 * @access public
 * @version $Id: $
 *
 * */
/**
  Magento
 *
  NOTICE OF LICENSE
 *
  This source file is subject to the Open Software License (OSL 3.0)
  that is bundled with this package in the file LICENSE.txt.
  It is also available through the world-wide-web at this URL:
  http://opensource.org/licenses/osl-3.0.php
  If you did not receive a copy of the license and are unable to
  obtain it through the world-wide-web, please send an email
  to license@magentocommerce.com so we can send you a copy immediately.
 *
  @category Cardconnect
  @package Cardconnect_Ccgateway
  @copyright Copyright (c) 2014 CardConnect (http://www.cardconnect.com)
  @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<style>
    #t_head_row{
        background-color: #3399CC !important;
        text-align: center;
        color: #fff;
    }
    #t_content_row{
        text-align: left;
    }
    #t_content_row td{
        padding-left: 10px;
    }
    #text_link{
        color:#3399CC;
        cursor: pointer;
    }
    #text_link:hover{
        text-decoration: underline;
    }

#fade{ width:100%; height:100%; background:rgba(0,0,0,0.1); position:fixed; top:0px; left:0px; display:none;}
.loader{position:absolute; top:80%; left:50%;}
</style>


<script>
    function makeDefaultPayment(defaultId, value, id) {

        var loadurl = '<?php echo Mage::getUrl('ccgateway/cardmanagement/makedefaultpayment',array('_secure'=>true)); ?>';
        //Element.show('loadingmask');
        new Ajax.Request(loadurl, {
			onCreate : startLoading,
            method: 'post',
            parameters: "defaultId=" + defaultId + "&value=" + value + "&id=" + id,
            onComplete: function (transport) {
                document.getElementById('success-msg').style.display = "block";
                document.getElementById('success-msg').innerHTML = transport.responseText;
				stopLoading();
                window.location.reload(100000);
            }
        });
    }



    function confirm_del(delId) {

        var loc = document.getElementById('cardListGrid');
        var conf = confirm("Are you sure to delete this?");
        if (conf == true) {
            var loadurl = '<?php echo Mage::getUrl('ccgateway/cardmanagement/deletewallet',array('_secure'=>true)); ?>';

            new Ajax.Request(loadurl, {
				onCreate : startLoading,
                method: 'post',
                parameters: "cc_id=" + delId,
                onComplete: function (transport) {
                    alert(transport.responseText); //return false;
					stopLoading();
                    document.getElementById('success-msg').style.display = "";
                    $('success-msg').innerHTML = transport.responseText;
                    window.location.reload();
                }
            });
        } else {
            alert('You cancelled to delete.');
        }
    }


 var loaded = false;
  function startLoading() {
    loaded = false;
    window.setTimeout('showLoadingImage()', 500);
  }

  function showLoadingImage() {
  document.getElementById('fade').style.display ="block";
    var el = document.getElementById("loading_box");
    if (el && !loaded) {

        el.innerHTML = '<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" alt="Loading...">';
        new Effect.Appear('loading_box');
    }
  }

	function stopLoading() {
	document.getElementById('fade').style.display ="none";
		Element.hide('loading_box');
		loaded = true;
	}



</script>

<div id="fade">
<div id="loading_box" class="loader"></div>
</div>

<div id="success-msg" style="display:none;">
    <ul class="messages">
        <li class="success-msg">
            <ul class="success-msg">
                <li><strong>Wallet Profile has been updated.</strong></li>
            </ul>
        </li>
    </ul>

</div>

<div class="page-title title-buttons">
    <h1><?php echo $this->__('Card Management') ?></h1>
    <button type="button" title="<?php echo $this->__('Add New Card') ?>" class="button" onclick="window.location = '<?php echo $this->getAddUrl() ?>';"><span><span><?php echo $this->__('Add New Card') ?></span></span></button>
</div>
<div id="cardManagementGrid">
    <table cellpadding="2" cellspacing="1" border="1" name="cardListGrid" id="cardListGrid" width="100%">
        <?php $walletProfile = $this->getCCProfileName();
        if (count($walletProfile) != 0) {
            ?>
            <tr id="t_head_row">
                <td>#</td>
                <td>Card Name</td>
                <td>Card Number</td>
                <td>Action</td>
                <td>Default</td>
            </tr>
            <?php
            $i = 1;
            foreach ($walletProfile as $val => $data) {
                ?>
                <tr id="t_content_row">
                    <td><?php echo $i; ?></td>
                    <td><?php echo ucfirst($data['CC_CARD_NAME']); ?></td>
                    <td><?php echo substr_replace($data['CC_MASK'], '************', 0, 12); ?></td>
                    <td>
                        <a href="<?php echo $this->getEditUrl() . "?cardid=" . $data['CC_ID'] . "&pid=" . $data['CC_PROFILEID']; ?>">Edit</a>&nbsp;&nbsp;
						<span id="text_link"  <?php if ($data['CC_DEFAULT_CARD'] == 'Y' && count($walletProfile) !=1) { ?> style="display:none;" <?php } ?>  onclick="confirm_del(<?php echo $data['CC_ID']; ?>);">Delete</span>

					</td>
                    <td><input type="radio" name="defaultPaymentCard" id="defaultPaymentCard_<?php echo $i; ?>" onclick="javascript:makeDefaultPayment(this.id, this.value, <?php echo $data['CC_ID']; ?>);" <?php if ($data['CC_DEFAULT_CARD'] == 'Y') { ?> checked="checked" <?php } ?>value="<?php echo $data['CC_DEFAULT_CARD']; ?>" /> <?php // echo $data['CC_PROFILEID'];  ?></td>
                </tr>
                <?php
                $i++;
            }
        }else{
        ?>
                <div>
                    <strong>No Card Found.</strong>
                </div>

     <?php } ?>
    </table>
</div>




