<?php
/**
 * @brief Defines the html for show Credit Card Dashbord
 * @category Magento CardConnect Payment Module
 * @author CardConnect
 * @copyright Portions copyright 2014 CardConnect
 * @copyright Portions copyright Magento 2014
 * @license GPL v2, please see LICENSE.txt
 * @access public
 * @version $Id: $
 *
 * */
/**
  Magento
 *
  NOTICE OF LICENSE
 *
  This source file is subject to the Open Software License (OSL 3.0)
  that is bundled with this package in the file LICENSE.txt.
  It is also available through the world-wide-web at this URL:
  http://opensource.org/licenses/osl-3.0.php
  If you did not receive a copy of the license and are unable to
  obtain it through the world-wide-web, please send an email
  to license@magentocommerce.com so we can send you a copy immediately.
 *
  @category Cardconnect
  @package Cardconnect_Ccgateway
  @copyright Copyright (c) 2014 CardConnect (http://www.cardconnect.com)
  @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<style>
    #fade{ width:100%; height:100%; background:rgba(0,0,0,0.1); position:fixed; top:0px; left:0px; display:none;}
    .loader{position:absolute; top:80%; left:50%;}
</style>

<?php
$_code = "ccgateway";

if(Mage::getSingleton('customer/session')->isLoggedIn()) {
    $isTestMode = $this->isTransactionModeTest();
    $siteName = Mage::helper('ccgateway')->getSiteName();
    $customerData = Mage::getSingleton('customer/session')->getCustomer();
    $customerId = $customerData->getId();
    $address =  Mage::getSingleton('customer/session')->getCustomer()->getDefaultBillingAddress();

    if($address){
        $customer = Mage::getModel('customer/customer')->load($customerId);
        $billingAddress = $customer->getDefaultBillingAddress();
        $billingStreet = $billingAddress->getData('street');
        $billingCity = $billingAddress->getData('city');
        $billingRegion = $billingAddress->getData('region');
        $billingCountry = $billingAddress->getData('country_id');
        $billingPostCode = $billingAddress->getData('postcode');
        $billingTelephone = $billingAddress->getData('telephone');
    }
    $errorLogURL = Mage::getUrl('ccgateway/log/logfrontenderrors',array('_secure'=>true));
}



?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Add New Card Form') ?></h1>
    <button type="button" title="<?php echo $this->__('Go Back') ?>" class="button" onclick="window.location = '<?php echo $this->getUrl('customer/cardmanagement/') ?>';"><span><span><?php echo $this->__('Go Back') ?></span></span></button>
</div>

<div id="fade" style="display:none;">
    <div id="loading_box" class="loader"></div>
</div>

<fieldset class="form-list">
    <form name="addcard" method="post" action="<?php echo Mage::getUrl('ccgateway/cardmanagement/savePayment',array('_secure'=>true)); ?>">
        <ul id="add_new_card_form_<?php echo $_code ?>" style="display:block">

            <li>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <label for="<?php echo $_code ?>_cc_alias" class="required"><em>*</em><?php echo $this->__('Alias') ?></label>
                <div class="input-box">
                    <input type="text"  title="<?php echo $this->__('Alias') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_profile_name" name="addcard[cc_profile_name]" value=""  required/>
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <div class="input-box">
                    <input type="text"  title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="addcard[cc_owner]" value="<?php #echo $this->escapeHtml($this->getInfoData('cc_owner'))  ?>" required />
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_type" class="required validate-cc-type "><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
                <div class="input-box">

                    <select id="ccgateway_cc_type" name="addcard[cc_type]" onchange="resetcardinfo();"  title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-select" required>
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                        <?php foreach ($this->getCcTypes() as $ccType): ?>
                            <option value="<?php echo $ccType['value']; ?>" ><?php echo $ccType['label'] ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>

            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">

                    <input type="text" onblur="valid_credit_card(value, '<?php echo $isTestMode; ?>', '<?php echo $siteName; ?>', '<?php echo $errorLogURL; ?>')"  onkeypress="javascript:return validate(event, 'ccgateway_cc_number_org');
                            blockNonNumbers(this, event, false, false)" id="ccgateway_cc_number_org" name="addcard[cc_number_org]" title="<?php echo $this->__('Credit Card Number') ?>" maxlength="16"  class="input-text required-entry" value="" required />
                    <input type="hidden"   id="ccgateway_cc_number" name="addcard[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text" value="" required />
					<div class="validation-advice" id="testError" style="display: none;"></div>
                </div>

            </li>
            <li><div id="response"></div></li>

            <li>
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="addcard[cc_exp_month]" class="month validate-cc-exp required-entry" style="width: 150px;" required>
                            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>" ><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration_yr" name="addcard[cc_exp_year]" class="year required-entry" style="width: 150px;" required>
                            <?php foreach ($this->getCcYears() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>" ><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>

                </div>
            </li>


            <li>
                <label for="<?php echo $_code ?>_cc_Billing"><strong><?php echo $this->__('Billing Information') ?></strong></label>
            </li>
            <?php if($address){ ?>
            <li>
                <div class="input-box">
                    <div class="v-fix">
                        <span style="margin-bottom: 10px;">
                            <input type="checkbox" title="<?php echo $this->__('Use default bill to address') ?>"
                                   onclick="javascript:return showDefaultAddress('<?php echo $billingStreet; ?>', '<?php echo $billingCity; ?>', '<?php echo $billingRegion; ?>', '<?php echo $billingCountry; ?>', '<?php echo $billingPostCode; ?>', '<?php echo $billingTelephone; ?>')"
                                   id="ccgateway_default_address" name="addcard[default_address]" value=""  />  
                        </span>
                        <label for="<?php echo $_code ?>_cc_wallet"><?php echo $this->__('Use default bill to address') ?></label>
                    </div>
                </div>

            </li>
            <?php } ?>

            <div id="save_card" style="display:block;">
                <li>
                    <label for="<?php echo $_code ?>_cc_street" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('Street Address') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_street" name="addcard[cc_street]" value="" required />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_city" name="addcard[cc_city]" value="" required />
                    </div>
                </li>

                <li>

                    <label for="<?php echo $_code ?>_cc_region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <?php $regionCollection = Mage::getModel('directory/region_api')->items("US"); ?>
                        <select name='addcard[cc_region]' id='<?php echo $_code ?>_cc_region' class="required-entry validate-select" required>
                            <option>Please select region, state or province</option>
                            <?php
                            foreach ($regionCollection as $region) {
                                ?>
                                <option value="<?php echo $region['name'] ?>"   ><?php echo $region['name'] ?></option>
                                <?php
                            }
                            ?>

                        </select>
                    </div>

                </li>



                <li>
                    <div class="field">
                        <label for="<?php echo $_code ?>_cc_country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php
                            $_countries = Mage::getResourceModel('directory/country_collection')
                                    ->loadData()
                                    ->toOptionArray(false)
                            ?>
                            <?php if (count($_countries) > 0): ?>
                                <select name="addcard[cc_country]" id="<?php echo $_code ?>_cc_country" required>
                                    <option value="">-- Please Select --</option>
                                    <?php foreach ($_countries as $_country): ?>
                                        <option value="<?php echo $_country['value'] ?>" >
                                            <?php echo $_country['label'] ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>

                        </div>
                    </div>
                </li>

                <li>
                    <label for="<?php echo $_code ?>_cc_postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('Zip/Postal Code') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_postcode" name="addcard[cc_postcode]" value=""  required />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('telephone') ?>" class="input-text required-entry"  onkeypress="javascript:return validate(event, 'ccgateway_cc_number_org');
                                blockNonNumbers(this, event, false, false)" maxlength="10" id="<?php echo $_code ?>_cc_telephone" name="addcard[cc_telephone]" value="" required />
                    </div>
                </li>

                <button id="addcardbutton" class="button" style="margin-top: 10px;" type="submit" title="<?php echo $this->__('Add') ?>" class="button" onclick="<?php echo $this->getUrl('ccgateway/cardmanagement/savecard'); ?>"><span><span><?php echo $this->__('Add') ?></span></span></button>

            </div>


            <?php echo $this->getChildHtml() ?>

        </ul>
    </form>
</fieldset>
