<div class="padder">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="page-head">
	    <h3><?php echo $this->__('My Servers') ?></h3>
	</div>
	
	<div class="box simple_contact">
	<form id="noc_zalert_edit" name="noc_zalert_edit" action="/noc/zalert/save" method="post">
	<script type="text/javascript">
	//< ![CDATA[
	var customForm = new VarienForm('noc_zalert_edit');
	//]]>
	</script>
	    <fieldset class="group-select">
	        <h4 class="legend">Server Alert Contact</h4>
	        <p></p>
	        <ul>
	        <li>
                <div class="input-box">
                    <label for="name">Name <span class="required">*</span></label><br />
                    <input name="contact_name" id="contact_name" title="Name" value="" class="required-entry input-text" type="text" />
                </div>
                <div class="input-box">
                    <label for="email">Email Address <span class="required">*</span></label><br />
                    <input name="contact_email" id="contact_email" title="Email" value="" class="required-entry input-text validate-email" type="text" />
                </div>
                <input type="hidden" name="server_id" id="server_id" value="<?php echo $this->getServerId() ?>">
			</li>
	        </ul>
	    </fieldset>
	    <div class="button-set">
	        <p class="required">* Required Fields</p>
	        <button class="form-button" type="submit"><span>Submit</span></button>
	    </div>
	</form>
	</div>
</div>