<?php 
function f_get_random_string($length){
  $acceptedChars = 'AZERTYUIOPQSDFGHJKLMWXCVBN0123456789';
  $max = strlen($acceptedChars)-1;
  $session = null;
  $rnd = '';
  for($i=0; $i < $length; $i++) {
   $rnd .= $acceptedChars{mt_rand(0, $max)};
  }
  return $rnd;
}
?>

<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<div class="padder">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head">
    <h3><?php echo $this->__('My Referrer Information') ?></h3>
</div>

<?php
$customerData = Mage::getSingleton('customer/session')->getCustomer();
#print_r($customerData);
try {
  $affiliate = Mage::getModel('rebill/affiliate')->getAffiliateByCustomerId($customerData->getEntityId());
#print_r($affiliate);
} catch (Exception $e) {
  $data = array('customer_id' => $customerData->getEntityId(),
      'ref_key' => f_get_random_string(15),
      'ref_percentage' => 10,
      'payout' => 0);
    #print_r($data);
    $load = Mage::getModel('rebill/affiliate');
    $load->setData($data);
    $load->save();
    $affiliate = Mage::getModel('rebill/affiliate')->getAffiliateByCustomerId($customerData->getEntityId());
}

?>

 <span style="font-weight:bold">Referrer URL:</span>

<?php
$refurl = 'http://'.$_SERVER['HTTP_HOST'].'/affiliate.php?refId='.$affiliate->getRefKey();
print '<a href="'.$refurl.'">'.$refurl.'</a>';
?>
<br/>

<span style="font-weight:bold">Referal Balance:</span>
<?php print $affiliate->getPayout(); ?>

<br/>
<br/>
<span style="font-weight:bold">Associated Referrer Account Servers:</span>
<br/>
<?php
  $servers = Mage::getModel('rebill/affiliate')->getServersByAffiliate($affiliate->getAffiliateId());
  #print_r($servers);
  foreach ($servers as $server) {
    print $server.'<br/>';
  }
?>
</div>
