<?php

	$baseUrl = $this->getBaseUrl();
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
	$skinUrl = $this->getSkinUrl();

?>
<?php $_helper = Mage::getModel('catalog/category') ?>
<?php $_categories = $_helper->getCategories(5) ?>
<?php if (count($_categories) > 0): ?>
            <?php foreach ($_categories as $_category):?>
                <li>
                    <a href="<?php echo $_category->getUrl(); ?>" title="<?php echo $_category->getName() ?>">
                        <?php echo $_category->getName() ?>
                    </a>
                </li>
            <?php endforeach;?>
<?php endif; ?>

