<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/
	$baseUrl = $this->getBaseUrl();
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
	$skinUrl = $this->getSkinUrl();
?>
<footer class="footer-360">
    <div class="container footer-wrapper">
        <div class="col-md-6 col-sm-6 no-gutter">
            <a class="footer-logo" href="/">
                  <img src="<?php echo $skinUrl;?>images/logo-green-mantis.c9b80a1c2165.png" alt="360 Fly" title="360 Fly">
            </a>
            <ul class="inline-list footer-nav">
                <li><a href="http://blog.360fly.com">Blog</a>
                </li>
                <li><a href="https://forums.360fly.com/">Forums</a>
                </li>
                <li><a href="<?php echo $baseUrl;?>about-360fly">About Us</a>
                </li>
                <li><a href="<?php echo $baseUrl;?>press">Press</a>
                </li>
                <li><a href="http://careers.360fly.com">Careers</a>
                </li>
                <li><a href="<?php echo $baseUrl;?>b2b/">B2B Portal</a>
                </li>
            </ul>
            <p class="copyright hide-mobile"><?php echo $this->getCopyright(); ?> <br/> 360fly is a trademark of 360fly, Inc.</p>
            <ul class="inline-list footer-nav hide-mobile footer-bottom-nav">
                <li><a href="https://support.360fly.com">Contact Us</a>
                </li>
                <li><a href="<?php echo $baseUrl;?>terms-use/">Terms of Use</a>
                </li>
                <li><a href="<?php echo $baseUrl;?>privacy-policy/">Privacy Policy</a>
                </li>
            </ul>
        </div>
        <div class="col-md-6 col-sm-6 contact no-gutter text-right">
            <div class="row">
                <div class="col-xs-12 no-gutter">
                    <span class="stayuptodate">STAY UP TO DATE</span>
                    <form action="//360fly.us3.list-manage.com/subscribe?u=834d6982a45baceab74d738d8&id=46c68bca25" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" novalidate="">
                        <input value="" name="EMAIL" class="required email mailSignUp btn btn-footer" id="mce-EMAIL" type="email" placeholder="EMAIL">
                    </form>
                    <a class="btn btn-default retailer" href="<?php echo $baseUrl;?>store-locator/">FIND A RETAILER</a>
                </div>
            </div>
            <ul class="social-icon">
                <li><a target="_blank" href="https://instagram.com/360fly"><span class="icon-instagram-jul15 footer_icon"></span></a>
                </li>
                <li><a target="_blank" href="https://www.facebook.com/360fly"><span class="icon-facebook-jul15 footer_icon"></span></a>
                </li>
                <li><a target="_blank" href="https://twitter.com/360fly"><span class="icon-twitter-jul15 footer_icon"></span></a>
                </li>
                <li><a target="_blank" href="http://blog.360fly.com/"><span class="icon-tumblr-jul15 footer_icon"></span></a>
                </li>
                <li><a target="_blank" href="https://www.youtube.com/channel/UCBNph_5dIKPQFS3IsIVXJfQ"><span class="icon-youtube-jul15 footer_icon"></span></a>
                </li>
            </ul>
            <div class="mobile-copyright show-mobile">
                <p class="copyright"><?php echo $this->getCopyright(); ?> <br/> 360fly is a trademark of 360fly, Inc.</p>
                <ul class="inline-list footer-nav ">
                    <li><a href="https://support.360fly.com">Contact Us</a>
                    </li>
                    <li><a href="<?php echo $baseUrl;?>terms-use/">Terms of Use</a>
                    </li>
                    <li><a href="<?php echo $baseUrl;?>privacy-policy/">Privacy Policy</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
	<!--end of container-->
</footer>
