<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/
	$baseUrl = $this->getBaseUrl();
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
	$skinUrl = $this->getSkinUrl();
?>
<!-- New Header Starts -->
<div class="container-fluid header-bg-black h95px"></div>
<div class="container-fluid header-bg-green h36px hidden-xs"></div>
<div class="container-fluid header-bg-green h5px visible-xs"></div>
<div class="header container wrapper-width hidden-xs">
	<div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
		<div class="h95px logo col-sm-3 col-md-3 col-lg-3"><a href="<?php echo $baseUrl;?>"><img src="<?php echo $skinUrl;?>images/logo.png" alt="360Fly Logo" title="360 Fly"/></a></div>
		<div class="h95px navbar col-sm-9 col-md-9 col-lg-9">
			<div id="navbar3" class="navbar-collapse collapse">
				<ul class="nav navbar-nav  navbar-right ">
				  <li class="shopping-cart visible-xs">
					<a href="<?php echo $baseUrl;?>shop"><span class="icon-shopping-cart"></span></a>
				  </li>
				  <li class="menu1" ><a href="<?php echo $baseUrl;?>shop">SHOP</a>
					<ul class="submenu1 submenu">
					  <li><a href="<?php echo $baseUrl ;?>cameras">CAMERAS</a></li>
					  <li><a href="<?php echo $baseUrl ;?>accessories">ACCESSORIES</a></li>
					  <li><a href="<?php echo $baseUrl;?>/faq/">FAQ</a></li>

					</ul>
				  </li>
				  <li class="divider-vertical menu2"><a href="<?php echo $baseUrl ;?>apps">APPS</a>
					<ul class="submenu2 submenu">
					  <li><a href="<?php echo $baseUrl;?>apps/">MOBILE</a></li>
					  <li><a href="<?php echo $baseUrl;?>Director">DESKTOP</a></li>

					</ul>
				  </li>
				  <li class="divider-vertical"><a href="<?php echo $baseUrl;?>videos">VIDEO</a></li>
				  <li class="divider-vertical"><a href="<?php echo $baseUrl;?>community">COMMUNITY</a></li>
				  <li class="divider-vertical"><a href="http://support.360fly.com/">SUPPORT</a></li>
				  <li class="shopping-cart hide-mobile">
					<a href="<?php echo $baseUrl;?>shop">
					  <span class="icon-shopping-cart"></span>
					</a>
				  </li>
				</ul>
			  </div>
		</div>
	</div>
</div>
<div class="header container visible-xs">
	<div class="col-xs-12">
		<div class="h95px logo col-xs-6"><a href="<?php echo $baseUrl;?>"><img src="<?php echo $skinUrl;?>images/logo.png" alt="360Fly Logo" /></a></div>
		<div class="h95px col-xs-12 abs">
			<nav class="mobilenav navbar navbar-inverse navbar-static-top" role="navigation">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>

					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							  <li class="shopping-cart visible-xs">
								<a href="<?php echo $baseUrl;?>shop"><span class="icon-shopping-cart"></span></a>
							  </li>
							  <li class="menu1" ><a href="<?php echo $baseUrl;?>shop">SHOP</a>
								<ul class="submenu1 submenu">
									<li><a href="<?php echo $baseUrl ;?>cameras">CAMERAS</a></li>
									<li><a href="<?php echo $baseUrl ;?>accessories">ACCESSORIES</a></li>
									<li><a href="<?php echo $baseUrl;?>/faq/">FAQ</a></li>

								</ul>
							  </li>
							  <li class="divider-vertical menu2"><a href="<?php echo $baseUrl ;?>apps">APPS</a>
								<ul class="submenu2 submenu">
								  <li><a href="<?php echo $baseUrl;?>apps/">MOBILE</a></li>
								  <li><a href="<?php echo $baseUrl;?>Director">DESKTOP</a></li>

								</ul>
							  </li>
							  <li class="divider-vertical"><a href="<?php echo $baseUrl;?>videos">VIDEO</a></li>
							  <li class="divider-vertical"><a href="<?php echo $baseUrl;?>community">COMMUNITY</a></li>
							  <li class="divider-vertical"><a href="http://support.360fly.com/">SUPPORT</a></li>
							  <li class="shopping-cart hide-mobile">
								<a href="<?php echo $baseUrl;?>shop">
								  <span class="icon-shopping-cart"></span>
								</a>
							  </li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
	</div>
</div>

<!-- New Header Ends -->