<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/
	$baseUrl = $this->getBaseUrl();
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
	$skinUrl = $this->getSkinUrl();
	$currentUrl = Mage::helper('core/url')->getCurrentUrl();
	$cleanBaseUrl = Mage::getStoreConfig(Mage_Core_Model_Url::XML_PATH_SECURE_URL);
	$shopUrl = $cleanBaseUrl.'shop';
	$communityUrl = $cleanBaseUrl.'community';
	$appsUrl = $cleanBaseUrl.'apps';
	$cartCount = $this->helper('checkout/cart')->getSummaryCount();
	$appsClass = 'x';
	$communityClass = 'x';
	$menuClass = 'non-shop-page';
	if( strpos($currentUrl, $shopUrl) !== false ){
		$menuClass = 'is-shop-page';
	}
	if( strpos($currentUrl, $communityUrl) !== false ){
		$communityClass = 'is-community-page';
	}
	if( strpos($currentUrl, $appsUrl) !== false ){
		$appsClass = 'is-apps-page';
	}
?>
<!-- New Header Starts -->
<div class="container-fluid header-bg-black h95px"></div>
<div class="container-fluid header-bg-green h36px hidden-xs"></div>
<div class="container-fluid header-bg-green h5px visible-xs"></div>
<div class="header container wrapper-width hidden-xs">
	<div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
		<div class="h95px logo col-sm-3 col-md-3 col-lg-3"><a href="<?php echo $baseUrl;?>"><img src="<?php echo $skinUrl;?>images/logo.png" alt="360Fly Logo" title="360 Fly"/></a></div>
		<div class="h95px navbar col-sm-9 col-md-9 col-lg-9">
			<div id="navbar3" class="navbar-collapse collapse">
				<ul class="nav navbar-nav  navbar-right ">
				  <li class="shopping-cart visible-xs">
					<a href="<?php echo $baseUrl;?>shop"><span class="icon-shopping-cart"></span></a>
				  </li>
				  <li class="menu1 <?php echo $menuClass?>-container" ><a class="<?php echo $menuClass?>-anchor" href="<?php echo $baseUrl;?>shop">SHOP</a>
					<ul class="submenu1 submenu <?php echo $menuClass;?>">
                        <?php echo $this->getChildHtml('category.links');?>
                        <li><a href="<?php echo $baseUrl;?>faq/">FAQ</a></li>

					</ul>
				  </li>
				  <li class="divider-vertical menu2 <?php echo $appsClass?>-container"><a class="<?php echo $appsClass?>-anchor" href="<?php echo $baseUrl ;?>apps">APPS</a>
					<ul class="submenu2 submenu">
					  <li><a href="<?php echo $baseUrl;?>apps/">MOBILE</a></li>
					  <li><a href="<?php echo $baseUrl;?>Director">DESKTOP</a></li>

					</ul>
				  </li>
				  <li class="divider-vertical"><a href="https://360fly.com/videos/">VIDEO</a></li>
				  <li class="divider-vertical <?php echo $communityClass?>-container" "><a class="<?php echo $communityClass?>-anchor" href="<?php echo $baseUrl;?>community">COMMUNITY</a></li>
				  <li class="divider-vertical"><a href="http://support.360fly.com/">SUPPORT</a></li>
				  <li class="shopping-cart hide-mobile">
					<a class="cart-color" href="<?php echo $this->helper('checkout/cart')->getCartUrl();?>">
						<?php echo $cartCount > 0 ? $cartCount : ''; ?>
				  		<span class="icon-shopping-cart"></span>
					</a>
				  </li>
				</ul>
			  </div>
		</div>
        <div class="abs header-account-links"><?php echo $this->getChildHtml('accountLinks');?></div>
	</div>
</div>
<!-- MOBILE MENU -->
<div class="header container visible-xs header-mobile">
	<div class="col-xs-12">
		<div class="h95px logo col-xs-4"><a href="<?php echo $baseUrl;?>"><img src="<?php echo $skinUrl;?>images/logo.png" alt="360Fly Logo" /></a></div>
		<div class="h95px col-xs-11 abs no-gutter hamburger-menu">
			<ul>
				<li class="toggle-topbar menu-icon open" id="nav-icon3">
					<a href="#">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>
				</li>
			</ul>
			<section class="top-bar-section" style="display:none;">
				<!-- Right Nav Section -->
				<ul class="">
					<li class="shopping-cart show-mobile">
						<a class="cart-color cart-count" href="<?php echo $baseUrl;?>checkout/cart">
							<?php echo $cartCount > 0 ? $cartCount : ''; ?>
							<span class="icon-shopping-cart"></span>
						</a>
					</li>
					<li class="show-mobile"><a href="<?php echo $baseUrl;?>shop">Shop</a></li>
					<li class="show-mobile"><a href="<?php echo $baseUrl;?>apps">APPS</a></li>
					<li><a href="videos.360lfy.com/">VIDEO</a></li>
					<li><a href="<?php echo $baseUrl;?>/community">COMMUNITY</a></li>

					<li><a href="https://support.360fly.com">SUPPORT</a></li>
					<hr/>
					<?php echo $this->getChildHtml('category.links');?>
					<hr/>
                    <li  class="header-xs-account-links"><?php echo $this->getChildHtml('accountLinks');?></li>
					<li><a href="<?php echo $baseUrl;?>faq/">FAQ</a></li>
				</ul>


			</section>
		</div>
	</div>
</div>

<!-- New Header Ends -->
