<?php
/**
 * @brief Inherited for having additonal info.
 * @category Magento CardConnect Payment Module
 * @author CardConnect
 * @copyright Portions copyright 2014 CardConnect
 * @copyright Portions copyright Magento 2014
 * @license GPL v2, please see LICENSE.txt
 * @access public
 * @version $Id: $
 *
 **/
 
/**
Magento
*
NOTICE OF LICENSE
*
This source file is subject to the Open Software License (OSL 3.0)
that is bundled with this package in the file LICENSE.txt.
It is also available through the world-wide-web at this URL:
http://opensource.org/licenses/osl-3.0.php
If you did not receive a copy of the license and are unable to
obtain it through the world-wide-web, please send an email
to license@magentocommerce.com so we can send you a copy immediately.
*
@category Cardconnect
@package Cardconnect_Ccgateway
@copyright Copyright (c) 2014 CardConnect (http://www.cardconnect.com)
@license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
*/

?>

<form id="edit_form" method="post" action="<?php echo $this->getSaveUrl() ?>">
    <?php echo $this->getBlockHtml('formkey') ?>
    <?php $_order = $this->getCreditmemo()->getOrder() ?>
    <?php echo $this->getChildHtml('order_info') ?>

    <?php if (!$_order->getIsVirtual()): ?>
        <div class="box-left" style="width:100%">
        <?php else: ?>
            <div class="box-right">
            <?php endif; ?>
           
        </div>
            
             <!--Payment Information-->
            <div class="entry-edit" style="float: left;">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
                </div>
                <fieldset>
                    <div><?php echo $this->getChildHtml('order_payment') ?></div>
                    <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
                    <?php /* if ($this->getCreditmemo()->canRefund()): ?>
                      <input type="checkbox" name="creditmemo[do_refund]" id="creditmemo_do_refund" value="1" checked/>
                      <label for="creditmemo_do_refund" class="normal"><?php echo Mage::helper('sales')->__('Refund Amount') ?></label>
                      <?php endif; */ ?>
                </fieldset>
            </div>
             <!--Payment Information end-->
            
            
            
            
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box-right" style="width:100%">
                <!--Shipping Address-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping Information') ?></h4>
                    </div>
                    <fieldset>
                        <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>
                        <?php echo $this->helper('sales')->__('Total Shipping Charges'); ?>:

                        <?php if ($this->helper('tax')->displaySalesPriceInclTax($this->getSource()->getStoreId())): ?>
                            <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                        <?php else: ?>
                            <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                        <?php endif; ?>
                        <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                        <?php echo $_excl; ?>
                        <?php if ($this->helper('tax')->displaySalesBothPrices($this->getSource()->getStoreId()) && $_incl != $_excl): ?>
                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                        <?php endif; ?>
                    </fieldset>
                </div>
            </div>
        <?php endif; ?>
        <div class="clear"></div>

        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items to Refund') ?></h4>
            </div>
        </div>
        <div id="creditmemo_item_container">
            <?php echo $this->getChildHtml('order_items') ?>
        </div>
</form>
