<?php
$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
?>

<!-- Accessory Mount Carousel Begin -->
<div class=" product-promotion">
	<div class="container">
		<h2>GO ANYWHERE.
			MOUNT EVERYWHERE.
		</h2>
		<div class="col-sm-10 col-sm-offset-1 product-slider ">
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>camera-dive-housing"><img src="<?php echo $skinUrl; ?>images/accessories/dive_housing.png" alt="Camera Dive Housing" title="Camera Dive Housing" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>camera-dive-housing" title="Camera Dive Housing">Camera Dive Housing</a></p>

					  <a href="<?php echo $baseUrl;?>camera-dive-housing" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vr-headset"><img src="<?php echo $skinUrl; ?>images/accessories/VR_headset.png" alt="VR Headset" title="VR Headset" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vr-headset" title="VR Headset">VR Headset</a></p>

					  <a href="<?php echo $baseUrl;?>vr-headset" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>

			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>pov-pole"><img src="<?php echo $skinUrl; ?>images/accessories/pov_pole.png" alt="POV Pole" title="POV Pole" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>pov-pole" title="POV Pole">POV Pole</a></p>

					  <a href="<?php echo $baseUrl;?>pov-pole" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>floating-handgrip"><img src="<?php echo $skinUrl; ?>images/accessories/floating_handgrip.png" alt="" title="Floating Handgrip" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>floating-handgrip" title="Floating Handgrip">Floating Handgrip</a></p>

					  <a href="<?php echo $baseUrl;?>floating-handgrip" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>




			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>suction-mount"><img src="<?php echo $skinUrl; ?>images/accessories/suction-mount-4k.jpg" alt="Suction Mount (¼-20)" title="Suction Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>suction-mount" title="Suction Mount (¼-20)">Suction Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>suction-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>mount-kit"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Action_Mount.jpg" alt="Mount Kit (¼-20)" title="Mount Kit (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>mount-kit" title="Mount Kit (¼-20)">Mount Kit (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>mount-kit" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vented-helmet-mount"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Helmet_Mount.png" alt="Vented Helmet Mount (¼-20)" title="Vented Helmet Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vented-helmet-mount" title="Vented Helmet Mount (¼-20)">Vented Helmet Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>vented-helmet-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>handle-bar-mount"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Handlebar_Mount.png" alt="Handlebar Mount (¼-20)" title="Handlebar Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>handle-bar-mount" title="Handlebar Mount (¼-20)">Handlebar Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>handle-bar-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>

			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>rugged-handlebar-mount"><img src="<?php echo $skinUrl; ?>images/accessories/rugged_handlebar.png" alt="Rugged Handlebar Mount (¼-20)" title="Rugged Handlebar Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>rugged-handlebar-mount" title="Rugged Handlebar Mount (¼-20)">Rugged Handlebar Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>rugged-handlebar-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>tripod-grip"><img src="<?php echo $skinUrl; ?>images/accessories/tripod_grip.png" alt="Tripod Grip (¼-20)" title="Tripod Grip (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>tripod-grip" title="Tripod Grip (¼-20)">Tripod Grip (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>tripod-grip" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			



		</div>
	</div>
</div>
<!-- Accessory Mount Carousel End -->
