<?php
$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
?>

<!-- Accessory Mount Carousel Begin -->
<div class=" product-promotion">
	<div class="container">
		<h2>GO ANYWHERE.
			MOUNT EVERYWHERE.
		</h2>
		<div class="col-sm-10 col-sm-offset-1 product-slider ">
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>action-cam-adapter-quicktwist"><img src="<?php echo $skinUrl; ?>images/accessories/aca-quicktwist.jpg" alt="Action Cam Mount (HD w/QuickTwist)" title="Action Cam Mount (HD w/QuickTwist)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>action-cam-adapter-quicktwist" title="Action Cam Mount (HD w/QuickTwist)">Action Cam Mount (HD w/QuickTwist)</a></p>

					  <a href="<?php echo $baseUrl;?>action-cam-adapter-quicktwist" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>handle-bar-mount-quicktwist"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Handlebar_mount.jpg" alt="Handlebar Mount (HD w/QuickTwist)" title="Handlebar Mount (HD w/QuickTwist)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>handle-bar-mount-quicktwist" title="Handlebar Mount (HD w/QuickTwist)">Handlebar Mount (HD)</a></p>

					  <a href="<?php echo $baseUrl;?>handle-bar-mount-quicktwist" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>suction-mount-quicktwist"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Suction_Mount.jpg" alt="Suction Mount (HD w/QuickTwist)" title="Suction Mount (HD w/QuickTwist)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>suction-mount-quicktwist" title="Suction Mount (HD w/QuickTwist)">Suction Mount (HD w/QuickTwist)</a></p>

					  <a href="<?php echo $baseUrl;?>suction-mount-quicktwist" class="btn  btn-custom">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>tripod-adapter-quicktwist"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Tripod_Adapter.jpg" alt="Tripod Adapter (HD w/QuickTwist)" title="Tripod Adapter (HD w/QuickTwist)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>tripod-adapter-quicktwist" title="Tripod Adapter (HD w/QuickTwist)">Tripod Adapter (HD w/QuickTwist)</a></p>

					  <a href="<?php echo $baseUrl;?>tripod-adapter-quicktwist" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vented-helmet-mount-quicktwist"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Helmet_Mount.jpg" alt="Vented Helmet Mount (HD w/QuickTwist)" title="Vented Helmet Mount (HD w/QuickTwist)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vented-helmet-mount-quicktwist" title="Vented Helmet Mount (HD w/QuickTwist)">Vented Helmet Mount (HD w/QuickTwist)</a></p>

					  <a href="<?php echo $baseUrl;?>vented-helmet-mount-quicktwist" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>

			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>camera-dive-housing"><img src="<?php echo $skinUrl; ?>images/accessories/dive_housing.png" alt="Camera Dive Housing" title="Camera Dive Housing" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>camera-dive-housing" title="Camera Dive Housing">Camera Dive Housing</a></p>

					  <a href="<?php echo $baseUrl;?>camera-dive-housing" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vr-headset"><img src="<?php echo $skinUrl; ?>images/accessories/VR_headset.png" alt="VR Headset" title="VR Headset" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vr-headset" title="VR Headset">VR Headset</a></p>

					  <a href="<?php echo $baseUrl;?>vr-headset" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>suction-mount"><img src="<?php echo $skinUrl; ?>images/accessories/suction-mount-4k.jpg" alt="Suction Mount (¼-20)" title="Suction Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>suction-mount" title="Suction Mount (¼-20)">Suction Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>suction-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>mount-kit"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Action_Mount.jpg" alt="Mount Kit (¼-20)" title="Mount Kit (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>mount-kit" title="Mount Kit (¼-20)">Mount Kit (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>mount-kit" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vented-helmet-mount"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Helmet_Mount.png" alt="Vented Helmet Mount (¼-20)" title="Vented Helmet Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vented-helmet-mount" title="Vented Helmet Mount (¼-20)">Vented Helmet Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>vented-helmet-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>handle-bar-mount"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Handlebar_Mount.png" alt="Handlebar Mount (¼-20)" title="Handlebar Mount (¼-20)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>handle-bar-mount" title="Handlebar Mount (¼-20)">Handlebar Mount (¼-20)</a></p>

					  <a href="<?php echo $baseUrl;?>handle-bar-mount" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
		</div>
	</div>
</div>
<!-- Accessory Mount Carousel End -->
