<!--Google translate code BEGIN-->
<div id="google_translate_element" style="float:right;"></div><br><br><script type="text/javascript">
function googleTranslateElementInit() {
	new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.FloatPosition.TOP_RIGHT, gaTrack: true, gaId: 'UA-46834247-1'}, 'google_translate_element');
}
$(".goog-te-gadget-simple").css("border", "0");
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<!--Google translate code END-->        
