<?php
/*Write conditions here to switch video source based on request URL*/
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$videoId = $mediaUrl."videos/promotional_4k.mp4";
$videoPoster = "https://d3a8ot8p8m13p6.cloudfront.net/videos/promotional_thumbnail.jpg";
if(count($this->videoid)> 0){
    $videoId = $this->videoid;
}

if(count($this->videoposter) >0){
	$videoPoster =   $this->videoposter;
}
$_product = $this->getProduct();
 //echo $_product;
//$productResolution = strtolower($_product->getAttributeText('camera_resolution'));
//echo $productResolution;
?>


<div class="video-player hide-on-uncompatible-browser" id="player">
    <div class="video-container">
        <div id="video">
            <section id="one-up">
                <div class="videocontent embed-responsive embed-responsive-16by9">
                    <div class="video-overlay-content">
                        <div class="video-overlay-text no-display">
                            <p>CLICK AND DRAG BELOW TO</p>
                            <p><b>EXPERIENCE 360&deg;</b></p>
                        </div>
                        <!-- <div class="swipe-icon-yt">
                        </div> -->
                    </div>
					<video id="video_4k" class="video-js video360 vjs-default-skin vjs-big-play-centered home-video" controls preload="auto"  data-flyautoplay="off" alt="360 camera, 360 video, panoramic video camera, VR video camera"
					poster="<?php echo $videoPoster; ?>" data-setup="{}" >
						<source src="<?php echo $videoId;?>" type='video/mp4'>
					</video>
                    <!-- <div class="youtube-player" id="player-yt" data-id="<?php //echo $videoId;?>"></div> -->
                </div>
            </section>
        </div>
    </div>
</div>

<script>

    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    var player;
     function onYouTubeIframeAPIReady() {
       player = new YT.Player('player-yt', {
         height: '100%',
         width: '100%',
         videoId: '<?php echo $videoId;?>',
         events: {
           //'onReady': onPlayerReady,
         }
       });
     }
     function onPlayerReady(event) {
        event.target.playVideo();
      }

</script>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/pages/videojs.phtml')->toHtml(); ?>
