<?php
    /*Write conditions here to switch video source based on request URL*/
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
?>

<div class="hide-on-uncompatible-browser" id="">
    <div class="video-container">
        <div id="video">
            <section id="one-up">
                <div class="videocontent embed-responsive embed-responsive-16by9">
                    <div class="video-overlay-content">
                        <div class="swipe-icon">
                        </div>
                        <div class="video-overlay-text">
                            <p>CLICK AND DRAG BELOW TO EXPERIENCE 360&deg; VIDEO</p>
                        </div>
                    </div>
                    <video id="video_dewtour" class="video-js video360 vjs-default-skin vjs-big-play-centered devtour-video" controls preload="auto"  data-flyautoplay="off" alt="360 camera, 360 video, panoramic video camera, VR video camera"
                            data-setup="{}" >
                        <source src="<?php echo  $mediaUrl.'videos/oBjJau5yMU8TvgyKk2o4Uc.mp4';?>" type='video/mp4'>
                    </video>
                </div>
            </section>
        </div>
    </div>
</div>
