<?php

	$baseUrl = $this->getBaseUrl();
	$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
	$skinUrl = $this->getSkinUrl();

?>

<div class="base-content clearfix no-route-container">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 redirect">
            <span class="icon-player-fly brand-gradient fly_redirect"></span>
            <h2>Not Found</h2>
            <h4 class="coming-soon active">You reached a page that does not exist.
			<br>Learn about our latest product, <a href="<?php echo $baseUrl;?>shop">360fly HD</a>, or view interactive <a href="<?php echo $baseUrl;?>videos/">360&deg; videos</a></h4>
        </div>
    </div>
</div>




<style type="text/css">
.no-route-container .redirect {color: #fff;margin: 0 auto;width: 100%;padding-top: 200px;padding-bottom: 130px;text-align: center;}
.no-route-container .base-content {height: 75%;}
.no-route-container .fly_redirect {font-size: 80px;}
.no-route-container .coming-soon {margin-top: 20px;color: #fff;}
.no-route-container .coming-soon a {color: #78BE20;}
.no-route-container{background: url("<?php echo $skinUrl;?>images/facets.jpg") no-repeat top center;}
.no-route-container h2{font-size: 45px;}
.no-route-container h4{font-size: 20px;}
</style>