<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

?>

<div class="main-container">
	<div class="about_img">
		<div class= "col-sm-12 about_img_text">
			<h1>About 360fly</h1>
		</div>
	</div>
	<div class="container about-contain">
		
			<div class="col-sm-9 col-md-9 col-lg-8 no-gutter">   
				<h2>About Us</h2>
				<p>At 360fly, we design and create 360° cameras and technology that inspire people to capture, share and experience their lives in immersive, interactive 360° video. Our passion and unrelenting pursuit of innovation have led us to redefine what is possible in video, virtual reality and visual storytelling.</p>
			</div>
			<div class="col-sm-3 col-md-3 col-lg-4 no-gutter">
				<a href="<?php echo $baseUrl;?>#top" class="btn to-top round pull-right">Back to Top</a>
			</div>
		
	</div>
	<div class="container about-contain">
		
			<div class="col-sm-9 col-md-9 col-lg-8 no-gutter">   
				<h2>Our History</h2>
				<p>360fly started up in a robotics lab out of Carnegie Mellon University. A technology once used for robots has quickly transformed into a technology we use to capture life’s most memorable moments. From military training and aviation to stadium implosions and music videos we’ve captured it all. In 2011, we launched the world’s first consumer 360 lens for iPhone- GoPano Micro, along with the world’s first 360 video sharing service, GoPano.com. Today we’re building 360fly, a camera that captures everything, in all directions, without limits. See it all.</p>
			</div>
			<div class="col-sm-3 col-md-3 col-lg-4 no-gutter">
				<a href="<?php echo $baseUrl;?>#top" class="btn to-top round pull-right">Back to Top</a>
			</div>
		
	</div>
	<div class="container about-contain career-section">
		
			<div class="col-sm-9 col-md-9 col-lg-8 no-gutter">   
				<h2>Careers</h2>
				<p><a href="http://careers.360fly.com">View Job Postings</a></p>
			</div>
			<div class="col-sm-3 col-md-3 col-lg-4 no-gutter">
				<a href="<?php echo $baseUrl;?>#top" class="btn to-top round pull-right">Back to Top</a>
			</div>
		
	</div>
</div>  