<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>
<div class="base-content clearfix apps-container">
		<div class="full-width" id="apps-header">
	        <div class="container wrapper-width">
	        	<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 no-gutter">
	                <h1>The apps that power your 360° world.</h1>
					<p>The 360fly mobile and desktop 360fly Director apps serve as your camera’s viewfinder, controller, editor, effects studio, library and more.</p>
            	</div>
	        </div>
        </div>
        <div class="full-width" id="miss-share">
	        <div class="container wrapper-width">
	        	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-gutter">
		            <h2>Miss nothing, share everything.</h2>
					<p>The 360fly apps make capturing, editing and sharing 360° video fun, easy and intuitive. They give you the power to share your best clips with family and friends across social media, directly from your device, with just the push of a button.</p>
				</div>
	        </div>
    	</div>
    	<div class="mobile-desktop-apps">
	    	<div class="image-square left-content app-section">
	            <div class="col-md-6 image no-gutter">
	                <div class="background-image-holder">
	                </div>
	            </div>
	            <div class="col-md-6 col-md-offset-1 content overflow-content">
	            	<div class="col-lg-7 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12 app-content">
						<h2>The 360fly <br> Android and iOS mobile app. </h2>
						<p>Use your mobile device as your camera’s viewfinder, controller and editor—then instantly share immersive 360° content, standard 16:9 edits of 360° footage and stills directly from your mobile device.</p>
		                <ul class="android-ios" >
		                    <li>
		                    	<a href="https://itunes.apple.com/us/app/360fly/id1030962364">
		                    		<img src="<?php echo $skinUrl ?>images/apps/apple.svg" alt="Apple iStore" title="Apple iStore" />
		                    	</a>
		                    </li>
		                    <li>
		                    	<a href="https://play.google.com/store/apps/details?id=com.fly360.fly360">
		                    		<img src="<?php echo $skinUrl ?>images/apps/google.svg" alt="Google Play Store" title="Google Play Store" />
	                    		</a>
	                		</li>
		                </ul>
					</div>
	            </div>
	        </div>
	        <div class="image-square right-content app-section">
	            <div class="col-md-6 image img-right">
	                <div class="background-image-holder">
	                </div>
	            </div>
	            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 content overflow-content">
	                <div class="col-lg-7 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12 app-content">
	            		<h2>Discover the 360fly Director desktop app.</h2>
						<p>The 360fly Director desktop app has everything you need to edit, effect, organize and view your entire library of immersive, interactive 360° video on your personal computer.</p>
			            <ul class="download-section">
			                <li style="padding-bottom: 0px;">
			                	<a class="btn btn-custom" id="macosx" href="https://s3.amazonaws.com/360fly-media-assets/director-app/360fly-director-162.dmg">Download Mac OS X</a>
		                	</li>
			                <li>
			                	<a class="btn btn-custom" id="windows" href="https://s3.amazonaws.com/360fly-media-assets/director-app/360fly-director-setup-162.exe">Download Windows
								</a>
		                	</li>
			            </ul>
	        		</div>
	            </div>
	        </div>
		</div>
    	<span class="clear"></span>
	    <div class="full-width" id="easy-control">
	        <div class="container wrapper-width">
	            <div class="col-lg-4 col-md-6 col-sm-12">
	                <h2>360° control comes easy.</h2>
					<p>Use the 360fly mobile app as your camera’s viewfinder and controller. You can also record directly from your camera using its OnePush button during those rare times you don’t have your phone.</p>
	            </div>
	        </div>
	    </div>
	    <div class="full-width" id="youtube-section">
	        <div class="container wrapper-width">
	            <div class="col-lg-8 col-md-12 col-sm-12">
	                <img src="<?php echo $skinUrl ?>images/apps/desktop-youtube.jpg" alt="Youtube & Facebook Your Best" title="Youtube & Facebook Your Best" class="img-responsive">
	            </div>
	            <div class="col-lg-4 col-md-12 col-sm-12">
	                <h2>YouTube &amp; Facebook<br>	your best.</h2>
					<p>The 360fly Director and mobile&nbsp;apps now give&nbsp;you the power to export your best 360° edits directly to YouTube and Facebook.</p>
	            </div>
	        </div>
    	</div>
    	<div class="full-width" id="compatible-section">
	        <div class="container wrapper-width">
	            <div class="col-lg-6 col-md-6 col-sm-6">
	                <h2>Compatible iOS devices</h2>
	                <p>360fly is compatible on iOS devices running iOS 9 or later.</p>
	                <p><b>Supported Devices:</b><br>Fully Compatible:</p>
	                <ul>
	                	<li>iPhone 5s</li>
						<li>iPhone SE</li>
						<li>iPhone 6/6s</li>
						<li>iPhone 6Plus/6sPlus</li>
						<li>iPhone 7,7Plus</li>
						<li>iPad Pro</li>
						<li>iPad Air</li>
						<li>iPad Air 2</li>
						<li>iPad Mini 2</li>
						<li>iPad Mini 3</li>
						<li>iPad Mini 4</li>
	                </ul>
	                <p><b>Partially Compatible</b><br>The following devices are unable to offer full functionality, but they are able to explore videos from the site and have basic camera controls. However, they cannot play or edit videos that are on the camera. The reason for this is due to hardware limitations in the following devices, as 360fly apps require an A7 chipset or later.</p>
	                <ul>
	                	<li>iPhone 4S</li>
	                	<li>iPhone 5</li>
	                	<li>iPhone 5c</li>
	                	<li>iPad (3rd generation)</li>
	                	<li>iPad (4th generation)</li>
	                	<li>iPad Mini</li>
	                </ul>
	            </div>
	            <div class="col-lg-6 col-md-6 col-sm-6">
	                <h2>Compatible Android devices</h2>
	                <p>Our 360fly Android app requires hardware with a 4k compatible display and Android Version 4.4 or later to function.</p>
	                <p>The following devices have all been tested by 360fly engineers:</p>
	                <ul>
	                    <li>HTC: M8, M9, A9</li>
						<li>LG: G3, G4, Flex 2, Nexus 5</li>
						<li>Motorola: Moto X 2nd Gen, Nexus 6, Droid Turbo/2, Moto Z</li>
						<li>Samsung: Galaxy S5, Galaxy S6/Edge, Galaxy S7/Edge, Galaxy Note 4/Edge, Galaxy Note 5, Galaxy Note 7</li>
						<li>Sony: Xperia Z3</li>
						<li>Nexus 6P, Nexus 5X, Pixel</li>
	                </ul>
	                <h2>360fly Director System Requirements</h2>
	                <p>To use our 360fly Director app, we have a few hardware and software requirements that your machine must meet or exceed:</p>
	                <p>Supported Operating Systems - Windows 7* and above, Mac OS X 10.8 and above<br>
	                <small>*64-bit OS required for 4K</small><br>
	                <small>*Microsoft Surface not supported at this time.</small></p>
	                <p>Check out our support page <a href="https://support.360fly.com/hc/en-us/articles/216573008">here</a> for more details</p>
	            </div>
	        </div>
		</div>
	</div>
