<?php
    $baseUrl = $this->getBaseUrl();
    $mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
    $skinUrl = $this->getSkinUrl();
?>

<div class="pre-footer">
    <div class="container wrapper-width">
        <div class="col-sm-6 col-lg-6">
            <h2>THE APPS THAT <span class="line-break">POWER IT ALL.</span></h2>
            <h3>360fly mobile and desktop Director apps.</h3>
            <p>The 360fly mobile app turns your smartphone into your camera's viewfinder and editing suite and gives you the power to share 360&deg; and standard video directly from your iOS or Android device to social media. </p>
            <p>With many of the same innovative tools as the 360fly mobile app, the desktop Director lets you use the power of your home computer to edit, add effects to, and share your 360&deg; videos.</p>
            <a href="<?php echo $baseUrl;?>apps" class="btn btn-custom">LEARN MORE </a>
        </div>
        <div class="col-sm-6 col-lg-6 app-img">
            <img alt="THE APPS THAT POWER IT ALL" src="<?php echo $skinUrl?>images/phone-desktop-app.png" alt="The App that power it all" title="The App that power it all" id="apps-img">
        </div>
    </div>
</div>
