<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>


<div class="container-fluid row cms-australia">
	<div class="">
		<div class="video-container">
			<div class="video-overlay abs">
			  <div class="au-r1-container abs text-center wrapper-width">
			  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
				<!--<div class="col-md-8 col-lg-8 col-sm-10 col-xs-10 col-md-offset-2 col-lg-offset-2 col-sm-offset-1 col-xs-offset-1">-->
					<h1><b>One camera. One lens.</b><br>Full 360&deg; video.</h1>
					<p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
					<!--<p class="medium-10 small-12 text-center columns">-->
						Welcome to the official 360fly store. Here you'll find everything you need to capture and share your life in immersive, interactive 360&deg; video.
					</p>
				  <div class="cta-buttons text-center">
					  <a href="<?php echo $baseUrl;?>cameras" class="btn btn-shop">Buy Now</a>
					  <a href="#" class="btn-custom btn">Watch Videos</a>
				  </div>
				</div>
			  </div>
			</div>
			<video class="video-bg" autoplay="" muted="" loop="">
				<source src="https://s3.amazonaws.com/360fly-media-assets/eComm_Full_Movie_Encoded_2Bit.mp4" type="video/mp4">
			</video>
		</div>
	</div>
	<div class="">
		<div class="row product-block">
          <div class="au-r2-container text-center container">
				<div class="col-lg-6 col-md-6">
					<div class="col-lg-12 col-md-12">
						<h3>The Camera</h3>
						<p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 center no-padding">Get your 360fly now and miss nothing in the future.</p>

						<img class="product-img fly-camera img-responsive" src="https://d3a58tk6tptbgs.cloudfront.net/static/public/img/homepage_au/camera_full.462b76ed3148.png" alt="360 Fly Camera" title="360 Fly Camera" />

						<a href="<?php echo $baseUrl;?>cameras" class="btn btn-custom">Buy Now</a>
					</div>
				</div>

				<div class="col-lg-6 col-md-6">
					<div class="col-lg-12 col-md-12">
						<h3>The Accessories</h3>
						<p class="col-lg-12 col-md-12 col-sm-12 col-xs-12 center no-padding">Wear it, mount it or put it on a tripod - 360fly fits seamlessly into your active lifestyle.</p>

						<img class="product-img mounts-img" src="https://d3a58tk6tptbgs.cloudfront.net/static/public/img/homepage_au/mount_cluster.cd3534ab10ec.png" alt="360 Fly Accessories" title="360 Fly Accessories" />

						<a href="<?php echo $baseUrl;?>accessories" class="btn btn-custom accessories-btn">Shop Accessories</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="au-r3-container">
		<div class="social-connect">
			<div class="container wrapper-width">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-gutter">
					<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 follow">
						<p class="left follow">Follow Us</p>
						<div class="social-icons">
							<a href="https://instagram.com/360flyanz"><span class="icon-instagram-jul15 social-links"></span></a>
							<a href="https://www.facebook.com/360flyAUNZ"><span class="icon-facebook-jul15 social-links"></span></a>
							<a href="https://twitter.com/360fly_aunz"><span class="icon-twitter-jul15 social-links"></span></a>
							<a href="http://blog.360fly.com/"><span class="icon-tumblr-jul15 social-links"></span></a>
							<a href="https://www.youtube.com/channel/UCBNph_5dIKPQFS3IsIVXJfQ"><span class="icon-youtube-jul15 social-links"></span></a>
						</div>
					</div>
					<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 update">
						<p class="left getUpdates">Get Updates</p>
						<div class="signUp">
							<form action="https://360fly.us3.list-manage.com/subscribe/post?u=834d6982a45baceab74d738d8&amp;id=983c16bcb9" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" novalidate="">
								<input value="" name="EMAIL" class="required email mailSignUp" id="mce-EMAIL" type="email" placeholder="email@address.com">
								<button type="submit" class="btn btn-grey">Sign Up</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- <div class="">
		<div class="row social-connect">
			<div class="au-r3-container wrapper-width">
				<div id="social-bar" class="col-md-12 col-sm-12 col-xs-12 col-sm-12 no-gutter">
					<div class="social-left col-xs-12 col-sm-12 col-md-5 col-lg-5 no-gutter">
						<p class="left follow">Follow Us</p>
						<div class="social-icons">
							<a href="https://instagram.com/360flyanz"><span class="icon-instagram-jul15 social-links"></span></a>
							<a href="https://www.facebook.com/360flyAUNZ"><span class="icon-facebook-jul15 social-links"></span></a>
							<a href="https://twitter.com/360fly_aunz"><span class="icon-twitter-jul15 social-links"></span></a>
							<a href="http://blog.360fly.com/"><span class="icon-tumblr-jul15 social-links"></span></a>
							<a href="https://www.youtube.com/channel/UCBNph_5dIKPQFS3IsIVXJfQ"><span class="icon-youtube-jul15 social-links"></span></a>            
						</div>
					</div>
					<div class="social-right col-xs-12 col-sm-12 col-md-7 col-lg-7 no-gutter">
						<p class="left getUpdates">Get Updates</p>
						<div class="signUp">

							<form action="https://360fly.us3.list-manage.com/subscribe/post?u=834d6982a45baceab74d738d8&amp;id=983c16bcb9" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" novalidate="">
								<input value="" name="EMAIL" class="required email mailSignUp" id="mce-EMAIL" type="email" placeholder="email@address.com">
								<button type="submit" class="btn btn-grey">
								Sign Up
								</button>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div> -->
	<div class="">
		<div class="au-r4-container">
			<div class="au-intro">
				<div class="container no-gutter">
					<div class="col-lg-5 col-md-6 col-sm-12 col-xs-12">
						<h3>Get the 360fly that's right for you.</h3>
						<p>We've made it easy to find the best 360fly for your lifestyle. If you're looking for 360° HD video in a rugged, waterproof package, the 360fly HD is the one.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="">
		<div class="au-r5-container">
			<div class="editing-sharing">
				<div class="col-lg-8 col-lg-offset-2 col-md-12 col-sm-12 col-xs-12 text-center">
					<h3>Easy editing meets easier sharing.</h3>
					<p>The 360fly app gives you the power to instantly <b>shoot</b> videos, <b>share</b> edits to social media and <b>swipe</b>, explore and interact with your favorite memories — all directly from your mobile device.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="clear">
		<div class="au-r6-container">
			<div class="mobile-desktop-apps">
				<div class="image-square left-content app-section">
					<div class="col-md-6 image no-gutter">
						<div class="background-image-holder">
						</div>
					</div>
					<div class="col-md-6 col-md-offset-1 content overflow-content">
						<div class="app-content">
							<h3>360fly mobile app.</h3>
							<p>The 360fly mobile app not only turns your smartphone into your camera's remote control. It gives you the power to edit videos — including adding filters, music and slow- or fast-motion — then share to social media with the push of a button.</p>
							<a href="https://itunes.apple.com/us/app/360fly/id1030962364">
								<img src="<?php echo $skinUrl ?>images/apps/apple.svg" alt="Apple iStore" title="Apple iStore" class="apps-button" />
							</a>
							<a href="https://play.google.com/store/apps/details?id=com.fly360.fly360">
								<img src="<?php echo $skinUrl ?>images/apps/google.svg" alt="Google Play Store" title="Google Play Store" class="apps-button" />
							</a>
						</div>
					</div>
				</div>
				<div class="image-square right-content app-section">
					<div class="col-md-6 image img-right">
						<div class="background-image-holder">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 content overflow-content">
						<div class="app-content plr15">
							<h3>360fly desktop Director.</h3>
							<p>Use the 360fly desktop Director on your PC or Mac to create and manage your 360fly film library, merge your favorite clips together and use all the same editing features found in the 360fly mobile app.</p>
							<ul class="download-section">
								<li style="padding-bottom: 0px;">
									<a class="btn btn-primary btn-custom" id="macosx" href="https://s3.amazonaws.com/360fly-media-assets/director-app/360fly-director-160.dmg">Download MacOS X</a>
								</li>
								<li>
									<a class="btn btn-primary btn-custom" id="windows" href="https://s3.amazonaws.com/360fly-media-assets/director-app/360fly-director-setup-161.exe">Download Windows</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div> 


