<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

?>

<div class="container-fluid row m0p0 graybg">
    <div class="b2bContainer wrapper-width row">
        <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
            <h2>B2B Portal Login</h2>
            <p>360fly isn't just a camera, it's a device designed to capture what happened as if you were there.</p>
            <p>To register to receive information about becoming a dealer, <a href="https://www.voxxdealers.com/ERP2Web/e2wNewUserRegistration.aspx">click here</a>.</p>
        </div>
        <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
            <div class="voxx">
                <iframe scrolling="no" src="https://www.voxxdealers.com/ERP2Web/" class="iframe-block">
                </iframe>
            </div>
        </div>
    </div>
</div>
