<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>
<div class="community-inner cannondale" id="athlete-marketing">
	<div class="cannondale-container" id="">
		<div class="container wrapper-width">
			<div class="covertext text-contain ">
				<h1 class="extreme-headline">
					<b>Cannondale 360FLY</b>
				</h1>
                <h2 class="extreme-headline">Mountain Biking </h2>
			</div>
		</div>
	</div>
	<div class="bio-container">
		<div class="bio-left greybg ">
			<div class="bio-left-child-1">
			<h3>Cannondale 360FLY's Bio</h3>
			<p>Cannondale 360fly, Powered by SUGOI brings together three innovative brands with trailblazing technology to fuel North America’s fastest domestic mountain bikers.
			</p>
          	<p>Show casing a 4 person team for 2016, the Cannondale/360fly team will have riders racing almost every discipline of mountain biking throughout the season.
          	</p>
          	<p>Canadian National Champion and 2012 London Olympian Raphael Gagne captains the team as he bids for another Olympic birth in 2016. The team also includes legend and 2X Olympian Tinker Juarez, who will focus on long and ultra distance races. Female podium contender Evelyn Dong, U23 National Champion Keegan Swenson, and 3X Park City Point to Point race winner Alex Grant.\
          	</p>
          	<p>Throughout the season, riders will be capturing their training, racing and travel adventures in immersive 360 degree footage.
          	</p>
			</div>
			<div class="bio-left-child-2">
			</div>
		</div>
		<div class="bio-right greenbg">
			<div class="bio-right-content">
			</div>
		</div>
	</div>
</div>
<div class="athlete-social">
	<div class="athlete-wrapper">
		<div class="col-sm-12 col-md-12 col-lg-12 icons-wrapper">
	        <div class="athlete-social-name"><p class="pull-left follow">Follow Cannondale 360FLY</p></div>
	      	<div class="pull-left icons">
		        <a href="https://twitter.com/cannondalePro" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
		        <a href="https://www.facebook.com/CannondaleProCycling/" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
		        <a href="https://www.instagram.com/cannondalepro/" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
	        </div>
      	</div>
	</div>
</div>

