<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
?>

<div class="container-fluid community-container" id="featured-profile">
	<!--banner -->
	<div class="row">	
		<a href="<?php echo $baseUrl;?>chad-reed">
			<div class="community-banner" id="top-banner">
				<div class="container wrapper-width">
					<!-- <div class="row ">
						<div class="col-md-12 col-lg-12"> -->
							<div class="community-info">
								<h2>Chad Reed</h2>
								<h3>MotoCross</h3>
							</div>
						<!-- </div>
					</div> -->
				</div>
			</div>
		</a>
	</div>
	<div class="row community-bg ">
		<div class="wrapper-width">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 inner-wrapper community-content-left">
				<a href="<?php echo $baseUrl;?>jorge-lorenzo">
					<div class="community-banner small " id="community-lorenzo">
	       			 	<div class="community-info gradient">
		          			<h2>Jorge Lorenzo</h2>
		          			<h3>MOTOGP</h3>
	        			</div>
      				</div>
      			</a>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 inner-wrapper community-content-right">
				<a href="<?php echo $baseUrl;?>sunny-garcia">
					<div class="community-banner small" id="community-garcia">
				        <div class="community-info gradient">
				          <h2>Sunny Garcia</h2>
				          <h3>Surfer</h3>
				        </div>
		      		</div>
	      		</a>
			</div>

		</div>
	</div>	
	<div class="row">
		<div class="wrapper-width">
		<iframe width="1000"  height="500" src="https://www.youtube.com/embed/m_MWFh3o1bA?list=PL8R9h4tp3m-NHVBQ1HqpAIgvV2n-F2A-Y" frameborder="0" allowfullscreen></iframe>
		</div>
	</div>
	<div class="row community-bg ">
		<div class="wrapper-width">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 inner-wrapper community-content-left">
				<a href="<?php echo $baseUrl;?>matt-cordova">
					<div class="community-banner small " id="community-cordova">
	       			 	<div class="community-info gradient">
		          			<h2>Matt Cordova</h2>
		          			<h3>BMX</h3>
	        			</div>
      				</div>
      			</a>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 inner-wrapper community-content-right">
				<a href="<?php echo $baseUrl;?>terry-adams">
					<div class="community-banner small" id="community-adams">
				        <div class="community-info gradient">
				          <h2>Terry Adams</h2>
				          <h3>BMX Flatland</h3>
				        </div>
		      		</div>
	      		</a>
			</div>

		</div>
	</div>
	<div class="row">
	  <div class="wrapper-width">
	    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 inner-wrapper">
	      <a href="<?php echo $baseUrl;?>pro-circuit"><div class="community-banner" id="community-kx">
	        <div class="community-info gradient">
	          <h2>Pro Circuit KAW</h2>
	          <h3>Motocross</h3>
	        </div>
	      </div></a>
	    </div>
	  </div>
	</div>
	<div class="row community ">
		<div class="wrapper-width video-wrapper">
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 community-content-left">
				<iframe width="100%" height="300" src="https://www.youtube.com/embed/qcO7VDhqjso?list=PL8R9h4tp3m-NHVBQ1HqpAIgvV2n-F2A-Y" frameborder="0" allowfullscreen></iframe>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 community-content-right">
				<iframe width="100%" height="300" src="https://www.youtube.com/embed/Mvj7B9RzlEA?list=PL8R9h4tp3m-NHVBQ1HqpAIgvV2n-F2A-Y" frameborder="0" allowfullscreen></iframe>
			</div>

		</div>
	</div>
	<div class="row last-community-banner">
	  <div class="wrapper-width">
	    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 no-gutter">
	      <a href="<?php echo $baseUrl;?>cannondale"><div class="community-banner" id="community-canondale">
	        <div class="community-info gradient">
	          <h2>Cannondale</h2>
	          <h3>Mountain Biking</h3>
	        </div>
	      </div></a>
	    </div>
	  </div>
	</div>	
</div>