<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>
<div class="base-content clearfix director-page">
	<div class="full-width director-banner" >
        <div class="container wrapper-width no-gutter director-wrap">
        	<div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 no-gutter">
                <h1>Discover the 360fly Director desktop app.</h1>
				<p>The 360fly Director desktop app has everything you need to edit, effect, organize and view your entire library of immersive, interactive 360° video on your personal computer.</p>
				<ul class="download-section">
		                <li style="padding-bottom: 0px;">
		                	<a class="btn btn-primary btn-custom director-btn-padding" id="macosx" href="https://s3.amazonaws.com/360fly-media-assets/director-app/360fly-director-160.dmg">Download MacOS X</a>
	                	</li>
		                <li>
		                	<a class="btn btn-primary btn-custom director-btn-padding" id="windows" href="https://s3.amazonaws.com/360fly-media-assets/director-app/360fly-director-setup-161.exe">Download Windows</a>
	                	</li>
		        </ul>
        	</div>
        </div>
    </div>
</div>
<div class="full-width" id="miss-share">
    <div class="container wrapper-width">
    	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 no-gutter">
            <h2>Miss nothing, share everything.</h2>
			<p>The 360fly apps make capturing, editing and sharing 360° video fun, easy and intuitive. They give you the power to share your best clips with family and friends across social media, directly from your device, with just the push of a button.</p>
		</div>
    </div>
</div>
<div class="full-width" id="youtube-section">
    <div class="container wrapper-width">
        <div class="col-lg-8 col-md-12 col-sm-12">
            <img src="<?php echo $skinUrl ?>images/apps/desktop-youtube.jpg" alt="Youtube & Facebook Your Best" title="Youtube & Facebook Your Best" class="img-responsive">
        </div>
        <div class="col-lg-4 col-md-12 col-sm-12">
            <h2>YouTube &amp; Facebook<br>	your best.</h2>
			<p>The 360fly Director and mobile&nbsp;apps now give&nbsp;you the power to export your best 360° edits directly to YouTube and Facebook.</p>
        </div>
    </div>
</div>
<div class="full-width" id="compatible-section">
        <div class="container wrapper-width">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <h2>360fly Director System Requirements</h2>
                <p>To use our 360fly Director app, we have a few hardware and software requirements that your machine must meet or exceed:</p>
                <p>Supported Operating Systems - Windows 7* and above, Mac OS X 10.8 and above<br>
                <small>*64-bit OS required for 4K</small><br>
                <small>*Microsoft Surface not supported at this time.</small></p>
                <p>Check out our support page <a href="https://support.360fly.com/hc/en-us/articles/216573008">here</a> for more details</p>
            </div>
        </div>
</div>
