<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
$isBlackFriday = count(Mage::getModel('core/variable')->loadByCode('is_production')->getValue('plain')) > 0 ? (int) Mage::getModel('core/variable')->loadByCode('is_black_friday')->getValue('plain') : 0;
$isCyberMonday = count(Mage::getModel('core/variable')->loadByCode('is_production')->getValue('plain')) > 0 ? (int) Mage::getModel('core/variable')->loadByCode('is_cyber_monday')->getValue('plain') : 0;

?>

<div class="slider-wrapper">
	<div id="layerslider" style="width: 100%; height: 720px;">
		<div class="ls-slide" data-ls="transition2d: 5; timeshift: -1000;">
			<div class="ls-l ls-background" style="left: 50%; top: 50%; height: 100%; width: 120%; background: url(<?php echo $skinUrl;?>images/layerslider/slide-01/bg.jpg) no-repeat center; background-size: cover;" data-ls="parallaxlevel: 10;">
			</div>
		<!-- text layers -->
			<h2 class="ls-l flyslim" data-ls="offsetxin: left; offsetxout: right;" style="top: 40%; left: 50%; white-space: nowrap;color:white;font-size: 88px;">ONE LENS. NO SEAMS.</h2>
			<h2 class="ls-l bold" data-ls="offsetxin: right; offsetxout: left;" style="top: 50%; left: 50%; white-space: nowrap;color:white; white-space: nowrap;font-size: 88px;font-weight: bold;">LIMITLESS POSSIBILITIES</h2>
		<!-- parallax layers -->
			<img src="<?php echo $skinUrl;?>images/layerslider/slide-01/camera.png" alt="360 Camera" title="360 Camera" data-ls="offsetyin: bottom; offsetyout: bottom;" style="left: 50%; top: 78%;" class="ls-l" alt="" />
		</div>
		<div class="ls-slide" data-ls="transition2d: 5; timeshift: -1000;">
			<div class="ls-l ls-background" style="left: 50%; top: 50%; height: 100%; width: 110%; background: url(<?php echo $skinUrl;?>images/layerslider/slide-02/bg.jpg) no-repeat center; background-size: cover;" data-ls="parallaxlevel: -5;">

			</div>
			 <!-- parallax layers -->
			<img src="<?php echo $skinUrl;?>images/layerslider/slide-02/camera-bottom.png" alt="360 Camera" title="360 Camera" data-ls="offsetyin: top; offsetyout: top;" style="left: 70%; top: 38%;" class="ls-l" alt="" />
			<!-- text layers -->
			<h2 class="ls-l large-4k" data-ls="offsetyin: top; offsetyout: bottom;" style="top: 43%; left: 50%; white-space: nowrap;color:white;font-size: 192px; line-height: 192px;font-weight: bold;">4K<span style="font-size:40%;vertical-align: top;">IS</span>HERE.</h2>
			<h2 class="ls-l small-4k flyslim" data-ls="offsetyin: bottom; offsetyout: top;" style="top: 59%; left: 50%; white-space: nowrap;color:white;font-size:41px;line-height:39px;">NEVER BEFORE HAS ONE BALL<br/>CHANGED THE GAME SO MUCH.</h2>
			<img src="<?php echo $skinUrl;?>images/layerslider/slide-02/camera.png" alt="360 Camera" title="360 Camera" data-ls="offsetyin: bottom; offsetyout: bottom;" style="left: 10%; top: 96%;" class="ls-l" alt="" />
		</div>
		<div class="ls-slide app-slide" data-ls="transition2d: 5; timeshift: -1000;">
			<div class="i">
			<div class="ls-l" data-ls="offsetxin: 0; offsetyin: 0;" style="left: 50%; top: 50%; height: 100%; width: 100%; background: url(<?php echo $skinUrl;?>images/layerslider/slide-03/bg.jpg) no-repeat center; background-size: cover;">

			</div>
			<!-- parallax layers -->
			<img src="<?php echo $skinUrl;?>images/layerslider/slide-03/devices.png" data-ls="offsetxin: right; fadein: true; scalexin: 800; scaleyin: 800;" style="left: 430px" class="ls-l" alt="iOs Android Windows Devices" title="iOs Android Windows Devices" />
			<!-- text layers -->
			<h2 class="ls-l" data-ls="offsetyin: bottom; offsetyout: bottom;" style="top: 28%; left: 0px; width: 400px; white-space: nowrap;font-size: 73px;line-height: 71px;color:#78BE20;padding: 0px 10px;">LIVE VIDEO<br> THAT'S<br> TRULY ALIVE.</h2>
			<p class="ls-l" data-ls="offsetyin: bottom; delayin: 200; offsetyout: bottom;" style="top: 57%; left: 0px; width: 400px;font-size:30px;line-height: 33px;color:#666666;padding: 0px 10px;">With your 360fly camera, the free Livit mobile app and a smartphone, you have the power to live stream interactive 360&#176; video to family and friends around the globe.</p>
			<div class="ls-l hidden-xs mobile_img app-links" data-ls="offsetyin: bottom; delayin: 400; offsetyout: bottom;" style="top: 83%;">
				<a href="https://itunes.apple.com/us/app/livit-live-video-and-vr/id896514048?mt=8" class="apple-btn-link" target="_blank">
					<img src="<?php echo $skinUrl;?>images/layerslider/slide-03/ios-app-btn.png" class="img-responsive" style="width: 133px;" alt="App Store" title="App Store!" />
				</a>
				<a href="https://play.google.com/store/apps/details?id=com.livitnow.livit&hl=en" class="google-btn-link" target="_blank">
					<img src="<?php echo $skinUrl;?>images/layerslider/slide-03/android-app-btn.png" class="img-responsive" alt="Google play" title="Google Play!" />
				</a>
			</div>
			<img class="ls-l hidden-lg hidden-md hidden-sm" data-ls="offsetyin: bottom; delayin: 400; offsetyout: bottom;" style="top: 83%; left: 10px;" src="<?php echo $skinUrl;?>images/layerslider/slide-03/ios-app-btn.png" class="img-responsive" alt="App Store"  title="App Store"/>
			<img class="ls-l hidden-lg hidden-md hidden-sm" data-ls="offsetyin: bottom; delayin: 400; offsetyout: bottom;;" style="top: 83%; left: 153px;" src="<?php echo $skinUrl;?>images/layerslider/slide-03/android-app-btn.png" class="img-responsive" alt="Google Play" titler="Google Play" />
		</div>
	</div>
</div>
</div>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/blocks/video-block-a.phtml')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/blocks/video-edge-error.phtml')->toHtml(); ?>
<div class="video_background globe">
  <div class="container wrapper-width no-gutter">
		<div class="col-sm-12 col-md-7 col-lg-7 text-center" id="globe-wrap">
			<img src="<?php echo $skinUrl?>images/parallax/fov/fov__imagesequence_54.png" class="img-responsive margin-center" alt="360_rotate image" title="360_rotate image">
		</div>
		<div class="col-md-5 col-lg-5 text-right hidden-sm hidden-xs" >
		  <div class="valign">
			  <h2 >MISS NOTHING.</h2>
			  <h3>Full 360&deg; horizontal x 240&deg; vertical field of view.</h3>
			  <p>Life doesn't just come at you straight on. Which is why the 360fly 4K and 360fly HD put you in the center of the action while capturing the entire world all around you.</p>
				<a href="<?php echo $baseUrl;?>shop" class="btn btn-custom">LEARN MORE </a>
		  </div>
		</div>
		<div class="col-md-5 col-lg-5 text-left visible-sm visible-xs" >
		  <div class="valign">
			  <h2 >MISS NOTHING.</h2>
			  <h3>Full 360&deg; horizontal x 240&deg; vertical field of view.</h3>
			  <p>Life doesn't just come at you straight on. Which is why the 360fly 4K and 360fly HD put you in the center of the action while capturing the entire world all around you.</p>
				<a href="<?php echo $baseUrl;?>shop" class="btn btn-custom">LEARN MORE </a>
		  </div>
		</div>
	</div>
</div>
<div class="pov row">
	<div class="container wrapper-width">
		<div class="col-lg-7 col-md-7 col-sm-7 col-xs-12 text-left pov-para" >
			<h2 >CAPTURE EVERY POV. PLUS ONE.</h2>
			<h3>360fly 4K First-Person POV.</h3>
			<p>Go from recording in 360&deg; video to standard 16:9 format and back with ease. With the 360fly 4K's First-Person mode activated, just orient or mount your camera with its lens facing forward and OnePush button centered/facing up and use your 360fly like traditional point-and-shoot action cameras.</p>
			<a href="<?php echo $baseUrl;?>shop" class="btn btn-custom">LEARN MORE </a>
		</div>
		<div class="col-lg-5 col-md-5 col-sm-5 col-xs-12">
			<div id="pov-wrap" class="hidden-xs">
				<img src="<?php echo $skinUrl;?>images/parallax/pov/pov__imagesequence_01.png" />
			</div>
			<div id="pov-mobile" class="visible-xs">
				<img src="<?php echo $skinUrl;?>images/parallax/pov/pov_mobile.png" />
			</div>
      	</div>
	</div>
</div>
<div class="dirt ">
	<div class="video_img2">
		<div class="container wrapper-width">
			<div class="col-sm-12 col-md-6">
				<h2 class="large">
					DUSTPROOF<br>AND<br>SHOCKPROOF.
				</h2>
				 <a href="<?php echo $baseUrl;?>shop" class="btn btn-custom">LEARN MORE </a>
				<div class="dirt-wrap">
					<div class="back">
						<img src="<?php echo $skinUrl; ?>images/elements/dirt/dirt-back.png" alt="Dirt Back" title="Dirt Back">
					</div>
					<div id="dirt-back-spray-1" >
						<img src="<?php echo $skinUrl; ?>images/elements/dirt/back-spray-1.png" alt="Back Spary Small" title="Back Spary Small">
					</div>
					<div id="dirt-back-spray-2">
						<img src="<?php echo $skinUrl; ?>images/elements/dirt/back-spray-2.png" alt="Back Spray Large" title="Back Spray Large">
					</div>
					<div id="dirt-camera" class="camera" style="top: -1100px;" >
						<img src="<?php echo $skinUrl; ?>images/elements/dirt/camera.png" alt="360 Camera" title="360 Camera">
					</div>
					<div id="dirt-spray-front" >
						<img src="<?php echo $skinUrl; ?>images/elements/dirt/front-spray.png" alt="Front Spray Light" title="Front Spray Light">
					</div>
					<div class="front">
						<img src="<?php echo $skinUrl; ?>images/elements/dirt/dirt-front.png" alt="Dirt Front Heavy" title="Dirt Front Heavy">
					</div>
				</div>
			</div>
		</div>
	</div>

</div>
<div class=" product-promotion">
	<div class="container">
		<h2>GO ANYWHERE.
			MOUNT EVERYWHERE.
		</h2>
		<div class="col-sm-10 col-sm-offset-1 product-slider ">
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>action-cam-adapter-hd"><img src="<?php echo $skinUrl; ?>images/accessories/aca-hd.jpg" alt="Action Cam Mount (HD)" title="Action Cam Mount (HD)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>action-cam-adapter-hd" title="Action Cam Mount (HD)">Action Cam Mount (HD)</a></p>

					  <a href="<?php echo $baseUrl;?>action-cam-adapter-hd" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>handle-bar-mount-hd"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Handlebar_mount.jpg" alt="Handlebar Mount (HD)" title="Handlebar Mount (HD)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>handle-bar-mount-hd" title="Handlebar Mount (HD)">Handlebar Mount (HD)</a></p>

					  <a href="<?php echo $baseUrl;?>handle-bar-mount-hd" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>suction-mount-hd"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Suction_Mount.jpg" alt="Suction Mount (HD)" title="Suction Mount (HD)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>suction-mount-hd" title="Suction Mount (HD)">Suction Mount (HD)</a></p>

					  <a href="<?php echo $baseUrl;?>suction-mount-hd" class="btn  btn-custom">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>tripod-adapter-hd"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Tripod_Adapter.jpg" alt="Tripod Adapter (HD)" title="Tripod Adapter (HD)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>tripod-adapter-hd" title="Tripod Adapter (HD)">Tripod Adapter (HD)</a></p>

					  <a href="<?php echo $baseUrl;?>tripod-adapter-hd" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vented-helmet-mount-hd"><img src="<?php echo $skinUrl; ?>images/accessories/HD_Helmet_Mount.jpg" alt="Vented Helmet Mount (HD)" title="Vented Helmet Mount (HD)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vented-helmet-mount-hd" title="Vented Helmet Mount (HD)">Vented Helmet Mount (HD)</a></p>

					  <a href="<?php echo $baseUrl;?>vented-helmet-mount-hd" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vr-headset"><img src="<?php echo $skinUrl; ?>images/accessories/VR_headset.png" alt="VR Headset" title="VR Headset" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vr-headset" title="VR Headset">VR Headset</a></p>

					  <a href="<?php echo $baseUrl;?>vr-headset" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>suction-mount-4k"><img src="<?php echo $skinUrl; ?>images/accessories/suction-mount-4k.jpg" alt="Suction Mount (4K)" title="Suction Mount (4K)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>suction-mount-4k" title="Suction Mount (4K)">Suction Mount (4K)</a></p>

					  <a href="<?php echo $baseUrl;?>suction-mount-4k" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>mount-kit-4k"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Action_Mount.jpg" alt="Mount Kit (4K)" title="Mount Kit (4K)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>mount-kit-4k" title="Mount Kit (4K)">Mount Kit (4K)</a></p>

					  <a href="<?php echo $baseUrl;?>mount-kit-4k" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>vented-helmet-mount-4k"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Helmet_Mount.png" alt="Vented Helmet Mount (4K)" title="Vented Helmet Mount (4K)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>vented-helmet-mount-4k" title="Vented Helmet Mount (4K)">Vented Helmet Mount (4K)</a></p>

					  <a href="<?php echo $baseUrl;?>vented-helmet-mount-4k" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
			<div>
				<article class="product_pod">
				  <a href="<?php echo $baseUrl;?>handle-bar-mount-4k"><img src="<?php echo $skinUrl; ?>images/accessories/4K_Handlebar_Mount.png" alt="Handlebar Mount (4K)" title="Handlebar Mount (4K)" class=""></a>

				   <div class="product_price clearfix">
					  <p class="product-title"><a href="<?php echo $baseUrl;?>handle-bar-mount-4k" title="Handlebar Mount (4K)">Handlebar Mount (4K)</a></p>

					  <a href="<?php echo $baseUrl;?>handle-bar-mount-4k" class="learn_more_small">MORE INFO</a>
				   </div>
				</article>
			</div>
		</div>
	</div>
</div>
<div class="pre-footer">
	<div class="container wrapper-width">
		<div class="col-sm-6 col-lg-6">
			<h2>THE APPS THAT <span class="line-break">POWER IT ALL.</span></h2>
			<h3>360fly mobile and desktop Director apps.</h3>
			<p>The 360fly mobile app turns your smartphone into your camera's viewfinder and editing suite-and gives you the power to share 360&deg; and standard video directly from your iOS or Android device to social media. With many of the same innovative tools as the 360fly mobile app, the desktop Director lets you use the power of your home computer to edit, add effects to, and share your 360&deg; videos.</p>
				<a href="<?php echo $baseUrl;?>apps" class="btn  btn-custom">LEARN MORE </a>
		</div>
		<div class="col-sm-6 col-lg-6 app-img">
			<img alt="THE APPS THAT POWER IT ALL" src="<?php echo $skinUrl?>images/phone-desktop-app.png" alt="The App that power it all" title="The App that power it all" id="apps-img">
		</div>
	</div>
</div>


<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/pages/videojs.phtml')->toHtml(); ?>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/pages/homejs.phtml')->toHtml(); ?>
