<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>
<div class=" community-inner kalani-david" id="athlete-marketing">
	<div class="kalani-container" id="">
		<div class="container wrapper-width">
			<div class="covertext text-contain ">
				<h1 class="extreme-headline">
					<b>Kalani David</b>
				</h1>
                <h2 class="extreme-headline">Surf/Skate</h2>
				<p class="col-sm-12 col-md-5">“I’m stoked to be a part of 360fly. Like surfing and skating, I am always trying to be on the leading edge and progressive and 360fly is the leading edge of camera technology!”</p>
			</div>
		</div>
	</div>
	<div class="bio-container">
		<div class="bio-left greybg ">
			<div class="bio-left-child-1">
	          <h3>Kalani's Bio</h3>
	            <div class="stats-box">
					<span class="stats pull-left">Age:</span><span class="pull-left ">17</span>
					<span class="clear"></span>
					<span class="stats pull-left">Location:</span><span class="pull-left ">Haleiwa, Hawaii</span>
					<span class="clear"></span>
					<span class="stats pull-left">Sport:</span><span class="pull-left ">Surfing and skating</span>
					<span class="clear"></span>
	            </div>
				<p>I was born in Costa Rica and came to Hawaii when I was 4 years old. I was very lucky I had parents who were open to so many cool things! Surfing, skating, racing motorcycles, and playing drums every day, for the next 5 years was pretty much all I did.
				</p>&nbsp;
				<p>I won the Mr. Hawaiian Tropic title, when I was 9 years old, and rode in parades through Waikiki. I've surfed and skated in a couple big screen movies during those early years too. Hawaii was such an amazing place, with so many opportunities for someone who loved surfing and skating! I grew up surfing in the Hawaiian Amateur Surfing Associations, and spent the summer skating parks up and down the California coast. I really enjoyed competing in both, surfing and skateboarding events.
				</p>&nbsp;
				<p>I worked really hard to qualify for the-WQS 6 Star's, and the Pro Bowl skate tour at 14 years old. I skated in X-Games and surfed in the U S Open on the same day. I took time off traveling and events to finish High School. I was homeschooled for 6 years, and going to an actual High School was very demanding. The future starts here!
				</p>
			</div>
			<div class="bio-left-child-2">
				<h3>Q &amp; A</h3>
				<p class="question col-xs-1 col-sm-1 pull-left">Q.</p> 
				<p class="question col-xs-11 col-sm-11 pull-left ">Biggest  accomplishment?</p>
				<p class="col-xs-1 col-sm-1">A.</p>
				<p class="answer col-xs-11 col-sm-11 ">For so many years it was all about winning. Nowadays, it's about making my family, sponsors, and everyone who has supported me, proud. The best feeling of accomplishment in the world! </p>

				<p class="question col-xs-1 col-sm-1 pull-left">Q.</p>
				<p class="question col-xs-11 col-sm-11 pull-left">Coolest place you've ever been?</p>
				<p class="col-xs-1 col-sm-1">A.</p> 
				<p class="answer col-xs-11 col-sm-11">Take this secret dirt road with jumps in my truck at full throttle! Let's not mention that to my parents.</p>

				<p class="question col-xs-1 col-sm-1 pull-left">Q.</p>
				<p class="question col-xs-11 col-sm-11 pull-left">What is your favorite thing to do?</p>
				<p class="col-xs-1 col-sm-1">A.</p> 
				<p class="answer col-xs-11 col-sm-11">Take this secret dirt road with jumps in my truck at full throttle! Let's not mention that to my parents.</p>

				<p class="question col-xs-1 pull-left">Q.</p>
				<p class=" question col-xs-11 col-sm-11 pull-left">Favorite place to surf and skate?</p>
				<p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">Backdoor for surfing and RVCA Warehouse when I skate.
				</p>

				<p class="question col-xs-1 pull-left">Q.</p>
				<p class=" question col-xs-11 col-sm-11 pull-left">Never leave home without?</p>
				<p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">Sunblock!

				<p class="question col-xs-1 pull-left">Q.</p>
				<p class=" question col-xs-11 col-sm-11 pull-left">What music are you currently listening to?</p>
				<p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">DJ Mix-Old Classic Rock-Rap-Jazz and when I'm on Maui? I listen to country while checking the waves, with the boys.
				</p>

				<p class="question col-xs-1 pull-left">Q.</p>
				<p class=" question col-xs-11 col-sm-11 pull-left">What inspires you?</p>
				<p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">People who are committed to selfless acts of random kindness.
				</p>

				<p class="question col-xs-1 pull-left">Q.</p>
				<p class=" question col-xs-11 col-sm-11 pull-left">Activities you like to do when not competing.</p>
				<p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">I still do a lot every day. My favorite thing to do of course is surf and skate, but I also like to ride dirt bikes and play the drums.
				</p>
			</div>
		</div>
		<div class="bio-right greenbg">
			<div class="">
				<div class="athlete_highlight_text">
					<h4>Career Highlights</h4>
					<div class="bio-right-content">
						<p class="date-highlight">2013</p>
						<p class="indent">World Junior Amateur Champion-Surfing</p>						
						<p class="indent">Third Place - Dew Tour Pro Bowl-Skating</p>
						<p class="indent">Pipeline Pro Jr Champion-Surfing</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2008-13</p>
						<p class="indent">Grom /Jr /Men Open/Explorer -National Surf Champion </p>						
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2012</p>
						<p class="indent">Third Place Bowl A Rama-Skating</p>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</div>
<div class=" athlete-social">
	<div class="athlete-wrapper">
		<div class="col-sm-12 col-md-12 col-lg-6 icons-wrapper">
	        <div class="athlete-social-name"><p class="pull-left follow">Follow Kalani</p></div>
	      	<div class="pull-left icons">
		        <a href="https://twitter.com/kalanidavid" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
		        <a href="https://www.facebook.com/kalanidavid" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
		        <a href="https://instagram.com/kalani_david_/?hl=en" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
	        </div>
      	</div>
	</div>
</div>

