<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>
<div class="led-bkg">
    <div class="container wrapper-width">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 led-desc">
                <h2>Let there be LED light.</h2>
                <p>Get to know the light that lets you know what your 360fly is doing. Here’s a little mnemonic that’ll help you remember two key LED states and their functions:</p>
                <p><i>Blue is booting up or down, red is recording all around.</i></p>
                <p>To experience all your camera’s LED states and vibrations, click each function in the list below.</p>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                <div class="led-camera">
                    <img class="led-cam" src="<?php echo $skinUrl;?>images/led-camera.png" alt="360fly Camera">
                    <svg id="AnimateTriangle" class="triangle" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 21.3 54.2" xml:space="preserve"><polyline class="st0" points="21.3,16 0,0 0,54.2"></polyline></svg>
                </div>
            </div>
            <hr class="led-hr">
        </div>
    </div>
</div>
<div class="">
    <div class="container wrapper-width led">
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 led-states">
            <ul>
                <a id="Powered_Off" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-black.svg"><span>Powered off</span></li>
                </a>
                <a id="Fully_Charged" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-green.svg"><span>Fully Charged</span></li>
                </a>
                <a id="Charging" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-green.svg"><span>Charging</span></li>
                </a>
                <a id="Ready" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-blue.svg"><span>Ready</span></li>
                </a>
                <a id="BootingShutting" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-blue.svg"><span>Booting/Shutting Down</span></li>
                </a>
                <a id="Discovering" href="#">
                    <li><img class="led-light-three" src="<?php echo $skinUrl;?>images/led-rgb.svg"><span>Discovering</span></li>
                </a>
            </ul>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 led-states">
            <ul>
                <a id="Recording" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-red.svg"><span>Recording</span></li>
                </a>
                <a id="Recording_LED_LowM" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-red.svg"><span>Recording (low memory)</span></li>
                </a>
                <a id="Recording_LED_NoM" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-red.svg"><span>Recording (no memory)</span></li>
                </a>
                <a id="Low_Battery" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-pink.svg"><span>Low Battery (&lt;30%)</span></li>
                </a>
                <a id="Firmware_Update" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-yellow.svg"><span>Firmware Update</span></li>
                </a>
                <a id="Factory_Reset" href="#">
                    <li><img class="led-light-two" src="<?php echo $skinUrl;?>images/led-yb.svg"><span>Factory Reset</span></li>
                </a>
            </ul>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 led-states">
            <ul>
                <a id="Warnings_Errors" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-white.svg"><span>Warnings/Errors</span></li>
                </a>
                <a id="Unable_Boot" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-white.svg"><span>Unable to Reboot (error related)</span></li>
                </a>
                <a id="UMS" href="#">
                    <li><img class="led-light" src="<?php echo $skinUrl;?>images/led-yellow.svg"><span>USB Mass Storage</span></li>
                </a>
                <a id="Reformat_Storage" href="#">
                    <li><img class="led-light-two" src="<?php echo $skinUrl;?>images/led-yb.svg"><span>Reformat Storage</span></li>
                </a>
            </ul>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 led-download">
            <a class="btn btn-led" href="https://s3.amazonaws.com/360fly-mage-static-assets/media/wysiwyg/LEDstate_new.15504c3a52b1.pdf">Download LED Reference</a>
        </div>
    </div>
</div>
