<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

?>
<div class="wrapper-width container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <h1>360fly Patents</h1>
        </div>
        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
            <p><b>360fly Virtual Patent Marking Webpage</b></p>
            <p>This website is provided to satisfy the virtual patent marking provisions of various jurisdictions including Section 287 of Title 35 of the United States Code. Patents in the U.S. and elsewhere protect the following 360fly products. This list may not be all-inclusive and one or more patents may protect other 360fly products not listed here. Additional patents may be pending in the U.S. and elsewhere.</p>
        </div>
        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
            <table class="table table-bordered patents-table" cellspacing="1" cellpadding="10" border="1" align="left">
                <thead>
                    <tr class="theadtr">
                        <th>Product</th>
                        <th>Model</th>
                        <th>Protected by one or more of the following US Patents and their non-US counterparts (if any)</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>360fly camera</td>
                        <td>360FLYBLK</td>
                        <td>US8,730,322; US7,058,239; US7,139,440; US8,836,783; D682,904; Patents pending </td>
                    </tr>
                    <tr>
                        <td>360fly mount</td>
                        <td></td>
                        <td>Patents pending</td>
                    </tr>
                    <tr class="trblank">
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td>GOPANO</td>
                        <td>GoPano</td>
                        <td>US7,123,777; US6,856,472; US6,594,448; US8,836,783</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>GoPano Plus</td>
                        <td>US7,123,777; US6,856,472; US6,594,448; US8,836,783</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>GoPano Micro</td>
                        <td>US7,123,777; US6,856,472; US6,594,448; US8,836,783</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>GoPano plus Red Lens Adapter</td>
                        <td>US7,399,095 </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
