<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

?>

<div class="container-fluid press-content press-container">
	<div class="row">
		<div class="col-sm-12 press-img">
			<h1>Press</h1>
		</div>
		<div class="row" id="listings">
			<div class="col-xs-10 list-content no-gutter">
				<p><p>Interested in writing about us? <a href="/contact/">Click here</a> to contact us for press inquiries. </p></p>
			</div>
		</div>
		<div class="row" id="listings">
			<div class="col-xs-10 list-content pull-left">
				<h2>"Street View your life" - CNET</h2>
				<h3>This year you won't need a professional camera rig to grab an immersive 360-degree view of your surroundings so you can create and share your own VR photos and video.</h3>
				<p></p>
				<p>February 19, 2016</p>
				<p class="snippet-text">The people behind the 360fly used more than a decade of experience developing panoramic solutions for military and aviation to make this tough little single-lens action cam that's water-, dust- and shock-resistant. By using a single lens, you avoid having seams in your video created by stitching together shots from two or more cameras. </p>
				<a href="http://www.cnet.com/news/360-degree-cameras-2016/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"THE WORLD'S ONLY SINGLE-LENS 360 CAM IS ABOUT TO GO 4K" - Maxim</h2>
				<h3>Capture everything in ultra-high def.</h3>
				<p></p>
				<p>February 16, 2016</p>
				<p class="snippet-text">You're familiar with stitching—not just the physical kind you get at the emergency room after each epic adventure, but also the way your camera uses special software to link together panoramic pics. To avoid that awkward stitching, 360fly's camera magically captures everything around you with just a single lens. And in April, they'll be releasing a 4K version.</p>
				<a href="http://www.maxim.com/gear/360fly-releases-4k-panoramic-camera-2016-02" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"We Tested The Best 360 Degree Cameras Under $1000" - Gizmodo</h2>
				<p>February 9, 2016</p>
				<p class="snippet-text">Shooting 360 degree video, which can be viewed on Youtube, Facebook, or with a VR headset, was once reserved for professionals with a professional budget. Over the last year, we’ve begun seeing a number of manufacturers releasing 360 degree cameras that promise high quality immersive video at a price point that consumers can actually afford.</p>
				<a href="http://gizmodo.com/heres-what-you-can-expect-to-get-from-360-cameras-for-1755798348" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly puts 4K video cams on helmets" - Engadget</h2>
				<h3>Adrenaline junkies, these are for you.</h3>
				<p>January 7, 2016</p>
				<p class="snippet-text">If you don't want to MacGyver an action helmet, you might like 360fly's new products. The company has launched not only a 360-degree action cam that can take 4K videos at CES, but also four Bell- and Giro-branded bicycle, motorcyle and snow helmets that already have the camera mounted on top. The device can capture up to 30 fps videos and tag them with GPS info, has built-in WiFi, Bluetooth and two hours of battery life. Just like its predecessor, it can be controlled by an accompanying mobile app.</p>
				<a href="http://www.engadget.com/2016/01/06/360fly-4k-video-helmets/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"GoPro rivals offer 360-degree cameras, Onstar-like safety features" - MarketWatch</h2>
				<h3>Younger action-camera companies offer 360-degree video, Onstar-like safety features</h3>
				<p>February 4, 2016</p>
				<p class="snippet-text">As GoPro Inc. suffers from a gloomy holiday season, fresh action-camera faces are eagerly waiting in the wings with software features they think will usher in a new era of rugged recording. “We’re a completely different experience,” 360Fly CEO Peter Adderton, an Australian motorbike enthusiast who co-founded the telecom giant Boost Mobile, said in a recent interview.</p>
				<a href="http://www.marketwatch.com/story/gopro-rivals-ready-to-pounce-on-wounded-giant-2016-02-03" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly and BRG Sports Debut Actions Sports’ First Smart Helmet" - Transworld Business</h2>
				<p>January 6, 2016</p>
				<p class="snippet-text">The collaboration between 360fly and BRG Sports has produced the first-ever video integrated smart helmet designed for action sports</p>
				<a href="http://business.transworld.net/products/360fly-and-brg-sports-debut-actions-sports-first-smart-helmet/#4ozWg6vBBLIlzpUX.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"This New Helmet Can Do 360° HD Streaming Video And Help Riders Avoid Getting Hit" - Jalopnik</h2>
				<p>January 7, 2016</p>
				<p class="snippet-text">Bell Helmets and 360Fly are looking to shake up the action camera world by joining forces to offer the first helmet with an integrated camera. The 360Fly camera shoots 360 degrees (clever name, I know), and will bring a host of other features your GoPro can’t touch.</p>
				<a href="http://lanesplitter.jalopnik.com/tag/360fly" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"5 coolest things we've seen so far at CES 2016" - USA Today</h2>
				<p>January 5, 2016</p>
				<p class="snippet-text">LAS VEGAS — The size of a small ball, the 360fly camera takes spherical videos that don't require complicated editing — one of the coolest things we saw at the start of the Consumer Electronics Show here.</p>
				<a href="http://www.usatoday.com/story/tech/2016/01/05/5-coolest-things-weve-seen-so-far-ces-2016/78292044/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly Gives A Sneak Peek At Its 360-Degree Camera Drone" - Techcrunch</h2>
				<p>Sarah Buhr</p>
				<p>January 5, 2016</p>
				<p class="snippet-text">The 360fly camera, a small, sturdy ball with panoramic views we first discovered at CES 2014, is back again and buddying up with sports brand BRG to bring us live or recorded, 360-degree, stitchless, 4k video for sports enthusiasts – and with all that, a plan to push into virtual reality.</p>
				<a href="http://techcrunch.com/2016/01/04/360fly-pushes-into-virtual-reality-sports-and-gives-a-sneak-peek-at-its-360-degree-camera-drone/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"BRG action sports helmets get integrated 360-degree video camera" - GizMag</h2>
				<p>January 7, 2016</p>
				<p class="snippet-text">BRG (Bell, Riddell and Giro) Sports has used CES 2016 to introduce a new line of motorcycle, mountain bike and snow helmets featuring 360fly's proprietary 360-degree 4k video camera.</p>
				<a href="http://www.gizmag.com/action-sports-helmets-get-smarter-with-integrated-360-degree-video-camera/41210/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly Announces 4K Action Camera" - PC Mag</h2>
				<p>January 5, 2016</p>
				<p class="snippet-text">LAS VEGAS—The second-generation 360fly 4K camera looks a lot like its predecessor, and it still captures immersive video with a 360-degree horizontal and 240-degree vertical field of view, but internally it's a very different camera. The company has upped the image sensor resolution, so panoramic video is now captured in 4K (2,880 by 2,880 pixels) quality, a big step up from the meager 1080p offered by the previous generation model.</p>
				<a href="http://www.pcmag.com/article2/0,2817,2497242,00.asp" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>360fly Announces YouTube Sharing Capabilities</h2>
				<h3>Mobile App Update Allows Users to Share User-Generated Content Directly to YouTube</h3>
				<p>PRNewswire</p>
				<p>November 7, 2015</p>
				<p>PITTSBURGH, Nov. 11, 2015 /PRNewswire/ -- 360fly, Inc., the world's only 
				<p class="snippet-text">single-lens camera capturing stitchless 360-degree video with interactive and virtual reality viewing capabilities, today announced YouTube sharing capabilities through 360fly's iOS and Android mobile app. 360fly users can shoot, edit and share directly to YouTube from the convenience of their smartphone.</p>
				<a href="http://www.prnewswire.com/news-releases/360fly-announces-youtube-sharing-capabilities-300176824.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"22 Gifts for Serious Business Travelers" - Inc</h2>
				<p>Inc. Magazine</p>
				<p>December 8, 2015</p>
				<p class="snippet-text">360fly ($400) Slip one of these HD cameras in your bag. It records 360-degree video and photos. It’s waterproof and weighs just under five ounces. Attach to a tripod mount ($20) and a selfie-stick to get a panoramic view at a conference or your next meeting.</p>
				<a href="http://www.inc.com/john-brandon/22-gifts-for-serious-business-travelers.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"WANT LIST: 5 THINGS WE’RE COVETING THIS WEEK" - PlayBoy Magazine</h2>
				<p>PlayBoy Magazine</p>
				<p>November 20, 2015</p>
				<p class="snippet-text">Immersive, 360-degree virtual reality videos are coming. The fact that a recent edition of The New York Times shipped with Google's Cardboard VR goggles is proof. The 360fly is the first single-lens camera that captures stitchless 360-degree video with virtual reality viewing capabilities. The camera films 360 degrees horizontally, and 240 degrees vertically, allowing you to capture literally everything. The iOS app also makes it easy to shoot, edit, and share videos to YouTube.</p>
				<a href="http://www.playboy.com/articles/want-list-112015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Holiday 2015 Gift Ideas for People Who Love Tech and Gadgets" - Glamour Magazine</h2>
				<p>Glamour</p>
				<p>November 20, 2015</p>
				<p class="snippet-text">360 Fly, $400 at bestbuy.com: Great for action shots or even capturing family moments, the 360 Fly is a 360-degree video camera that allows you to share your media instantly via built-in Wi-Fi and its custom app.</p>
				<a href="http://www.glamour.com/inspired/blogs/the-conversation/2015/11/tech-gift-ideas-2015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"GQ's Best Stuff of the Year" - GQ Magazine</h2>
				<p>December 1, 2015</p>
				<a href="http://www.gq.com/gallery/best-stuff-of-the-year-2015#19" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360Fly Takes One Lens To Capture 100% Of The Action On The Slopes Other Sports Technology Video" - Sports Techie</h2>
				<p>December 8, 2015</p>
				<p class="snippet-text">Big name brands have already incorporated 360-degree video and virtual reality content as a marketing strategy to engage audiences in a unique way. In the past, viewers have seen stadiums and fields from different angles, as well as experience the perspective of how pro athletes see the game. And now, the virtual reality world is expanding into the action sports community with 360fly Inc. streaming the 2015 Dew Tour.</p>
				<a href="http://www.sporttechie.com/2015/12/07/360fly-takes-one-lens-capture-100-action-slopes/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"JORGE LORENZO JOINS 360FLY"- Transworld</h2>
				<p>Transworld</p>
				<p>October 22, 2015</p>
				<p class="snippet-text">The two-time MotoGP World Champion will represent the brand and its game-changing video technology and utilize 360fly to capture and share immersive 360-degree and virtual reality content.</p>
				<a href="http://business.transworld.net/news/jorge-lorenzo-joins-360fly/#1CPbKmpQJOl8tDfe.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"An action camera with eyes in the back of its head, the 360fly ensures you don't miss a thing. " - Morning Herald</h2>
				<p>Morning Herald</p>
				<p>December 4, 2015</p>
				<p class="snippet-text">An action camera with eyes in the back of its head, the 360fly ensures you don't miss a thing. Smaller than a tennis ball, it comes with a range of mounts for attaching the camera practically anywhere, plus it's compatible with GoPro accessories. It's even waterproof if you use the supplied plug to seal the microphone hole. - Sydney Morning Herald</p>
				<a href="http://www.smh.com.au/digital-life/computers/gadgets-on-the-go/review-360fly-360degree-action-camera-20151203-glea2f.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Gift Guide 2015: The Ultimate Gift Guide for Your Brother" - Men's Fitness</h2>
				<p>Men's Fitness</p>
				<p>December 7, 2015</p>
				<p class="snippet-text">This small gadget is big on power with its ability to snap quality video of an entire 360-degree paranoramic experience. Not only can he shoot on-the-go, but he can upload, edit, and share his entire journey within minutes through his cell phone, via the app. What's more, it's water-resistant and compatible with Android and IOS.</p>
				<a href="http://www.mensfitness.com/life/gearandtech/gift-guide-2015-ultimate-gift-guide-your-brother/slide/6" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Street View your life" - CNET</h2>
				<h3>This year you won't need a professional camera rig to grab an immersive 360-degree view of your surroundings so you can create and share your own VR photos and video.</h3>
				<p></p>
				<p>February 19, 2016</p>
				<p class="snippet-text">The people behind the 360fly used more than a decade of experience developing panoramic solutions for military and aviation to make this tough little single-lens action cam that's water-, dust- and shock-resistant. By using a single lens, you avoid having seams in your video created by stitching together shots from two or more cameras. </p>
				<a href="http://www.cnet.com/news/360-degree-cameras-2016/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Street View your life" - CNET</h2>
				<h3>This year you won't need a professional camera rig to grab an immersive 360-degree view of your surroundings so you can create and share your own VR photos and video.</h3>
				<p></p>
				<p>February 19, 2016</p>
				<p class="snippet-text">The people behind the 360fly used more than a decade of experience developing panoramic solutions for military and aviation to make this tough little single-lens action cam that's water-, dust- and shock-resistant. By using a single lens, you avoid having seams in your video created by stitching together shots from two or more cameras. </p>
				<a href="http://www.cnet.com/news/360-degree-cameras-2016/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"THE WORLD'S ONLY SINGLE-LENS 360 CAM IS ABOUT TO GO 4K" - Maxim</h2>
				<h3>Capture everything in ultra-high def.</h3>
				<p></p>
				<p>February 16, 2016</p>
				<p class="snippet-text">You're familiar with stitching—not just the physical kind you get at the emergency room after each epic adventure, but also the way your camera uses special software to link together panoramic pics. To avoid that awkward stitching, 360fly's camera magically captures everything around you with just a single lens. And in April, they'll be releasing a 4K version.</p>
				<a href="http://www.maxim.com/gear/360fly-releases-4k-panoramic-camera-2016-02" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"THE WORLD'S ONLY SINGLE-LENS 360 CAM IS ABOUT TO GO 4K" - Maxim</h2>
				<h3>Capture everything in ultra-high def.</h3>
				<p></p>
				<p>February 16, 2016</p>
				<p class="snippet-text">You're familiar with stitching—not just the physical kind you get at the emergency room after each epic adventure, but also the way your camera uses special software to link together panoramic pics. To avoid that awkward stitching, 360fly's camera magically captures everything around you with just a single lens. And in April, they'll be releasing a 4K version.</p>
				<a href="http://www.maxim.com/gear/360fly-releases-4k-panoramic-camera-2016-02" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"We Tested The Best 360 Degree Cameras Under $1000" - Gizmodo</h2>
				<p>February 9, 2016</p>
				<p class="snippet-text">Shooting 360 degree video, which can be viewed on Youtube, Facebook, or with a VR headset, was once reserved for professionals with a professional budget. Over the last year, we’ve begun seeing a number of manufacturers releasing 360 degree cameras that promise high quality immersive video at a price point that consumers can actually afford.</p>
				<a href="http://gizmodo.com/heres-what-you-can-expect-to-get-from-360-cameras-for-1755798348" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"We Tested The Best 360 Degree Cameras Under $1000" - Gizmodo</h2>
				<p>February 9, 2016</p>
				<p class="snippet-text">Shooting 360 degree video, which can be viewed on Youtube, Facebook, or with a VR headset, was once reserved for professionals with a professional budget. Over the last year, we’ve begun seeing a number of manufacturers releasing 360 degree cameras that promise high quality immersive video at a price point that consumers can actually afford.</p>
				<a href="http://gizmodo.com/heres-what-you-can-expect-to-get-from-360-cameras-for-1755798348" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"GoPro rivals offer 360-degree cameras, Onstar-like safety features" - MarketWatch</h2>
				<h3>Younger action-camera companies offer 360-degree video, Onstar-like safety features</h3>
				<p>February 4, 2016</p>
				<p class="snippet-text">As GoPro Inc. suffers from a gloomy holiday season, fresh action-camera faces are eagerly waiting in the wings with software features they think will usher in a new era of rugged recording. “We’re a completely different experience,” 360Fly CEO Peter Adderton, an Australian motorbike enthusiast who co-founded the telecom giant Boost Mobile, said in a recent interview.</p>
				<a href="http://www.marketwatch.com/story/gopro-rivals-ready-to-pounce-on-wounded-giant-2016-02-03" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"GoPro rivals offer 360-degree cameras, Onstar-like safety features" - MarketWatch</h2>
				<h3>Younger action-camera companies offer 360-degree video, Onstar-like safety features</h3>
				<p>February 4, 2016</p>
				<p class="snippet-text">As GoPro Inc. suffers from a gloomy holiday season, fresh action-camera faces are eagerly waiting in the wings with software features they think will usher in a new era of rugged recording. “We’re a completely different experience,” 360Fly CEO Peter Adderton, an Australian motorbike enthusiast who co-founded the telecom giant Boost Mobile, said in a recent interview.</p>
				<a href="http://www.marketwatch.com/story/gopro-rivals-ready-to-pounce-on-wounded-giant-2016-02-03" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly puts 4K video cams on helmets" - Engadget</h2>
				<h3>Adrenaline junkies, these are for you.</h3>
				<p>January 7, 2016</p>
				<p class="snippet-text">If you don't want to MacGyver an action helmet, you might like 360fly's new products. The company has launched not only a 360-degree action cam that can take 4K videos at CES, but also four Bell- and Giro-branded bicycle, motorcyle and snow helmets that already have the camera mounted on top. The device can capture up to 30 fps videos and tag them with GPS info, has built-in WiFi, Bluetooth and two hours of battery life. Just like its predecessor, it can be controlled by an accompanying mobile app.</p>
				<a href="http://www.engadget.com/2016/01/06/360fly-4k-video-helmets/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly puts 4K video cams on helmets" - Engadget</h2>
				<h3>Adrenaline junkies, these are for you.</h3>
				<p>January 7, 2016</p>
				<p class="snippet-text">If you don't want to MacGyver an action helmet, you might like 360fly's new products. The company has launched not only a 360-degree action cam that can take 4K videos at CES, but also four Bell- and Giro-branded bicycle, motorcyle and snow helmets that already have the camera mounted on top. The device can capture up to 30 fps videos and tag them with GPS info, has built-in WiFi, Bluetooth and two hours of battery life. Just like its predecessor, it can be controlled by an accompanying mobile app.</p>
				<a href="http://www.engadget.com/2016/01/06/360fly-4k-video-helmets/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"BRG action sports helmets get integrated 360-degree video camera" - GizMag</h2>
				<p>January 7, 2016</p>
				<p class="snippet-text">BRG (Bell, Riddell and Giro) Sports has used CES 2016 to introduce a new line of motorcycle, mountain bike and snow helmets featuring 360fly's proprietary 360-degree 4k video camera.</p>
				<a href="http://www.gizmag.com/action-sports-helmets-get-smarter-with-integrated-360-degree-video-camera/41210/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"This New Helmet Can Do 360° HD Streaming Video And Help Riders Avoid Getting Hit" - Jalopnik</h2>
				<p>January 7, 2016</p>
				<p class="snippet-text">Bell Helmets and 360Fly are looking to shake up the action camera world by joining forces to offer the first helmet with an integrated camera. The 360Fly camera shoots 360 degrees (clever name, I know), and will bring a host of other features your GoPro can’t touch.</p>
				<a href="http://lanesplitter.jalopnik.com/tag/360fly" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"BRG action sports helmets get integrated 360-degree video camera" - GizMag</h2>
				<p>January 7, 2016</p>
				<p class="snippet-text">BRG (Bell, Riddell and Giro) Sports has used CES 2016 to introduce a new line of motorcycle, mountain bike and snow helmets featuring 360fly's proprietary 360-degree 4k video camera.</p>
				<a href="http://www.gizmag.com/action-sports-helmets-get-smarter-with-integrated-360-degree-video-camera/41210/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"This New Helmet Can Do 360° HD Streaming Video And Help Riders Avoid Getting Hit" - Jalopnik</h2>
				<p>January 7, 2016</p>
				<p class="snippet-text">Bell Helmets and 360Fly are looking to shake up the action camera world by joining forces to offer the first helmet with an integrated camera. The 360Fly camera shoots 360 degrees (clever name, I know), and will bring a host of other features your GoPro can’t touch.</p>
				<a href="http://lanesplitter.jalopnik.com/tag/360fly" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly and BRG Sports Debut Actions Sports’ First Smart Helmet" - Transworld Business</h2>
				<p>January 6, 2016</p>
				<p class="snippet-text">The collaboration between 360fly and BRG Sports has produced the first-ever video integrated smart helmet designed for action sports</p>
				<a href="http://business.transworld.net/products/360fly-and-brg-sports-debut-actions-sports-first-smart-helmet/#4ozWg6vBBLIlzpUX.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly and BRG Sports Debut Actions Sports’ First Smart Helmet" - Transworld Business</h2>
				<p>January 6, 2016</p>
				<p class="snippet-text">The collaboration between 360fly and BRG Sports has produced the first-ever video integrated smart helmet designed for action sports</p>
				<a href="http://business.transworld.net/products/360fly-and-brg-sports-debut-actions-sports-first-smart-helmet/#4ozWg6vBBLIlzpUX.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"5 coolest things we've seen so far at CES 2016" - USA Today</h2>
				<p>January 5, 2016</p>
				<p class="snippet-text">LAS VEGAS — The size of a small ball, the 360fly camera takes spherical videos that don't require complicated editing — one of the coolest things we saw at the start of the Consumer Electronics Show here.</p>
				<a href="http://www.usatoday.com/story/tech/2016/01/05/5-coolest-things-weve-seen-so-far-ces-2016/78292044/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"5 coolest things we've seen so far at CES 2016" - USA Today</h2>
				<p>January 5, 2016</p>
				<p class="snippet-text">LAS VEGAS — The size of a small ball, the 360fly camera takes spherical videos that don't require complicated editing — one of the coolest things we saw at the start of the Consumer Electronics Show here.</p>
				<a href="http://www.usatoday.com/story/tech/2016/01/05/5-coolest-things-weve-seen-so-far-ces-2016/78292044/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly Announces 4K Action Camera" - PC Mag</h2>
				<p>January 5, 2016</p>
				<p class="snippet-text">LAS VEGAS—The second-generation 360fly 4K camera looks a lot like its predecessor, and it still captures immersive video with a 360-degree horizontal and 240-degree vertical field of view, but internally it's a very different camera. The company has upped the image sensor resolution, so panoramic video is now captured in 4K (2,880 by 2,880 pixels) quality, a big step up from the meager 1080p offered by the previous generation model.</p>
				<a href="http://www.pcmag.com/article2/0,2817,2497242,00.asp" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly Announces 4K Action Camera" - PC Mag</h2>
				<p>January 5, 2016</p>
				<p class="snippet-text">LAS VEGAS—The second-generation 360fly 4K camera looks a lot like its predecessor, and it still captures immersive video with a 360-degree horizontal and 240-degree vertical field of view, but internally it's a very different camera. The company has upped the image sensor resolution, so panoramic video is now captured in 4K (2,880 by 2,880 pixels) quality, a big step up from the meager 1080p offered by the previous generation model.</p>
				<a href="http://www.pcmag.com/article2/0,2817,2497242,00.asp" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360Fly Takes One Lens To Capture 100% Of The Action On The Slopes Other Sports Technology Video" - Sports Techie</h2>
				<p>December 8, 2015</p>
				<p class="snippet-text">Big name brands have already incorporated 360-degree video and virtual reality content as a marketing strategy to engage audiences in a unique way. In the past, viewers have seen stadiums and fields from different angles, as well as experience the perspective of how pro athletes see the game. And now, the virtual reality world is expanding into the action sports community with 360fly Inc. streaming the 2015 Dew Tour.</p>
				<a href="http://www.sporttechie.com/2015/12/07/360fly-takes-one-lens-capture-100-action-slopes/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360Fly Takes One Lens To Capture 100% Of The Action On The Slopes Other Sports Technology Video" - Sports Techie</h2>
				<p>December 8, 2015</p>
				<p class="snippet-text">Big name brands have already incorporated 360-degree video and virtual reality content as a marketing strategy to engage audiences in a unique way. In the past, viewers have seen stadiums and fields from different angles, as well as experience the perspective of how pro athletes see the game. And now, the virtual reality world is expanding into the action sports community with 360fly Inc. streaming the 2015 Dew Tour.</p>
				<a href="http://www.sporttechie.com/2015/12/07/360fly-takes-one-lens-capture-100-action-slopes/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"22 Gifts for Serious Business Travelers" - Inc</h2>
				<p>Inc. Magazine</p>
				<p>December 8, 2015</p>
				<p class="snippet-text">360fly ($400) Slip one of these HD cameras in your bag. It records 360-degree video and photos. It’s waterproof and weighs just under five ounces. Attach to a tripod mount ($20) and a selfie-stick to get a panoramic view at a conference or your next meeting.</p>
				<a href="http://www.inc.com/john-brandon/22-gifts-for-serious-business-travelers.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"22 Gifts for Serious Business Travelers" - Inc</h2>
				<p>Inc. Magazine</p>
				<p>December 8, 2015</p>
				<p class="snippet-text">360fly ($400) Slip one of these HD cameras in your bag. It records 360-degree video and photos. It’s waterproof and weighs just under five ounces. Attach to a tripod mount ($20) and a selfie-stick to get a panoramic view at a conference or your next meeting.</p>
				<a href="http://www.inc.com/john-brandon/22-gifts-for-serious-business-travelers.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Gift Guide 2015: The Ultimate Gift Guide for Your Brother" - Men's Fitness</h2>
				<p>Men's Fitness</p>
				<p>December 7, 2015</p>
				<p class="snippet-text">This small gadget is big on power with its ability to snap quality video of an entire 360-degree paranoramic experience. Not only can he shoot on-the-go, but he can upload, edit, and share his entire journey within minutes through his cell phone, via the app. What's more, it's water-resistant and compatible with Android and IOS.</p>
				<a href="http://www.mensfitness.com/life/gearandtech/gift-guide-2015-ultimate-gift-guide-your-brother/slide/6" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Gift Guide 2015: The Ultimate Gift Guide for Your Brother" - Men's Fitness</h2>
				<p>Men's Fitness</p>
				<p>December 7, 2015</p>
				<p class="snippet-text">This small gadget is big on power with its ability to snap quality video of an entire 360-degree paranoramic experience. Not only can he shoot on-the-go, but he can upload, edit, and share his entire journey within minutes through his cell phone, via the app. What's more, it's water-resistant and compatible with Android and IOS.</p>
				<a href="http://www.mensfitness.com/life/gearandtech/gift-guide-2015-ultimate-gift-guide-your-brother/slide/6" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"An action camera with eyes in the back of its head, the 360fly ensures you don't miss a thing. " - Morning Herald</h2>
				<p>Morning Herald</p>
				<p>December 4, 2015</p>
				<p class="snippet-text">An action camera with eyes in the back of its head, the 360fly ensures you don't miss a thing. Smaller than a tennis ball, it comes with a range of mounts for attaching the camera practically anywhere, plus it's compatible with GoPro accessories. It's even waterproof if you use the supplied plug to seal the microphone hole. - Sydney Morning Herald</p>
				<a href="http://www.smh.com.au/digital-life/computers/gadgets-on-the-go/review-360fly-360degree-action-camera-20151203-glea2f.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"An action camera with eyes in the back of its head, the 360fly ensures you don't miss a thing. " - Morning Herald</h2>
				<p>Morning Herald</p>
				<p>December 4, 2015</p>
				<p class="snippet-text">An action camera with eyes in the back of its head, the 360fly ensures you don't miss a thing. Smaller than a tennis ball, it comes with a range of mounts for attaching the camera practically anywhere, plus it's compatible with GoPro accessories. It's even waterproof if you use the supplied plug to seal the microphone hole. - Sydney Morning Herald</p>
				<a href="http://www.smh.com.au/digital-life/computers/gadgets-on-the-go/review-360fly-360degree-action-camera-20151203-glea2f.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"GQ's Best Stuff of the Year" - GQ Magazine</h2>
				<p>December 1, 2015</p>
				<a href="http://www.gq.com/gallery/best-stuff-of-the-year-2015#19" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"GQ's Best Stuff of the Year" - GQ Magazine</h2>
				<p>December 1, 2015</p>
				<a href="http://www.gq.com/gallery/best-stuff-of-the-year-2015#19" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Holiday 2015 Gift Ideas for People Who Love Tech and Gadgets" - Glamour Magazine</h2>
				<p>Glamour</p>
				<p>November 20, 2015</p>
				<p class="snippet-text">360 Fly, $400 at bestbuy.com: Great for action shots or even capturing family moments, the 360 Fly is a 360-degree video camera that allows you to share your media instantly via built-in Wi-Fi and its custom app.</p>
				<a href="http://www.glamour.com/inspired/blogs/the-conversation/2015/11/tech-gift-ideas-2015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Holiday 2015 Gift Ideas for People Who Love Tech and Gadgets" - Glamour Magazine</h2>
				<p>Glamour</p>
				<p>November 20, 2015</p>
				<p class="snippet-text">360 Fly, $400 at bestbuy.com: Great for action shots or even capturing family moments, the 360 Fly is a 360-degree video camera that allows you to share your media instantly via built-in Wi-Fi and its custom app.</p>
				<a href="http://www.glamour.com/inspired/blogs/the-conversation/2015/11/tech-gift-ideas-2015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"WANT LIST: 5 THINGS WE’RE COVETING THIS WEEK" - PlayBoy Magazine</h2>
				<p>PlayBoy Magazine</p>
				<p>November 20, 2015</p>
				<p class="snippet-text">Immersive, 360-degree virtual reality videos are coming. The fact that a recent edition of The New York Times shipped with Google's Cardboard VR goggles is proof. The 360fly is the first single-lens camera that captures stitchless 360-degree video with virtual reality viewing capabilities. The camera films 360 degrees horizontally, and 240 degrees vertically, allowing you to capture literally everything. The iOS app also makes it easy to shoot, edit, and share videos to YouTube.</p>
				<a href="http://www.playboy.com/articles/want-list-112015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"WANT LIST: 5 THINGS WE’RE COVETING THIS WEEK" - PlayBoy Magazine</h2>
				<p>PlayBoy Magazine</p>
				<p>November 20, 2015</p>
				<p class="snippet-text">Immersive, 360-degree virtual reality videos are coming. The fact that a recent edition of The New York Times shipped with Google's Cardboard VR goggles is proof. The 360fly is the first single-lens camera that captures stitchless 360-degree video with virtual reality viewing capabilities. The camera films 360 degrees horizontally, and 240 degrees vertically, allowing you to capture literally everything. The iOS app also makes it easy to shoot, edit, and share videos to YouTube.</p>
				<a href="http://www.playboy.com/articles/want-list-112015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>360fly Announces YouTube Sharing Capabilities</h2>
				<h3>Mobile App Update Allows Users to Share User-Generated Content Directly to YouTube</h3>
				<p>PRNewswire</p>
				<p>November 7, 2015</p>
				<p>PITTSBURGH, Nov. 11, 2015 /PRNewswire/ -- 360fly, Inc., the world's only 
				<p class="snippet-text">single-lens camera capturing stitchless 360-degree video with interactive and virtual reality viewing capabilities, today announced YouTube sharing capabilities through 360fly's iOS and Android mobile app. 360fly users can shoot, edit and share directly to YouTube from the convenience of their smartphone.</p>
				<a href="http://www.prnewswire.com/news-releases/360fly-announces-youtube-sharing-capabilities-300176824.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>360fly Announces YouTube Sharing Capabilities</h2>
				<h3>Mobile App Update Allows Users to Share User-Generated Content Directly to YouTube</h3>
				<p>PRNewswire</p>
				<p>November 7, 2015</p>
				<p>PITTSBURGH, Nov. 11, 2015 /PRNewswire/ -- 360fly, Inc., the world's only 
				<p class="snippet-text">single-lens camera capturing stitchless 360-degree video with interactive and virtual reality viewing capabilities, today announced YouTube sharing capabilities through 360fly's iOS and Android mobile app. 360fly users can shoot, edit and share directly to YouTube from the convenience of their smartphone.</p>
				<a href="http://www.prnewswire.com/news-releases/360fly-announces-youtube-sharing-capabilities-300176824.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"JORGE LORENZO JOINS 360FLY"- Transworld</h2>
				<p>Transworld</p>
				<p>October 22, 2015</p>
				<p class="snippet-text">The two-time MotoGP World Champion will represent the brand and its game-changing video technology and utilize 360fly to capture and share immersive 360-degree and virtual reality content.</p>
				<a href="http://business.transworld.net/news/jorge-lorenzo-joins-360fly/#1CPbKmpQJOl8tDfe.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"JORGE LORENZO JOINS 360FLY"- Transworld</h2>
				<p>Transworld</p>
				<p>October 22, 2015</p>
				<p class="snippet-text">The two-time MotoGP World Champion will represent the brand and its game-changing video technology and utilize 360fly to capture and share immersive 360-degree and virtual reality content.</p>
				<a href="http://business.transworld.net/news/jorge-lorenzo-joins-360fly/#1CPbKmpQJOl8tDfe.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Camera Tech Revolution: Bloomberg West" - Bloomberg</h2>
				<p>September 10, 2015</p>
				<p class="snippet-text">Full episode of "Bloomberg West." Guests: 360fly CEO Peter Adderton along with other industry leaders (Source: Bloomberg)</p>
				<a href="http://www.bloomberg.com/news/videos/2015-09-05/camera-tech-revolution-bloomberg-west-full-show-9-04-" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly announces exclusive U.S. retail partnership with Best Buy" - TransWorld</h2>
				<p>July 29, 2015</p>
				<p class="snippet-text wrap-para">360FLY EYES SEPTEMBER LAUNCH – REPRESENTS ADVENT OF WIDESPREAD ACCESSIBILITY FOR VIRTUAL REALITY CONTENT PITTSBURGH (JULY 29, 2015) – 360fly, Inc., the world’s only single-lens camera capturing stitchless 360-degree video with interactive and virtual reality viewing capabilities, today announced an exclusive in-store and online retail partnership with electronics retailer Best Buy. Prior to 360fly’s in-store availability in mid-September, Best Buy will begin taking preorders at BestBuy.com. 360fly will retail for $399 and be available in approximately 900 store locations throughout the country. Read more at http://business.transworld.net/news/360fly-announces-exclusive-u-s-retail-partnership-with-best-buy/#PiP235wQFkczDZkH.99</p>
				<a href="http://business.transworld.net/news/360fly-announces-exclusive-u-s-retail-partnership-with-best-buy/#wU3MusYfGfcvzos8.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Shoot 360 degrees of video with new camera" - Fox Business</h2>
				<h3>360fly CEO Peter Adderton on the company’s new camera</h3>
				<p>July 16, 2015</p>
				<a href="http://video.foxbusiness.com/v/4357872055001/shoot-360-degrees-of-video-with-new-camera/?playlist_id=3166411554001#sp=show-clips" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly signs Kalani David"  - Transworld</h2>
				<h3>On and off the Boards, U16 ISA World Surfing Champion Will Capture and Share Life in 360-Degrees</h3>
				<p>June 30, 2015</p>
				<p class="snippet-text">Capturing the action of someone who’s riding is as diverse and explosive as Kalani David is difficult. The seventeen year old Hawaiian is a natural with a board under his feet; he’s an ISA world surfing champion and has stacked up solid finishes in skate contests across the country. 360fly hopes to give us a glimpse into Kalani’s life and capture his shredding with their 360-degree camera. David is the newest member of the team, joining big names like Chad Reed and Chip Ganassi Racing.</p>
				<a href="http://business.transworld.net/164177/news/360fly-signs-kalani-david/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly could do for VR what GoPro did for action cameras" - Mashable</h2>
				<p>June 23, 2015</p>
				<p class="snippet-text">GoPro's done a good job," 360fly's CEO Peter Adderton told Mashable. "They own the [action camera] space. No one owns the 360-degree video space." Adderton, a serial entrepreneur and extreme sports fanatic, whose previous successes include founding the prepaid wireless network Boost Mobile, which he then sold to Sprint, thinks his company's tennis ball-sized 360fly camera could become the GoPro of 360-degree videos and help popularize virtual reality, not just for tech nerds, but for everyone.</p>
				<a href="http://mashable.com/2015/06/23/360fly-360-degree-video-vr/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly takes on GoPro" - CNBC</h2>
				<p>June 12, 2015</p>
				<p class="snippet-text">360fly CEO Peter Adderton, says he wants his company to be the innovators in the camera space, and discusses competition with GoPro.</p>
				<a href="http://www.nbcnews.com/watch/cnbc/360fly-takes-on-gopro-462532675848" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"This GoPro challenger can record every direction at the same time" - NYPost</h2>
				<p>June 5, 2015</p>
				<p class="snippet-text">GoPro may want to flip around its camera: A new, high-tech rival is about to enter the race — and it can see in every direction at once. 360fly, a Pittsburgh-based startup founded by scientists from Carnegie Mellon’s robotics lab, is launching a plum-sized camera that can deliver a virtual-reality experience to a smartphone. The camera, to debut in August, has a wow factor that can soar past any model from GoPro — whose revolutionary wearable hi-def cameras have turned the company into an $8 billion Wall Street darling.</p>
				<a href="http://nypost.com/2015/06/04/this-gopro-challenger-can-record-every-direction-at-the-same-time/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly, Jeff Ward join Chip Ganassi Rallycross" - NBC Sports</h2>
				<p>June 4, 2015</p>
				<p class="snippet-text">Chip Ganassi Racing Teams, Inc. (CGRT) announced today a partnership with 360fly, the category creator in 360-degree digital video products, on their two entries in Red Bull Global Rallycross (GRC). 360fly will be the primary partner on the team’s No. 38 Ford Fiesta for the doubleheader in Daytona on June 20-21 as well as the race in Washington, DC on Aug. 15 with former Target Chip Ganassi Racing INDYCAR driver Jeff Ward behind the wheel.</p>
				<a href="http://motorsportstalk.nbcsports.com/2015/06/04/jeff-ward-360fly-join-chip-ganassi-rallycross/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Will Chad Reed Pull Out of the Outdoors? | The Great Helmet Cam Debate" - VurbMoto</h2>
				<p>June 1, 2015</p>
				<p class="snippet-text">If you aren’t already aware, Chad Reed has been involved in some controversy with the professional motocross series, as well as the well known helmet cam company GoPro. What is this dispute about? Well, recently the TwoTwo Motorsports rider/team owner signed a $500,000 contract with a brand new, state of the art, 360 Degree helmet camera company entitled 360fly.</p>
				<a href="http://vurbmoto.com/blogs/will-chad-reed-pull-out-outdoors-great-helmet-cam-/24572/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly Partners with Motocross Star Chad Reed" - TransWorld</h2>
				<p>TransWorld</p>
				<p>May 29, 2015</p>
				<p class="snippet-text">The new 360-degree POV camera company, 360fly, is gaining some momentum this year, after picking up surf pro Carissa Moore and just announcing the addition of Motocross champion Chad Reed to the team. Check out what new CEO Peter Adderton had to say about the latest 360fly ambassador.</p>
				<a href="http://business.transworld.net/162344/news/360fly-partners-motocross-star-chad-reed/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>360fly appoints Boost mobile founder Peter Adderton as CEO - Transworld</h2>
				<h3>360fly appoints Boost Mobile Founder Peter Adderton as CEO</h3>
				<p>May 5, 2015</p>
				<p class="snippet-text">Carissa Moore, flatland BMX champ Terry Adams, and X Games champ Simon Dumont round out the athlete roster for 360fly, an emerging POV camera technology that was originally used on robots to capture images in all directions, without limits. Today the tech company announces its new CEO Peter Adderton, founder of Boost Mobile and most recently the CEO of Mandalay Digital. Here’s the details.</p>
				<a href="http://business.transworld.net/161823/news/360fly-appoints-boost-mobile-founder-peter-adderton-new-ceo/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Will This Crazy New 360 Degree Camera Make GoPros Obsolete?" - MPORA</h2>
				<h3>This could genuinely revolutionize action sports filming</h3>
				<p>Tristan Kennedy</p>
				<p>March 19, 2015</p>
				<p class="snippet-text">Thought your new GoPro, Contour or Sony Action cam was state-of-the-art? Well, it may well be made to look old-school in comparison to the new kid on the block. Meet the 360fly action camera, a camera that films not only whatever it’s pointed at, but everything else around it as well.</p>
				<a href="http://mpora.com/articles/will-incredible-new-360-degree-camera-make-gopros-obsolete#uwGLeAbftht4vHav.97" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Simon Dumont partners with all-new 360 degree POV camera brand 360fly" - Freeskier Magazine</h2>
				<p>Thacher Stone</p>
				<p>March 12, 2015</p>
				<p class="snippet-text">X Games champion and freeskiing stud Simon Dumont has officially teamed up with a new POV camera brand 360fly. Unlike other popular point of view products, the mountable camera produces a 360 degree image, for users to capture everything that is going on around them in the heat of the moment.</p>
				<a href="http://freeskier.com/the-wire/simon-dumont-partners-new-360-degree-pov-camera-brand-360fly" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Upstarts: 360fly Camera" - Transworld Business</h2>
				<p>Kailee Bradstreet</p>
				<p>February 17, 2015</p>
				<p class="snippet-text">The POV camera market is exploding in growth right now, and some new players are coming to the table with technology that could possibly change the game for many athletes and consumers. New camera company 360fly, backed up by film/TV director and producer of Nitro Circus and Jackass Jeff Tremaine, has introduced a new POV cam that features 360-degree video technology. The company believes this innovative product will take the category to the next level, eliminating the need to look through a viewfinder while filming since the 360-degree field of view allows you to capture everything surrounding you, including yourself.</p>
				<a href="http://business.transworld.net/158770/news/upstarts-360fly-camera/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Terry Adams X 360fly Promo" - Transworld RIDE bmx</h2>
				<p>Zach Krejmas</p>
				<p>February 5, 2015</p>
				<p class="snippet-text">Terry Adams just scored himself a new endorsement in the form of 360fly, a 360 degree view POV camera that even allows the view to “swipe around” while watching the video for differing vantage points. Are they onto something with this?</p>
				<a href="http://bmx.transworld.net/videos/terry-adams-x-360fly-promo/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Panoramic" - Carnegie Mellon Today</h2>
				<p>Andrew Swensen</p>
				<p>January 20, 2015</p>
				<p class="snippet-text">During Michael Rondinelli's (CTO at 360fly) undergraduate years, he collaborated with a faculty team who had the task of building and testing a robotic rover for exploration of the planet Mars. In particular, he worked on developing panoramic technology that would translate visual images captured by the rover and transmit them back to NASA scientists on Earth. The end result—through a melding of mechanical and electrical engineering, software design, and artificial intelligence—was a visual system that incorporated 360-degree viewing.</p>
				<a href="http://www.carnegiemellontoday.com/issues/january-2015-issue/startups/panoramic/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly Action Camera Best of CES" - Men's Journal</h2>
				<p>Gear Lab</p>
				<p>January 13, 2015</p>
				<p class="snippet-text">Action cameras have gotten seriously sophisticated lately, getting smaller, steadier, and sturdier. Still, if you point the camera in the wrong direction as you're shredding through powder, you might see little more than snow. The 360fly action cam aims to fix this focal-point problem. This spherical camera records everything you're seeing in front of you, above and below you, and all around you, in 360-degrees.</p>
				<a href="http://www.mensjournal.com/gear/electronics/360fly-action-camera-best-of-ces-2015-20150107#ixzz3OtjKGRut" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"5 Awesome Things We Saw at CES 2015" - TechnoBuffalo</h2>
				<p>TODD HASELTON</p>
				<p>January 12, 2015</p>
				<p class="snippet-text">We saw tons of stuff during this year’s CES, everything ranging from drones to laptops, smartphones, new gaming gear, wearables and more. A few products already won our “Best of CES 2015″ awards, but there were some other really amazing things worth highlighting, too. TODD HASELTON</p>
				<a href="http://www.technobuffalo.com/2015/01/12/5-awesome-things-we-saw-at-ces-2015/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"10 Coolest Gadgets at CES" - Men's Health</h2>
				<p>Sarah Jacobsson Purewal</p>
				<p>January 12, 2015</p>
				<p class="snippet-text">Have you ever looked at your GoPro footage and thought, “Damn, I wish I could turn this thing around and see that killer wave behind me?” Well, with 360fly you can: This new sportscam has an ultra-wide-angle lens that captures 360 degrees of horizontal video and 240 degrees of vertical video at the same time. That means when you re-watch your video, you can actually turn the camera around in a full circle and see what’s going on in every direction. The 360fly is waterproof, gets about 3 hours of battery life, and will ship this spring for $499.</p>
				<a href="http://www.menshealth.com/techlust/10-gadgets-ces-2015" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Our Favorite CES Tech That You'll Actually Use" - Outside Online</h2>
				<h3>Your wearables, cameras, and even your bike are about to get a whole lot smarter.</h3>
				<p>Michael Frank</p>
				<p>January 9, 2015</p>
				<p class="snippet-text">The Consumer Electronics Show proves that wearables are getting more pervasive and more immersive, with brand-new 360-degree cameras and sensors that monitor your heart rate 24/7. Here are some of our favorite new wearables for 2015.</p>
				<a href="http://www.outsideonline.com/outdoor-gear/gear-shed/design-tech/The-Coolest-New-Tech-Products-of-2015.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Hits of the CES Gadget Parade" - Newsweek</h2>
				<p>David Weiss</p>
				<p>January 8, 2015</p>
				<p class="snippet-text">Mount it on your bike helmet or handlebars, and turn those boring home movies into vertigo-inducing action sequences. An attendant app allows you to shoot, edit and share your magnum opus with a wide-eyed world. The even better news? Unsuspecting subjects will not mug or fake-smile for the camera—because you needn't point it, no one knows they're even being filmed.</p>
				<a href="http://www.newsweek.com/hits-ces-gadget-parade-297792" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly - Coolest Way to Record Action Sports Video" - TechnoBuffalo</h2>
				<h3>You want crazy? the 360fly will give you crazy.</h3>
				<p>BRANDON RUSSELL</p>
				<p>January 7, 2015</p>
				<p class="snippet-text">The action cam market is crowded. GoPro isn’t the only name you think of anymore, making it increasingly difficult for alternatives to stand out. Most of them are the same, but some companies are getting increasingly creative with their ideas. 360-degree video isn’t necessarily new, but never has it been more accessible thanks to the 360fly. You want crazy? the 360fly will give you crazy.</p>
				<a href="http://www.technobuffalo.com/videos/360fly-is-the-coolest-way-to-record-action-sports-video/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Panoramic Vision" - Carnegie Mellon University</h2>
				<p>December 15, 2014</p>
				<p class="snippet-text">From death-defying athletic adventures to other once-in-a-lifetime moments, imagine video that can capture it all — literally. Thanks to Carnegie Mellon University spinout 360fly, soon everyone will be able to catch life in the round, with interactive, one-shot, 360-degree panoramic videos. "360fly doesn't just take a video. It adds a replay button to your world. Because your life is too glorious to be filtered, cropped or edited," said Amey Kanade (HNZ'09), 360fly's director of marketing.</p>
				<a href="http://www.cmu.edu/homepage/computing/2014/fall/panoramic-vision.shtml" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"The All-Seeing Video Camera" - Popular Science</h2>
				<p>Corinne Iozzio and Michael Nuñez</p>
				<p>December 1, 2014</p>
				<p class="snippet-text">Facebook, Google, and Samsung may have ventured into the virtual reality market this year, but their head-mounted displays won’t find a lot of traction without good content to support them</p>
				<a href="http://bestofwhatsnew.popsci.com/360fly" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"360fly scores $17.8M as investors bet big on interactive 360-degree video" - VentureBeat</h2>
				<p>Devindra Hardawar</p>
				<p>August 11, 2014</p>
				<p class="snippet-text">Just as the first-person video craze is reaching mainstream consumers, investors already have their eyes set on the next hot thing: interactive 360-degree videos.</p>
				<a href="http://venturebeat.com/2014/08/11/360fly-scores-17-8m-as-investors-bet-big-on-interactive-360-degree-video-exclusive/" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"Single POV Action Cameras Are Dead" - OutsideOnline</h2>
				<p>Erin Beresini</p>
				<p>June 5, 2014</p>
				<p class="snippet-text">That’s right. The future of adventure filmmaking lies in 360-degree video footage, at least according to a handful of ambitious inventors.</p>
				<a href="http://www.outsideonline.com/outdoor-gear/gear-shed/tech-talk/Capture-EverythingSeriouslyWith-360-Cameras.html" class="btn read-more round">Read More »</a>
			</div>
			<div class="col-xs-10 list-content pull-left">
				<h2>"A Camera That Covers Every Angle" - Popular Science</h2>
				<h3>No Blind Spot for This One</h3>
				<p>Corinne Iozzio</p>
				<p>May 22, 2014</p>
				<p class="snippet-text">For 16 years, EyeSee360 has made panoramic cameras for the military and other industries. Now the company has adapted its technology for the 360Fly, a consumer video camera that allows anyone to record a whole scene—360 degrees around and 240 vertically—without moving.</p>
				<a href="http://www.popsci.com/article/gadgets/camera-covers-every-angle" class="btn read-more round">Read More »</a>
			</div>
			<!-- hello -->
			<div class="col-xs-10 list-content pull-left">
				<h2>"The 360fly Can Capture Your Entire World" - TechCrunch</h2>
				<p>John Biggs</p>
				<p>January 17, 2014</p>
				<p class="snippet-text">A Pittsburgh-based tech company approached us on the CES 2014 show floor last week and asked for a bit of time to talk about their product, a small ball that can take panoramic video and is rugged enough to be strapped to a helmet or surf board. The product, called the 360fly, is still in beta but the company wanted to show it to us – complete with male surfer model – so we could get an idea of how the device worked.</p>
				<a href="http://techcrunch.com/2014/01/17/the-360-fly-can-capture-your-entire-world/" class="btn read-more round">Read More »</a>
			</div>
		</div>

	</div>
</div>