<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();

?>
<div class="community-inner pro-circuit" id="athlete-marketing">
	<div class="pro-container" id="">
		<div class="container wrapper-width">
			<div class="covertext text-contain ">
				<h1 class="extreme-headline">
					<b>Pro Circuit Kawasaki</b>
				</h1>
                <h2 class="extreme-headline">Motocross</h2>
			</div>
		</div>
	</div>
	<div class="bio-container">
		<div class="bio-left greybg ">
			<div class="bio-left-child-1">
				<h3>Pro Circuit Kawasaki's Bio</h3>
				<p>Pro Circuit is synonymous with winning in the world of supercross and motocross racing. The team has amassed an amazing 29 AMA Championships in the last two decades, more than any other team in the race paddock.  With six motocross des nations titles to their credit as well, Pro Circuit stands at the pinnacle of the motocross world.
				</p>
				<p>Working with the sport's all time greats like Jeremy McGrath, Ricky Carmichael and James Stewart, the Pro Circuit team has a history long steeped with providing the world's best racers with the best products.
				</p>
				<p>For 2016, team Pro Circuit returns with a five rider team, including 4X Arenacross Champion Tyler Bowers, Joey Savatgy, Arnaud Tonus, Chris Alldredge and Adam Cianciarulo. The team will compete in both the 250 West and East Supercross series, as well as the Lucas Oil outdoor championships.</p>
			</div>
			<div class="bio-left-child-2">
			</div>
		</div>
		<div class="bio-right greenbg">
			<div class="">
				<div class="athlete_highlight_text">
					<h4>Teams Highlights</h4>
					<div class="bio-right-content">
						<p >29 AMA Championships</p>						
					</div>
					<div class="bio-right-content">
						<p >6 Motocross de Nations Championships</p>
					</div>
					<div class="bio-right-content">
						<p >150+ Individual race wins</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="athlete-social">
	<div class="athlete-wrapper">
		<div class="col-sm-12 col-md-12 col-lg-6 icons-wrapper">
	        <div class="athlete-social-name"><p class="pull-left follow">Follow Pro Circuit Kawasaki</p></div>
	      	<div class="pull-left icons">
		        <a href="https://twitter.com/pcraceteam" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
		        <a href="https://www.facebook.com/ProCircuit78/" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
		        <a href="https://www.instagram.com/pcraceteam/" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
	        </div>
      	</div>
	</div>
</div>

