<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

?>
<div class="wrapper-width container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 support-device-container">
            <h1>360fly's Supported Mobile Devices</h1>
            <h3><b>Android:</b></h3>
            <ul class="support-devices">
            	<li>HTC: M8, M9, A9</li>
            	<li>LG: G3, G4, Flex 2, Nexus 5</li>
            	<li>Motorola: Moto X 2nd Gen, Nexus 6, Droid Turbo/2, Moto Z</li>
            	<li>Samsung: Galaxy S5, Galaxy S6/Edge, Galaxy S7/Edge, Galaxy Note 4/Edge, Galaxy Note 5, Galaxy Note 7</li>
            	<li>Sony: Xperia Z3</li>
            	<li>Nexus 6P, Nexus 5X, Pixel</li>
            </ul>
            <h3><b>iOS:</b></h3>
            <p>Fully Compatible:</p>
            <ul class="support-devices">
                <li>iPhone 5s</li>
                <li>iPhone SE</li>
                <li>iPhone 6/6s</li>
                <li>iPhone 6Plus/6sPlus</li>
                <li>iPhone 7,7Plus</li>
                <li>iPad Pro</li>
                <li>iPad Air</li>
                <li>iPad Air 2</li>
                <li>iPad Mini 2</li>
                <li>iPad Mini 3</li>
                <li>iPad Mini 4</li>
            </ul>
            <p>Partially Compatible:</p>
            <p>These devices can explore videos from the site and have basic camera controls. They cannot play or edit videos from the camera:</p>
            <ul class="support-devices">
                <li>iPhone 4S</li>
            	<li>iPhone 5</li>
            	<li>iPhone 5c</li>
            	<li>iPad (3rd generation)</li>
            	<li>iPad (4th generation)</li>
            	<li>iPad Mini</li>
            </ul>
        </div>
    </div>
</div>
