
<div class="padder">

<div class="page-title">
    <h1><?php echo $this->__('My Email Log') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->getCollection()->count() > 0) { ?>

    <p><?php echo $this->__('Click on the view link to display a copy of the email.') ?></p>

        <div class="module_servers">
          <div class="table-responsive">
            <table class="table table-striped mm-table mm-email-log">
              <thead>
                <tr>
                  <th>Dated</th>
                  <th>Subject</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
              <?php foreach ($this->getCollection() as $email) { ?>
              
                <tr>
                  <td><?php
                  $dateTimestamp = Mage::getModel('core/date')->timestamp(strtotime($email->getDated()));
                  echo $currentDate = date('M d Y h:i A', $dateTimestamp);
                  ?> ET</td>
                  <td><?php echo $email->getEmailSubject()?></td>
                  <td><a href="/magento/noc/email/view/id/<?php echo $email->getEmailId()?>" target="_blank" class="btn bnt-link">View</a></td>
                </tr>
              
              <?php } ?>
              </tbody>
            </table>
          </div>

        </div>

<?php } else { ?>

    <p><?php echo $this->__('You do not have any emails provisioned yet.') ?></p>

    <?php }  ?>
</div>