
<div class="padder">

<div class="page-title">
    <h1><?php echo $this->__('My Emails') ?></h1>
</div>    

<?php if($this->getCollection()->count() > 0) { ?>
    
        <div class="module_servers">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Host Name</th>
                            <th>Host IP</th>
                            <th>Level</th>
                            <th>CPU</th>
                            <th>RAM</th>
                            <th>SSD /home</th>
                            <th>BANDWIDTH</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->getCollection() as $email) { ?>
                        
                           <tr>
                                <td><?php echo $email->getHostName(); ?></td>
                                <td><?php echo $email->getHostIp()?></td>
                                <td><?php echo $email->getLevel()?></td>
                                <td><?php echo $email->getLevel()?></td>
                                <td><?php echo $email->getLevel() * 2?>GB</td>
                                <td><?php echo $email->getLevel() * 7.5?>GB</td>
                                <td><?php echo $email->getLevel() * 250 + 250?>GB</td>
                            </tr>
                        
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Available Graphs
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=3600">1h</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=10800">3h</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=43200">12h</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=86400">1d</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=604800">7d</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=1209600">14d</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=2592000">1m</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=7776000">3m</a> |
                            <a href="<?php echo $this->getCurrentUrl() ?>?&duration=23328000">9m</a>
                            </th>
                            <thalign="right"> 
                            <!-- Autorefresh <input type="checkbox" name="autorefresh">-->
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    $hostgraphs = $this->getEmailGraphsFromZabbix();
                    while (list($key, $value) = each($hostgraphs)) {
                    ?>

                    <tr>
                        <td colspan="2"><img src="/noc/email/graph/id/<?php echo $key . $this->getGraphUrlParams() . $this->getGraphDuration() ?>"></td>
                    </tr>

                    <?php } ?>
                                        
                    </tbody>
                </table>
            </div>

        </div>
        
<?php } else { ?>

    <p><?php echo $this->__('This email does not exist.') ?></p>

    <?php }  ?>

<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="btn btn-link">&laquo; <?php echo $this->__('Back To Emails') ?></a>
</div>
</div>