<div class="padder">
	<div class="page-title">
	    <h1><?php echo $this->__('Submit Migration Info') ?></h1>
	</div>

     <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	<div class="box simple_contact">
     	<form id="noc_migration_submit" name="noc_migration_submit" action="/noc/migration/submit" method="post">
     	<script type="text/javascript">
     	//< ![CDATA[
     	var customForm = new VarienForm('noc_migration_submit');
     	//]]>
     	</script>
     	    <fieldset class="group-select">
                    <div class="panel panel-default">
                         <div class="panel-heading">
                              <h2 class="panel-title">Control Panel Information</h2>
                         </div>
                         <div class="panel-body">
                              <p class="text07">This helps us migrate ssl certificates</p>
                              <div class="row">
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="control_panel_url" class="required">Control Panel Url <em>*</em></label>
                                             <input name="control_panel_url" id="control_panel_url" title="Control Panel Url" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="control_panel_username" class="required">Control Panel Username <em>*</em></label>
                                             <input name="control_panel_username" id="control_panel_username" title="Control Panel Url" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="control_panel_password" class="required">Control Panel Password <em>*</em></label>
                                             <input name="control_panel_password" id="control_panel_password" title="Control Panel Passsword" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>
                    
                    <div class="panel panel-default">
                         <div class="panel-heading">
                              <h2 class="panel-title">SSH Information</h2>
                         </div>
                         <div class="panel-body">
                              <p class="text07">We cannot perform a migration without this</p>
                              <div class="row">
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="ssh_url" class="required">SSH Url <em>*</em></label>
                                             <input name="ssh_url" id="ssh_url" title="SSH Url" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="ssh_username" class="required">SSH Username <em>*</em></label>
                                             <input name="ssh_username" id="ssh_username" title="SSH Username" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="ssh_password" class="required">SSH Password <em>*</em></label>
                                             <input name="ssh_password" id="ssh_password" title="SSH Password" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>
                    
                    <div class="panel panel-default">
                         <div class="panel-heading">
                              <h2 class="panel-title">Magento Admin Information</h2>
                         </div>
                         <div class="panel-body">
                              <p class="text07">We need this to perform our performance test, tune and optimization</p>
                              <div class="row">
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="magento_url" class="required">Magento Admin Url <em>*</em></label>
                                             <input name="magento_url" id="magento_url" title="Magento Url" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="magento_username" class="required">Magento Admin Username <em>*</em></label>
                                             <input name="magento_username" id="magento_username" title="Magento Username" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="magento_password" class="required">Magento Admin Password <em>*</em></label>
                                             <input name="magento_password" id="magento_password" title="Magento Password" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>

                    <div class="panel panel-default">
                         <div class="panel-heading">
                              <h2 class="panel-title">DNS Registrar Information</h2>
                         </div>
                         <div class="panel-body">
                              <p class="text07">We need this to switch your dns for the final cutover after your approval</p>
                              <div class="row">
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="registrar_url" class="required">DNS Registrar Url <em>*</em></label>
                                             <input name="registrar_url" id="registrar_url" title="DNS Registrar Url" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="registrar_username" class="required">DNS Registrar Username <em>*</em></label>
                                             <input name="registrar_username" id="registrar_username" title="DNS Registrar Username" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                                   <div class="col-xs-12 col-md-4">
                                        <div class="form-group">
                                             <label for="registrar_password" class="required">DNS Registrar Password <em>*</em></label>
                                             <input name="registrar_password" id="registrar_password" title="DNS Registrar Password" value="" class="required-entry form-control" type="text" />
                                        </div>
                                   </div>
                              </div>
                         </div>
                    </div>

                    <div class="buttons-set a-center">
                       <p class="required" style="margin-top:15px;">* Required Fields</p>
                       <button type="submit" class="btn btn-default" title="<?php echo $this->__('Submit'); ?>"><?php echo $this->__('Submit'); ?></button>
                    </div>        
               </fieldset>
     	</form>
	</div>
</div>