<div class="padder">
	
	<div class="page-title">
	    <h1><?php echo $this->__('Submit Migration Info') ?></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	
	<div class="box simple_contact">

	    <fieldset class="group-select">
	        <h4 class="text04">Your migration information has been submitted.  Please allow up to 24 hours for us to complete it.  Once completed we will notify by sending you a migration ready for review email.</h4>      
	    </fieldset>

	</div>
</div>