<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
?>
<div class="container wrapper-width user-guide">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <a href="javascript:window.print()" class="fa user-guide-print-link-button" title="Print this Guide"><!--img src="/skin/frontend/b-responsive/360fly/images/user-guide/print-icon.png" alt="Print this page" width="25" height="21"--></a>

            <h1 class="text-center border-bottom" style="margin-bottom:5px;">360fly-HD User Guide (Android <i class="fa fa-android"></i>)</h1>
            <a href="/360fly-hd-user-manual-ios" class="fa other-guide-link apple" title="Link to the HD IOS Guide"></a>
            
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/blocks/google-translate-right.phtml')->toHtml(); ?>
            
            <a class="user-guide-title" data-toggle="collapse" data-target="#getting-started" aria-expanded="true"><h3 class="user-guide-title">Getting Started</h3></a>
            <div id="getting-started" class="getting-started user-guide-subsection collapse in">
                <h3>Congratulations on landing your new 360fly HD camera.</h3>
                    <p>
                        This powerful camera and its apps make you part of an emerging community of visual storytellers and explorers, one that is fundamentally changing the way we experience and capture the world. <strong>Join them now and begin sharing your best 360° videos, ideas, and inspiration at <a href="<?php echo $baseUrl; ?>">www.360fly.com</a>.</strong>
                    </p>
                
                <br>
                <h3>Charging the Battery:</strong></h3>
                    <p>To charge your camera, insert the USB cable into a USB outlet adapter rated at 1.5A to 2.1A (most tablet charger adapters) and plug it into the <strong>360fly HD</strong> Power Cradle.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                            <img src="<?php echo $skinUrl;?>images/user-guide/getting-started.jpg" class="img-responsive img-full-width" alt="Getting Started" title="Getting Started"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Next, simply place the camera on the charger base. For best results, charge your camera while it’s powered off.<br/>
                    While your camera is charging, its LED indicator will flash green. When fully charged, the camera LED will remain solid green. It is recommended you charge your camera for at least 30 minutes prior to its first use.<br/>
                    When your camera battery is low, the LED will display a light purple color. Be sure to charge your camera before using it when the LED is light purple.</p>
            
                <br>
                <h3>Powering Up:</h3>
                <p>Remove the camera from its Power Cradle and turn it on by holding the <strong>OnePush</strong> button down for four seconds.<br/>
                        When powering up, the camera will vibrate three times and the LED will flash blue. After completing the power-up sequence, the LED will display a solid blue color, indicating that your camera is on and ready to fly.<br/>
                        You can also use the <strong>OnePush</strong> button to power down your camera by holding the button down for four seconds. The camera will vibrate four times to indicate that it is powering down.
                     </p>
                    <p><strong>Camera Care and Storage:</strong></p>
                    <p>A clean lens means clearer footage. Your <strong>360fly HD</strong> camera lens can be cleaned using a soft cloth. Lens solution, water, or isopropyl alcohol can be added for additional cleaning.<br/>
                    We highly recommend storing your <strong>360fly HD</strong> camera inside a protective case to help protect its lens from scratching, chipping, or other damage.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#app-powering-it-all"><h3 class="user-guide-title">The App Powering It All</h3></a>
                <div id="app-powering-it-all" class="app-powering-it-all collapse">

                    <div id="download-360fly-app" class="download-360fly-app user-guide-subsection">
                        <h3>Download the 360fly App:</h3>
                        <p>
                            The <strong>360fly</strong> app is key to capturing your entire world in 360° HD video on your Android™ smartphone. Just search “360fly” in the Google Play™ store and download the free <strong>360fly</strong> app to your mobile device. Remember, the app allows your mobile device to serve as your camera’s remote control and viewfinder, giving you the power to capture, edit, and share clips on the fly.<br/>
                            The first time launching the app, you will see a brief <i>Shoot, Share, Swipe</i> tutorial on recording, editing, exploring and sharing 360° videos with your new camera and app. Check it out. It’s well worth your time.
                        </p>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-1.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-2.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-3.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-4.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                            </div>
                        </div>
                     </div>
                    
                    <div class="create-account user-guide-subsection" id="create-account">
                        <p class="disp-inline-block mt20"><strong>Create Your 360fly Account:</strong></p>
                        <p>On the first app launch, you’ll also be prompted to build your 360fly.com profile.  You can select the “Sign In” option to activate via your existing social media account, or you can choose to “Sign Up” for a unique 360fly.com account by entering a new username, email address, and setting a password for your new profile. Signing in with your social media accounts will allow you to instantly share and post videos with the click of a button. You can also choose to skip the account creation step by selecting “Skip” in the top-left corner.</p>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-create-account-1.png" class="img-responsive img-full-width" alt="Create Account On 360fly App"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-create-account-2.png" class="img-responsive img-full-width" alt="Create Account On 360fly App"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-create-account-3.png" class="img-responsive img-full-width" alt="Create Account On 360fly App"/>
                            </div>
                        </div>
                    </div>
                    
                    <div class="connect-360fly-4k user-guide-subsection" id="connect-360fly-4k">
                        <p class="disp-inline-block mt20"><strong>Connecting to the 360fly HD:</strong></p>
                        <p>The application will lead you through a step-by-step guide for establishing a Bluetooth LE and Wi-Fi connection to your camera.</p>
                        <p><strong>Note:</strong> A Wi-Fi connection is required to view your camera’s live feed and stored content. Check your device settings to ensure that Bluetooth and Wi-Fi are both enabled prior to connecting.</p>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-1.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-2.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-3.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-4.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                        </div>
                        <p class="disp-inline-block mt20">Once the power up sequence is completed, your <strong>360fly HD</strong> will automatically enter pairing mode with your mobile device. For best results, place your phone about three inches away from your camera in order to get a good strong signal. Once the devices are paired, it’s time to give your camera a unique name and password. Now your device will automatically connect to your <strong>360fly HD</strong> camera via Wi-Fi.</p>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-5.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-6.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                                <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-7.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                            </div>
                        </div>
                        <p class="disp-inline-block mt20"><strong>Note:</strong> Your camera may require a firmware update prior to initial use. If a firmware update is available, your application will automatically walk you through the steps to download and transfer the most up-to-date software load to your camera. <strong>Congratulations! You’re all connected and ready to start flying in 360°!</strong></p>
                    </div>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#app-menu"><h3 class="user-guide-title">360fly App Main Menu</h3></a>
                <div id="app-menu" class="app-menu collapse user-guide-subsection">
            
                    <p>The <strong>360fly</strong> app homepage is the hub of the 360° video world. It starts with "Featured Videos" where you can explore the most epic videos from the <strong>360fly</strong> community around the globe. You can also view the latest video highlights from a range of categories, including "Snow", "Water", "Land", "Travel", and "Air", where the latest trending videos vie for a coveted "Clips of the Week" spot. The "User Generated" section lets you share your 360° vision with the entire <strong>360fly</strong> family and anyone with the <strong>360fly</strong> app. Be sure to check in often—and remember to tag your best edits shared across social media using #360fly and #MissNothing.
                    At the bottom of the homepage screen, you can select from four options:
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-menu-1.png" class="img-responsive img-full-width" alt="Home Page Four Options"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><strong>Camera: </strong>Select the <img src="<?php echo $skinUrl; ?>images/user-guide/camera.png" class="user-guide-img" alt="Camera"/> icon to connect to your <strong>360fly</strong> camera. Once connected, you will have full control of all of your camera’s features and functions through your smartphone. You can also view and download all of your video files stored on your camera’s memory.</p>
                    <p><strong>On My Phone:</strong> Select the <img src="<?php echo $skinUrl; ?>images/user-guide/on-my-phone.png" class="user-guide-img" alt="On My Phone"/> icon to access all of your videos, clips, and photos stored on your smartphone. Review, edit, and playback your content anytime/anywhere without the need to connect to the internet or your <strong>360fly</strong> camera.</p>
                    <p><strong>Explore:</strong> Select the <img src="<?php echo $skinUrl; ?>images/user-guide/explore.png" class="user-guide-img" alt="Explore"/> icon to browse public content uploaded by other <strong>360fly</strong> users. Select and view featured videos, along with hosted content spanning a variety of interesting topics and categories. Be sure to check back regularly to view the latest exciting uploads from other <strong>360fly</strong> users.</p>
                    <p><strong>Profile:</strong> Select the <img src="<?php echo $skinUrl; ?>images/user-guide/profile.png" class="user-guide-img" alt="Profile"/> icon to view all of the video content uploaded to your <strong>360fly</strong> account. You can access and playback any videos you’ve uploaded from anywhere you have an internet connection—with or without connecting to your <strong>360fly</strong> camera. You can also choose to make any of your videos public and share your experiences with friends and other <strong>360fly</strong> users. To make changes or edits to your account, just tap the edit profile option at the top of the screen.<br/>
                    </p>    
                    <p>
                        <strong>Note:</strong> An active internet connection is required to access and view content.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#camera-home-screen"><h3 class="user-guide-title">Camera Home Screen</h3></a>
                <div id="camera-home-screen" class="camera-home-screen collapse user-guide-subsection">
                
                    <p>Once your smartphone is connected to the camera, the app’s home screen gives you full access to all camera controls, modes, and settings options.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-camera-home-screen.png" class="img-responsive img-full-width" alt="Camera Home Screen Options"/>
                        </div>
                    </div>

                    <p class="disp-inline-block mt20"><strong>Note:</strong> The <strong>360fly HD</strong> AutoPilot mode sets your app to automatically pan your image to the area of footage that has the highest degree of motion. To use this feature within your camera’s live-view, just tap the AutoPilot icon <img src="<?php echo $skinUrl; ?>images/user-guide/autopilot.png" class="user-guide-img" alt="Autopilot"/>. Use the slider located on the left of your display to adjust the sensitivity level.
                    </p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#recording-video"><h3 class="user-guide-title">Recording Video</h3></a>
                <div id="recording-video" class="recording-video collapse user-guide-subsection">
            
                    <p>Recording 360° videos with the <strong>360fly</strong> app is quick and easy. Simply tap the white record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to start capturing. The center of the capture button will turn red and your camera will simultaneously vibrate while its LED turns from blue to red.
                    </p>
                    <p>To stop recording, tap the red record button <img src="<?php echo $skinUrl; ?>images/user-guide/red-record-hd.png" class="user-guide-img" alt="Red Record Button"/>. Your camera will vibrate twice and the LED will switch from solid red to blue, indicating that your recording has ended.</p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#recording-without-app"><h3 class="user-guide-title">Recording Without the App</h3></a>
                <div id="recording-without-app" class="recording-without-app collapse user-guide-subsection">
            
                    <p>If you don’t have access to the <strong>360fly</strong> app on your mobile device, you can record videos directly on your camera. Simply press the <strong>OnePush</strong> button on your camera to launch a 360° recording. Your camera will vibrate and the LED will turn from blue to solid red, indicating that your camera is now recording. To stop recording, press the <strong>OnePush</strong> button again.</p>
                    <p><strong>Note:</strong> The default recording mode for 360fly HD videos is pre-set at a resolution of 1504x1504 at 30 frames per second.</p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#accessing-camera-files"><h3 class="user-guide-title">Accessing Your Camera’s Stored Files</h3></a>
                <div id="accessing-camera-files" class="accessing-camera-files collapse user-guide-subsection">
            
                    <p>While connected to "camera" home screen, select the “On My Camera” icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-store-icon.png" class="user-guide-img" alt="Camera Storage Icon"/> to view your camera’s storage library. This selection will display all of the video files stored within your camera’s internal memory.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-storage-1.png" class="img-responsive img-full-width" alt="Access Video Storage Files"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-storage-2.png" class="img-responsive img-full-width" alt="Access Photos Storage Files"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">To view a video, simply tap on the thumbnail image of your desired file, and the application will automatically launch your file within its video player.<br/>
                    To download a video or image directly to your smartphone, simply tap the download icon <img src="<?php echo $skinUrl; ?>images/user-guide/download.png" class="user-guide-img" alt="Download Icon"/>. This will copy your file directly into your phone’s gallery.
                    </p>
                    <p><strong>Note:</strong> Storing your video files onto your phone’s gallery will allow you to play back content without the need to connect your device to your <strong>360fly</strong> camera. Additionally, the application’s video editing tools are (only) available for content stored in your phone’s gallery.<br/>
                    To delete a file, press and hold the thumbnail image. The app will request confirmation that you would like to delete the file before it is permanently removed from the camera’s memory storage.
                    </p>
                </div>
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#video-playback"><h3 class="user-guide-title">Video Playback</h3></a>
                <div id="video-playback" class="video-playback collapse user-guide-subsection">
            
                    <p>Tapping a video thumbnail image within your camera’s library will automatically launch the <strong>360fly</strong> player. Once the video uploads, you can pan the angle of view by swiping across the screen. You can also pan using your device’s built-in gyroscope function by turning your phone in the desired orientation.<br/>
                    To zoom in during playback, simply pinch two fingers together on your device’s display until you reach the desired zoom level. To zoom out, expand two fingers across the display and release when you have reached the ideal zoom level.
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-playback-1.png" class="img-responsive img-full-width" alt="Video Playback"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Use the playback bar at the bottom of your screen to pause/restart a video or fast-forward/rewind to a desired point within your video file.</p>
                    <p>You can adjust your video player’s settings by selecting the “Settings” icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display. Under this menu, you have the option to toggle your phone’s gyroscopic panning feature on/off or remove the app’s graphics/overlays from view during playback. The settings menu also features the option to invert your video file, allowing you the ability to switch videos that were recorded upside-down to the correct viewing orientation.</p>
                </div>
                <!-- <div id="auto-pilot-mode" class="auto-pilot-mode">
                    <h2 class="border-bottom">AutoPilot Playback Mode:</h2>
                    <p>The <strong>360fly HD</strong> AutoPilot mode sets your application to automatically track the area within your 360° footage that has the highest degree of activity, allowing you to simply sit back and enjoy all of the action without the need to interact with your device. </p>
                    <p>To watch your footage using AutoPilot mode, just tap the AutoPilot icon <img src="<?php //echo $skinUrl; ?>images/user-guide/autopilot.png" class="user-guide-img" alt="Autopilot"/> located at the top-right portion of your screen. Use the slider located on the left of your display to adjust the sensitivity level of the panning feature.</p>
                </div> -->
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#virtual-reality-mode"><h3 class="user-guide-title">Virtual Reality Goggle Playback</h3></a>
                <div id="virtual-reality-mode" class="virtual-reality-mode collapse user-guide-subsection">
            
                    <p><strong>360fly HD</strong> footage is designed to work seamlessly with most Google Cardboard VR viewers with just the touch of a button.<br/>
                        To watch your footage using a Google Cardboard viewer, just tap the VR viewer icon <img src="<?php echo $skinUrl; ?>images/user-guide/vr-viewer.png" class="user-guide-img" alt="VR Viewer"/> located at the top-right while you’re in the video player screen. Next, simply place your smartphone into your VR headset and immerse yourself inside the incredible world of <strong>360fly HD</strong> content.
                    </p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#gen-setting"><h3 class="user-guide-title">General Camera Settings</h3></a>
                <div id="gen-setting" class="gen-setting collapse user-guide-subsection">
            
                    <p>Adjust your camera controls and general system settings by pressing the "Settings" icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display screen. Under this menu, you can check your camera’s battery life, memory capacity, and make changes to your camera’s name and password. The "Settings" menu also gives you the power to turn off your camera directly from the application.<br/>
                    The team at <strong>360fly</strong> is always working to provide the latest features and camera software upgrades. Be sure to use the "Settings" menu to periodically check for new updates to your camera’s software and new available features.
                    </p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#image-tuning"><h3 class="user-guide-title">Image Tuning</h3></a>
                <div id="image-tuning" class="image-tuning collapse user-guide-subsection">
            
                    <p>The <strong>360fly HD</strong> default settings are optimized to deliver the highest quality output within a wide range of environments and lighting conditions. To get the most out of your videos and images, the <strong>360fly HD</strong> offers advanced options that will allow you to fine-tune your camera’s settings.</p>
                    <p>To access your camera’s fine-tuning options, tap the “Camera Tuning” icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-tuning.png" class="user-guide-img" alt="Camera Tuning Icon"/> located at the bottom right of your display screen.  A set of sliders will appear on screen, giving you options to make adjustments to the following tuning settings:</p>
                    <p><strong>Saturation:</strong> Use the <img src="<?php echo $skinUrl; ?>images/user-guide/camera-saturation.png" class="user-guide-img" alt="Camera Saturation"/> slider to adjust the intensity of the colors captured within your footage.</p>
                    <p><strong>Brightness:</strong> The <img src="<?php echo $skinUrl; ?>images/user-guide/camera-brightness.png" class="user-guide-img" alt="Camera Brightness"/> slider fine-tunes the brightness of the subjects within your image without affecting your camera’s exposure compensation.</p>
                    <p><strong>Exposure:</strong> Adjust the <img src="<?php echo $skinUrl; ?>images/user-guide/camera-exposure.png" class="user-guide-img" alt="Camera Exposure"/> slider to tune your camera image sensor’s sensitivity to light. For brighter environments (i.e. direct sunlight), use a lower exposure setting. Apply an increased exposure setting for darker environments. The slider also allows you to lock in a specific setting and override the camera from automatically adjusting to varying light conditions. The lock remains in place until you manually turn it off or the camera is powered down.</p>
                    <p><strong>Contrast:</strong> Increase the <img src="<?php echo $skinUrl; ?>images/user-guide/camera-contrast.png" class="user-guide-img" alt="Camera Contrast"/> setting to achieve a more vivid picture or lower the setting to deliver a slightly flatter appearance.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#edit-share-content"><h3 class="user-guide-title">Editing and Sharing Content</h3></a>
                <div id="edit-share-content" class="edit-share-content collapse user-guide-subsection">
            
                    <p>If you haven’t already, you will need to download your desired file from your camera library into your smart device’s memory in order to access the <strong>360fly app</strong> editing and sharing features.</p>
                    <p>You can access your camera’s library by selecting the “On My Camera” icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-store-icon.png" class="user-guide-img" alt="Camera Storage Icon"/> to view your camera’s storage library. After locating your selected video, tap the download icon <img src="<?php echo $skinUrl; ?>images/user-guide/download.png" class="user-guide-img" alt="Download Icon"/> to begin the file transfer process.</p>
                    <p>From the app’s main menu screen, select the “On My Phone” tab <img src="<?php echo $skinUrl; ?>images/user-guide/phone-content.png" class="user-guide-img" alt="View Phone Content"/> to view your stored content within your phone’s memory.</p>
                    <p>Select the video that you would like to edit to launch the file. As the video begins to play, tap the scissor icon <img src="<?php echo $skinUrl; ?>images/user-guide/scissor.png" class="user-guide-img" alt="Scissor"/> to enter into edit mode. There are three tools that enable you to edit and share your 360° footage: <strong>Clip Capture, Watch Me, and Still Capture</strong>.</p>
                    <p><img src="<?php echo $skinUrl; ?>images/user-guide/clip-capture.png" class="user-guide-img" alt="Clip Capture"/><strong> Clip Capture:</strong> Edit and share your clips in their native 360° format. Select this tool to trim your video by picking the parts of your 360° footage that you want to edit, store, and share.</p>
                    <p>After launching "Clip Capture", select the “Play” icon to start playing the video. At the location that you would like to begin your clip, press the <img src="<?php echo $skinUrl; ?>images/user-guide/clip-capture.png" class="user-guide-img" alt="Clip Capture"/> icon to start capturing. You will notice a green status ring around the icon indicating the time you have left in your capture session. You can record up to five minutes in one session.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-1.png" class="img-responsive img-full-width" alt="Clip Capture 1"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Press the <img src="<?php echo $skinUrl; ?>images/user-guide/clip-capture.png" class="user-guide-img" alt="Clip Capture"/> icon again to stop your clip. You can start and stop multiple times to create one continuous clip with multiple segments.</p>
                    <p>Once you have captured your video, press the “Done” button in the top-right corner and allow a few seconds for your video to process.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-2.png" class="img-responsive img-full-width" alt="Clip Capture 2"/>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-3.png" class="img-responsive img-full-width" alt="Clip Capture 3"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Once your video completely processes, you can click to preview.  In the "Preview" menu you’ll have the ability to add music, color filters, or apply slow and fast motion to the video, to create an awesome, fully immersive 360° clip. See below for more details on adding "Music", "Filters", and "Playback Speed Adjustment".</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-4.png" class="img-responsive img-full-width" alt="Clip Capture 4"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><img src="<?php echo $skinUrl; ?>images/user-guide/watch-me.png" class="user-guide-img" alt="Watch Me"/><strong> Watch Me:</strong> Create a standard 16:9 ratio clip from your original 360° footage. Use the "Watch Me" tool to record your movements as you pan left and right within the video. Wherever you swipe, shift and zoom while capturing in this mode, the resulting output will be cropped and saved as a shareable 16:9 video clip; capturing your unique point of view, ready to share with the world.</p>
                    <p>After launching the "Watch Me" tool, select the “Play” icon to start reviewing your video. At the location that you would like to begin your clip, press the <img src="<?php echo $skinUrl; ?>images/user-guide/watch-me.png" class="user-guide-img" alt="Watch Me"/> icon to start capturing. You’ll notice a green status ring around the icon indicating the time you have left in your capture session. You can record up to 10 minutes in one session.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-watch-me-1.png" class="img-responsive img-full-width" alt="Watch Me 1"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">As your video is recording, move the point of view by panning right, left, up, and down with your finger or by physically moving your device to pan via the gyroscope. Your resulting video clip will capture your point of view by following all of your movements.</p>
                    <p>You can also use the "AutoPilot" mode to automatically adjust the point of view within your clip by selecting the  <img src="<?php echo $skinUrl; ?>images/user-guide/autopilot.png" class="user-guide-img" alt="Autopilot"/> icon in the top right corner of the screen. "AutoPilot" will pan the point of view within your clip by automatically selecting the area within the video that contains the highest degree of activity.</p>
                    <p>When you’re done recording, click on the <img src="<?php echo $skinUrl; ?>images/user-guide/watch-me.png" class="user-guide-img" alt="Watch Me"/> icon to stop recording. You can start and stop multiple times in various locations of your video file to create a single clip.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-watch-me-2.png" class="img-responsive img-full-width" alt="Watch Me 2"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">When complete, click on the “Done” button and allow a few seconds for your video to process. You can now add some special effects like music, slow/fast motion, or change the image filter to apply a unique color scheme to your clip. See below for more details on adding "Music", "Filters", and "Playback Speed Adjustment".</p>
                    <p><strong>Note:</strong> Your app will remain in "Preview" mode after making adjustments to your clip until you select the “Save” button in the top right corner of your display. Once you have clicked the “Save” button, you’ll be prompted to name your "Watch Me" masterpiece and add a description.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-watch-me-3.png" class="img-responsive img-full-width" alt="Watch Me 3"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Your "Watch Me" videos are stored in your Android “Movie” folder and can be viewed on your phone and shared to social media sites in the same manner as any other movie file stored on your phone.</p>
                    <p><strong>Adding Filters:</strong> Tap the <img src="<?php echo $skinUrl; ?>images/user-guide/filters.png" class="user-guide-img" alt="Filters"/> icon to select from an array of filters and color enhancements for your video clip. After selecting, you’ll see a preview of the filter applied over your footage. When you’ve decided on the perfect filter, hit “Apply” to add it, or select the back arrow to return to the original, unfiltered file.</p>
                    <p><strong>Playback Speed Adjustments:</strong> Tap the <img src="<?php echo $skinUrl; ?>images/user-guide/playback-speed-adjust.png" class="user-guide-img" alt="Playback Speed Adjust"/> icon to speed up or slow down a section of your clip. Select just a portion of your edit using the sliders on the playback bar, or select the full clip. You can slide the green bar back and forth to select the section of your video that you wish to adjust. Next, use the speed control bar to increase or decrease the playback speed faster or slower for that selection. As you adjust, you’ll see a preview of the playback speed adjustment applied to your footage. Once you’re happy with your selection, hit “Apply” to add your speed adjustment to your clip or select the back arrow to return to the original file.</p>
                    <p><strong>Adding Soundtracks:</strong> Use the <img src="<?php echo $skinUrl; ?>images/user-guide/add-soundtrack.png" class="user-guide-img" alt="Add SoundTrack"/> option to add a track to your clip by selecting from an array of music options. You can choose between a 50/50 mix of music and your video’s ambient sound or 100% music. Toggle between the two to see which option you like best. Then, simply select the perfect track from our large library of free music and hit “Apply” to add it to your video clip.</p>
                    <p><strong>Note:</strong> Your app will remain in "Preview" mode after making adjustments to your clip until you select the “Save” button in the top-right corner of your display.</p>
                    <p>Once you have clicked the “Save” button, you’ll be prompted to name your masterpiece and add a description. After saving you can elect to share your creation to your favorite social sites.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-soundtrack.png" class="img-responsive img-full-width" alt="Add SoundTrack"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><strong>Note:</strong> Your device will need an internet connection to upload the video and post to your desired social networking sites.  On some phones, if you are connected to the <strong>360fly</strong> app, you’ll need to disconnect and re-establish your internet service prior to posting.</p>
                    <p><img src="<?php echo $skinUrl; ?>images/user-guide/still-capture-mode.png" class="user-guide-img" alt="Still Capture Mode"/><strong> Still Capture Mode:</strong> Create and export photos from your captured video moments. You’re the photographer—select an area within your video, capture, and then save a still image to your phone’s image gallery.<br/>
                    After launching the "Photo Capture" tool, you’ll be prompted to select your desired image ratio. Your app will allow you to select from 360° view, square, 16:9, or panoramic output for your photo capture.
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-still-capture-1.png" class="img-responsive img-full-width" alt="Still Capture Mode"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">After you have selected your image size, press the “Play” icon to begin playing the video. Pause the video player at the location that you would like to capture your photo and align your image to the desired orientation. You can also pinch to zoom in or out for a closer view within your image prior to capturing your photo.</p>
                    <p>Tap the <img src="<?php echo $skinUrl; ?>images/user-guide/still-capture-mode.png" class="user-guide-img" alt="Still Capture Mode"/> button to capture your shot. You will see a flash and hear a shutter click. Next, select from an array of filters and color enhancements for your new photo capture. Select and preview your desired filter and tap “Apply” to confirm it or click “None” if you do not wish to apply a filter. You can share your photo to any of your connected social media sites or store your image to your phone’s photo library in a .jpeg file format.</p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#transferring-content"><h3 class="user-guide-title">Transferring Content to Your PC:</h3></a>
                <div id="transferring-content" class="collapse user-guide-subsection">           
                    <p>Your <strong>360fly HD</strong> camera doubles as a USB mass storage device when connected to your PC or Mac. To access your camera’s stored content, simply connect your USB cable to your computer and place your camera onto its power cradle. Locate your <strong>360fly</strong> camera within your computer’s folder browser to view and transfer your files to your desktop or the desired file folder.</p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#troubleshooting"><h3 class="user-guide-title">Troubleshooting</h3></a>
                <div id="troubleshooting" class="collapse user-guide-subsection">
                
                    <p><strong>Resetting Your Camera:</strong></p>
                    <p>On rare occasions, it may become necessary to manually reset your <strong>360fly HD</strong> camera if it becomes unresponsive.<br/>
                    Your camera’s reset button is located inside the mount screw housing.<br/>
                    Using a skinny dull pointed object, such as a paper clip, gently press and hold the reset button down for 5 seconds. The camera will vibrate and the LED will flash blue during the reset process. After approximately 30 seconds, the LED will turn solid blue, indicating that your camera is now ready for use.<br/>
                    <strong>Note:</strong> Resetting will <u>not</u> delete videos stored within your camera’s memory.
                    </p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#tech-support-faq"><h3 class="user-guide-title">Tech Support and FAQs</h3></a>
                <div id="tech-support-faq" class="collapse user-guide-subsection">
                    <p>The 360fly team is always here to help. For all of your support needs, FAQ answers, or to report a bug, please visit us at <a href="https://support.360fly.com/hc/en-us">www.360fly.com/support</a>. Please be sure to check back regularly to learn more about new camera features and firmware upgrades.</p>
                </div>
        </div>
    </div>
</div>
<style>
.other-guide-link {font-size: 14px; text-align: right; display: inline-block; position: absolute; right:55px; top: 34px;}
.other-guide-link:hover {color:#999;}

/* -minus */
a > h3.user-guide-title:before {
  font-family: FontAwesome;
  content:"\f068";
  font-size:18px;
  padding-right:10px;
}
/* +plus*/
a.collapsed > h3.user-guide-title:before {
    content:"\f067";
}

@media print {
    .img-full-width {width: 40%;}
    .user-guide-img {width: 15px;}
    .navbar, .header-account-links, footer, .user-guide-print-link-button, h3.user-guide-title:before {display: none;}
    .user-guide-subsection {display: block;}
    body, p, div {font-size: 13px!important;}
    p a:after {content: " (" attr(href) ")"; font-size: 80%;}
    .header+.body-wrapper { padding-top: 0px;}
    .other-guide-link {display: none;}

    .header {display: none;}
    h3.user-guide-title {padding: 5px 9px;}
}
.goog-te-gadget-simple {border: 0;}

</style>

