<?php

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
?>
<div class="container wrapper-width user-guide">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <a href="javascript:window.print()" class="fa user-guide-print-link-button" title="Print this Guide"></a>

            <h1 class="text-center border-bottom" style="margin-bottom:5px;">360fly-4k User Guide (Android <i class="fa fa-android"></i>)</h1>
            <a href="/360fly-4k-user-manual-ios" class="fa other-guide-link apple" title="Link to the 4K IOS Guide"></a>

            <a class="user-guide-title" data-toggle="collapse" data-target="#getting-started" aria-expanded="true"><h3 class="user-guide-title">Getting Started</h3></a>
            <div id="getting-started" class="getting-started user-guide-subsection collapse in">
                <h3>Congratulations on landing your new 360fly 4K camera.</h3>
                <p>This powerful camera and its apps make you part of an emerging community of visual storytellers and explorers, one that is fundamentally changing the way we experience and capture the world. <strong>Join them now and begin sharing your best 360° 4K videos, ideas, and inspiration at <a href="<?php echo $baseUrl; ?>">www.360fly.com</a>.</strong></p>
                
                <br>
                <h3>Charging the Battery:</h3>
                <p>To charge your camera, insert the USB cable into a USB outlet adapter rated at 1.5A to 2.1A (most tablet charger adapters) and plug it into the <strong>360fly 4K Power Cradle</strong>.</p>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <img src="<?php echo $skinUrl;?>images/user-guide/getting-started.jpg" class="img-responsive img-full-width" alt="Getting Started" title="Getting Started"/>
                    </div>
                </div>
                <p class="disp-inline-block mt20">Next, simply place the camera on the charger base. For best results, charge your camera while it’s powered off.</p>
                <p>
                    While your camera is charging, its LED indicator will flash green. When fully charged, the camera LED will remain solid green. It is recommended you charge your camera for at least 30 minutes prior to its first use.</p>
                <p>When your camera battery is low, the LED will display a light purple color. Be sure to charge your camera before using it when the LED is light purple.</p>
                
                <br>
                <h3>Powering Up:</h3>
                <p>Remove the camera from its <strong>Power Cradle</strong> and turn it on by holding the <strong>OnePush</strong> button down for four seconds. The triangular <strong>OnePush</strong> button is surrounded by the LED indicator and located on the side of the camera.
                    When powering up, the camera will vibrate three times and the LED will flash blue. After completing the power-up sequence, the LED will display a solid blue color, indicating that your camera is on and ready to fly.
                    </p>
                <p>You can also use the <strong>Power Cradle</strong> button to power down your camera by holding the button down for four seconds. The camera will vibrate four times to indicate that it is powering down.</p>
                
                <br>
                <h3>Camera Care and Storage:</h3>
                <p>A clean lens means clearer footage. Your <strong>360fly 4K</strong> camera lens can be cleaned using a soft cloth. Lens solution, water, or isopropyl alcohol can be added for additional cleaning.</p>
                <p>
                We highly recommend storing your <strong>360fly 4K</strong> camera inside a protective case to help protect its lens from scratching, chipping, or other damage.</p>
            </div>
              
            <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#app-powering-it-all"><h3 class="user-guide-title">The App Powering It All</h3></a>
            <div id="app-powering-it-all" class="app-powering-it-all collapse">
            
                <div id="download-360fly-app" class="download-360fly-app user-guide-subsection">
                    <h3>Download the 360fly App:</h3>
                    <p>
                        The <strong>360fly app</strong> is key to capturing your entire world in 360° 4K video on your Android smartphone. Just search “360fly” in the Google Play store and download the free <strong>360fly app</strong> to your mobile device. Remember, the app allows your mobile device to serve as your camera’s remote control and viewfinder, giving you the power to capture, edit, and share clips on the fly.</p>
                        <p>
                        The first time launching the app, you will see a brief <i>Shoot, Share, Swipe</i> tutorial on recording, editing, exploring and sharing 360° videos with your new camera and app. Check it out. It’s well worth your time.
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-1.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-2.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-3.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-install-app-4.png" class="img-responsive img-full-width" alt="Install 360fly App"/>
                        </div>
                    </div>
                </div>
                <div class="create-account user-guide-subsection" id="create-account">
                    <p class="disp-inline-block mt20"><strong>Create Your 360fly Account:</strong></p>
                    <p>On the first app launch, you’ll also be prompted to build your 360fly.com profile.  You can select the “Sign In” option to activate via your existing social media account, or you can choose to “Sign Up” for a unique 360fly.com account by entering a new username, email address, and setting a password for your new profile. Signing in with your social media accounts will allow you to instantly share and post videos with the click of a button. You can also choose to skip the account creation step by selecting “Skip” in the top-left corner.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 mb20">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-create-account-1.png" class="img-responsive img-full-width" alt="Create Account On 360fly App"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-create-account-2.png" class="img-responsive img-full-width" alt="Create Account On 360fly App"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-create-account-3.png" class="img-responsive img-full-width" alt="Create Account On 360fly App"/>
                        </div>
                    </div>
                </div>
                <div class="connect-360fly-4k user-guide-subsection" id="connect-360fly-4k">
                    <p class="disp-inline-block mt20"><strong>Connecting to the 360fly 4K:</strong></p>
                    <p>The application will lead you through a step-by-step guide for establishing a Bluetooth LE and Wi-Fi connection to your camera.</p>
                    <p><strong>Note:</strong> A Wi-Fi connection is required to view your camera’s live feed and stored content. Check your device settings to ensure that Bluetooth and Wi-Fi are both enabled prior to connecting.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-1.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-2.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-3.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-4.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Once the power up sequence is completed, your <strong>360fly 4K</strong> will automatically enter pairing mode with your mobile device. For best results, place your phone about three inches away from your camera in order to get a good strong signal. Once the devices are paired, it’s time to give your camera a unique name and passcode. Now your device will automatically connect to your 360fly 4K camera via Wi-Fi.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-5.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-6.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-6">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-connect-7.png" class="img-responsive img-full-width" alt="Connect 360fly"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><strong>Note:</strong> Your camera may require a firmware update prior to initial use. If a firmware update is available, your application will automatically walk you through the steps to download and transfer the most up-to-date software load to your camera. <strong>Congratulations! You’re all connected and ready to start flying in 360° 4K!</strong></p>
                </div>
            </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#app-menu"><h3 class="user-guide-title">360fly App Main Menu</h3></a>
                <div id="app-menu" class="app-menu collapse user-guide-subsection">
            
                    <p>The 360fly app homepage is the hub of the 360° video world. It starts with Featured Videos where you can explore the most epic videos from the <strong>360fly</strong> community around the globe. You can also view the latest video highlights from a range of categories, including Snow, Water, Land, Travel, and Air, where the latest trending videos vie for a coveted Clips of the Week spot. The User Generated section lets you share your 360° vision with the entire <strong>360fly</strong> family and anyone with the <strong>360fly app</strong>. Be sure to check in often—and remember to tag your best edits shared across social media using #360fly and #MissNothing.
                    At the bottom of the homepage screen, you can select from four options:
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-menu-1.png" class="img-responsive img-full-width" alt="Home Page Four Options"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><strong>Camera: </strong>Select the <img src="<?php echo $skinUrl; ?>images/user-guide/camera.png" class="user-guide-img" alt="Camera"/> icon to connect to your <strong>360fly</strong> camera. Once connected, you will have full control of all of your camera’s features and functions through your smartphone. You can also view and download all of your video files stored on your camera’s memory.</p>
                    <p><strong>On My Phone:</strong> Select the <img src="<?php echo $skinUrl; ?>images/user-guide/on-my-phone.png" class="user-guide-img" alt="On My Phone"/> icon to access all of your videos, clips, and photos stored on your smartphone. Review, edit, and playback your content anytime/anywhere without the need to connect to the internet or your 360fly camera.</p>
                    <p><strong>Explore:</strong> Select the <img src="<?php echo $skinUrl; ?>images/user-guide/explore.png" class="user-guide-img" alt="Explore"/> icon to browse public content uploaded by other <strong>360fly</strong> users. Select and view featured videos, along with hosted content spanning a variety of interesting topics and categories. Be sure to check back regularly to view the latest exciting uploads from other <strong>360fly 4K users</strong>.</p>
                    <p><strong>Profile:</strong> Select the <img src="<?php echo $skinUrl; ?>images/user-guide/profile.png" class="user-guide-img" alt="Profile"/> icon to view all of the video content uploaded to your <strong>360fly</strong> account. You can access and playback any videos you’ve uploaded from anywhere you have an internet connection—with or without connecting to your <strong>360fly</strong> camera. You can also choose to make any of your videos public and share your experiences with friends and other <strong>360fly</strong> users. To make changes or edits to your account, just tap the edit profile option at the top of the screen.</p>
                    <p>
                    <strong>Note:</strong> An active internet connection is required to access and view content.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#camera-home-screen"><h3 class="user-guide-title">Camera Home Screen</h3></a>
                <div id="camera-home-screen" class="camera-home-screen collapse user-guide-subsection">
                    
                    <p>Once your smartphone is connected to the camera, the app’s home screen gives you full access to all camera controls, modes, and settings options.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-camera-home-screen.png" class="img-responsive img-full-width" alt="Camera Home Screen Options"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Note: The <strong>AutoPilot</strong> mode on your <strong>360fly</strong> camera sets your app to automatically pan your image to the area of footage that has the highest degree of motion. To use this feature within your camera’s Live View, just tap the <strong>AutoPilot</strong> icon <img src="<?php echo $skinUrl; ?>images/user-guide/autopilot.png" class="user-guide-img" alt="Autopilot"/>. Use the slider located on the left of your display to adjust the sensitivity level.
                    When the camera’s built-in GPS sensor is toggled on, the GPS indicator icon <img src="<?php echo $skinUrl; ?>images/user-guide/GPS.png" class="user-guide-img" alt="GPS"/> will appear on the home screen. Once activated, the GPS indicator will remain gray as the sensor calibrates an initial fix for the camera’s location. Once an active fix is secured, the icon will display a green color, <img src="<?php echo $skinUrl; ?>images/user-guide/GPS-active.png" class="user-guide-img" alt="GPS active"/> indicating that the GPS feature is ready for use. The GPS feature can take up to 2 minutes to generate an initial fix. For best results, use the GPS feature outdoors with a direct line to the sky free of interference from trees or tall buildings.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#recording-video"><h3 class="user-guide-title">Recording Video</h3></a>
                <div id="recording-video" class="recording-video collapse user-guide-subsection">
        
                    <p>Recording 360° videos with the <strong>360fly app</strong> is quick and easy. Simply tap the white record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to start capturing. The center of the capture button will turn red and your camera will simultaneously vibrate while its LED turns from blue to red.</p>
                    <p>
                    As your video records, you’ll notice a second button displaying a camera icon appears near the top of the record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-camera-shutter.png" class="user-guide-img" alt="Camera Shutter"/>. This button represents your camera shutter button, allowing you to capture a still 360° photo with your camera while recording your video.
                    </p>
                    <p>
                    <strong>Note:</strong> Your still photo captures will be stored in your camera’s internal memory as a separate .jpeg file.
                    </p>
                    <p>To stop recording, tap the red record button <img src="<?php echo $skinUrl; ?>images/user-guide/red-record.png" class="user-guide-img" alt="Red Record Button"/>. Your camera will vibrate twice and the LED will switch from solid red to blue, indicating that your recording has ended.</p>
                </div>
        
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#recording-without-app"><h3 class="user-guide-title">Recording Without the App</h3></a>
                <div id="recording-without-app" class="recording-without-app collapse user-guide-subsection">
            
                    <p>If you don’t have access to the <strong>360fly app</strong> on your mobile device, you can record videos directly on your camera. Simply press the <strong>OnePush</strong> button on your camera to launch a 360° recording. Your camera will vibrate and the LED will turn from blue to solid red, indicating that your camera is now recording. To stop recording, press the <strong>OnePush</strong> button again.</p>
                    <p><strong>Note:</strong> The default recording mode for <strong>360fly 4K</strong> videos is pre-set at a resolution of 2880x2880 at 30 frames per second. On this setting, the live viewfinder is disabled during active recording. To enable live-view while recording, you must change your settings to record your 360° 4K video as 2880x2880 pixels at 24 frames per second (fps).</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#pov-mode"><h3 class="user-guide-title">First-Person POV Mode</h3></a>
                <div id="pov-mode" class="pov-mode collapse user-guide-subsection">

                    <p><strong>First-Person POV</strong> mode gives you the power to record standard (non-360°), point of view (POV) videos in a 16:9 aspect ratio, turning your <strong>360fly</strong> into a traditional point-and-shoot action camera. With this mode activated, simply orient or mount your camera in a horizontal position with the lens facing forward and the <strong>OnePush</strong> button centered-facing up.</p>
                    <p>To enter First-Person POV mode, press the revolver wheel <img src="<?php echo $skinUrl; ?>images/user-guide/revolver.png" class="user-guide-img" alt="Revolver Wheel"/> located at the bottom of the screen and select the POV icon <img src="<?php echo $skinUrl; ?>images/user-guide/pov-icon.png" class="user-guide-img" alt="POV Icon"/>. Your application will display that it is set in POV mode above the live-view display on your screen and the live-view area will display a preview in a 16:9 aspect ratio.</p>
                    <p><strong>Note:</strong> The camera’s <strong>OnePush</strong> button represents the top/center of your camera’s viewing angle. When filming in POV mode, use the <strong>OnePush</strong> button to align your shot and achieve the ideal camera angle.
                    </p>
                    <p>To begin a recording in First-Person POV mode, tap the white record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to start capturing. The center of the capture button will turn red and your camera will simultaneously vibrate while its LED turns from blue to red. As your video records, you’ll notice a second button displaying a camera icon appears to the top right of the record button &nbsp;<img src="<?php echo $skinUrl; ?>images/user-guide/record-camera-shutter.png" class="user-guide-img" alt="Camera Shutter"/>. This button represents your camera shutter button, allowing you to capture a still 16:9 POV photo with your camera while recording your video.</p>
                    <p><strong>Note:</strong> When your camera is set into <strong>First-Person POV</strong> mode, you can also start and stop recordings using the on-camera <strong>OnePush</strong> button. POV operation via the <strong>OnePush</strong> button will remain intact until the record setting is changed back to a 360° video mode using the app or the camera is power-cycled.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#time-lapse-mode"><h3 class="user-guide-title">Time-Lapse Mode</h3></a>
                <div id="time-lapse-mode" class="time-lapse-mode collapse user-guide-subsection">
                    
                    <p>Turn hours of activity into dynamic minutes using the camera’s <strong>Time-Lapse</strong> mode. To enter <strong>Time-Lapse</strong> mode, press the revolver wheel <img src="<?php echo $skinUrl; ?>images/user-guide/revolver.png" class="user-guide-img" alt="Revolver Wheel"/> located in the bottom bar of the "camera" home screen and select the <strong>Time-Lapse</strong> icon <img src="<?php echo $skinUrl; ?>images/user-guide/time-lapse.png" class="user-guide-img" alt="Time Lapse Icon"/>. The recording mode you’re in will display at the top of the “Live View” display on your screen.
                    Change the interval between frame captures by adjusting the scroll bar to your desired setting. Your <strong>360fly 4K</strong> offers settings for 0.5, 1, 2, 5, 10, 30, or 60 seconds between frames when in <strong>Time-Lapse</strong> mode. After selecting your desired speed, press the <strong>Time-Lapse</strong> icon again to confirm.
                    </p>
                    <p>To begin a <strong>Time-Lapse</strong> recording, tap the white record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to start capturing. The center of the capture button will turn red and your camera will simultaneously vibrate while its LED turns from blue to red. As the video records, you’ll notice a second button displaying a camera icon appears to the top right of the Record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-camera-shutter.png" class="user-guide-img" alt="Camera Shutter"/>. This button represents your camera shutter button, allowing you to capture a still 360° photo with your camera while recording your video.</p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#60fps-mode"><h3 class="user-guide-title">60 FPS Mode</h3></a>
                <div id="60fps-mode" class="60fps-mode collapse user-guide-subsection">
            
                    <p>Your <strong>360fly 4K</strong> camera allows you to record videos at 60 frames per second with a resolution of 1728x1728 pixels. Perfect for extreme action sequences, this recording option is ideal for creating slow-motion effects when editing your videos and creating action clips.</p>
                    <p>To launch <strong>60 FPS mode</strong>, press the revolver wheel <img src="<?php echo $skinUrl; ?>images/user-guide/revolver.png" class="user-guide-img" alt="Revolver Wheel"/> located at the bottom of the screen and select the video camera icon  <img src="<?php echo $skinUrl; ?>images/user-guide/fps-camera-icon.png" class="user-guide-img" alt="FPS Camera Icon"/>. Your application will display an option to select from each of the 360° recording modes available on the 360fly 4K camera. Select the 1728x1728 @ 60 FPS option to change your record setting.
                    </p>
                    <p>To begin a <strong>60 FPS</strong> recording, tap the white record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to start capturing. The center of the capture button will turn red and your camera will simultaneously vibrate while its LED turns from blue to red. As the video records, you’ll notice a second button displaying a camera icon appears to the top right of the Record button <img src="<?php echo $skinUrl; ?>images/user-guide/record-camera-shutter.png" class="user-guide-img" alt="Camera Shutter"/>. This button represents your camera shutter button, allowing you to capture a still 360° photo with your camera while recording your video.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#still-image-mode"><h3 class="user-guide-title">Still Image Capture</h3></a>
                <div id="still-image-mode" class="still-image-mode collapse user-guide-subsection">
                    
                    <p>Your <strong>360fly 4K</strong> doubles as a still image action camera, allowing you to capture .jpeg photos at an effective resolution of 3456x3456 pixels. Your 360° images can be viewed within the mobile application or via the <strong>360fly desktop Director</strong> app on PC or Mac.</p>
                    <p>To switch your camera to Photo mode, tap the photo icon <img src="<?php echo $skinUrl; ?>images/user-guide/photo-icon.png" class="user-guide-img" alt="Photo Icon"/> at the bottom of the camera home screen. The icon will switch your camera to still photo mode and the application will indicate that it is in Photo mode at the top of the viewfinder screen.</p>
                    <p>Once your shot is lined up, tap the white shutter button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to take a photo. When a photo is captured, the camera LED will flash red once and return back to solid blue, indicating that it is in ready mode. All of your photo files will be stored in your camera’s memory in a .jpeg format.</p>
                    <p><strong>Note:</strong> To exit <strong>Photo</strong> mode, tap the video icon <img src="<?php echo $skinUrl; ?>images/user-guide/fps-camera-icon.png" class="user-guide-img" alt="FPS Camera Icon"/> at the bottom of the screen and your camera will return to video record mode.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#pov-photo-mode"><h3 class="user-guide-title">First-Person POV Photo Mode</h3></a>
                 <div id="pov-photo-mode" class="pov-photo-mode collapse user-guide-subsection">
            
                    <p>The <strong>360fly 4K</strong> can be set to capture standard photos from the First-Person POV perspective.</p>
                    <p>To switch from standard Photo mode to POV mode, tap the revolver wheel <img src="<?php echo $skinUrl; ?>images/user-guide/revolver.png" class="user-guide-img" alt="Revolver Wheel"/> at the bottom of the "camera" home screen. Tap the POV icon <img src="<?php echo $skinUrl; ?>images/user-guide/pov-icon.png" class="user-guide-img" alt="POV Icon"/> and the application will indicate that it is in POV Photo mode at the top of the viewfinder screen.</p>
                    <p>
                    Once your shot is lined up, tap the white shutter button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to take a photo. When a photo is captured, the camera LED will flash red once and return back to solid blue, indicating that it is in ready mode. All of your photo files will be stored in the camera’s memory in a .jpeg format.
                    </p>
                </div>
            
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#camera-burst-mode"><h3 class="user-guide-title">Camera Burst Mode</h3></a>
                <div id="camera-burst-mode" class="camera-burst-mode collapse user-guide-subsection">
                    <p>The <strong>Camera Burst</strong> mode allows you to capture several photographs in quick succession with a single push of the shutter button. Ideal for sports or action photography, Camera Burst mode lets you select the best image from a group of photos or arrange the entire group in a sequence.</p>
                    <p>To switch your camera from standard <strong>Photo</strong> mode to <strong>Camera Burst</strong> mode, press the revolver wheel   <img src="<?php echo $skinUrl; ?>images/user-guide/revolver.png" class="user-guide-img" alt="Revolver Wheel"/> at the bottom of the "camera" home screen. Tap the Camera Burst icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-burst.png" class="user-guide-img" alt="Camera-Burst"/> and the application will indicate that it is set in Camera Burst mode at the top of the live view display on your screen.</p>
                    <p>
                    Pre-set your frame capture intervals by adjusting the slider to your desired setting. The <strong>360fly 4K</strong> offers settings for 3, 5, or 8 captures per second within burst mode. After selecting your desired speed, press the Camera Burst icon to confirm your setting.
                    </p>
                    <p>To capture burst photos, tap the white shutter button <img src="<?php echo $skinUrl; ?>images/user-guide/record-btn.png" class="user-guide-img" alt="White Record Button"/> to take a photo. When a photo is captured, the camera LED will flash red once and return back to solid blue, indicating that it is in ready mode. All of your photo files will be stored in the camera’s memory in a .jpeg format</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#accessing-camera-files"><h3 class="user-guide-title">Accessing Your Camera’s Stored Files</h3></a>
                <div id="accessing-camera-files" class="accessing-camera-files collapse user-guide-subsection">
                    
                    <p>While connected to "camera" home screen, select the “On My Camera” icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-store-icon.png" class="user-guide-img" alt="Camera Storage Icon"/> to view your camera’s storage library. This selection will display all of the video files stored within your camera’s internal memory.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-storage-1.png" class="img-responsive img-full-width" alt="Access Video Storage Files"/>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                        <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-storage-2.png" class="img-responsive img-full-width" alt="Access Photos Storage Files"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">To view a video, simply tap on the thumbnail image of your desired file, and the application will automatically launch your file within its video player. To view your camera’s still image photo captures, tap the “Photos” tab at the top of the screen to switch your library view to display stored photos.</p>
                    <p>
                    To download a video or image directly to your smartphone, simply tap the download icon <img src="<?php echo $skinUrl; ?>images/user-guide/download.png" class="user-guide-img" alt="Download Icon"/>. This will copy your file directly into your phone’s gallery.
                    </p>
                    <p><strong>Note:</strong> Storing your video files onto your phone’s gallery will allow you to play back content without the need to connect your device to your <strong>360fly</strong> camera. Additionally, the application’s video editing tools are only available for content stored in your phone’s gallery.</p>
                    <p>To delete a file, press and hold the thumbnail image. The app will request confirmation that you would like to delete the file before it is permanently removed from the camera’s memory storage.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#video-playback"><h3 class="user-guide-title">Video Playback</h3></a>
                <div id="video-playback" class="video-playback collapse user-guide-subsection">
            
                    <p>Tapping a video thumbnail image within your camera’s library will automatically launch the <strong>360fly</strong> player. Once the video uploads, you can pan the angle of view by swiping across the screen. You can also pan using your device’s built-in gyroscope function by turning your phone in the desired orientation.</p>
                    <p>
                    To zoom in during playback, simply pinch two fingers together on your device’s display until you reach the desired zoom level. To zoom out, expand two fingers across the display and release when you have reached the ideal zoom level.
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-playback-1.png" class="img-responsive img-full-width" alt="Video Playback"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Use the playback bar at the bottom of your screen to pause/restart a video or fast-forward/rewind to a desired point within your video file.</p>
                    <p>You can adjust your video player’s settings by selecting the “Settings” icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display. Under this menu, you have the option to toggle your phone’s gyroscopic panning feature on/off or remove the app’s graphics/overlays from view during playback. The settings menu also features the option to invert your video file, allowing you the ability to switch videos that were recorded upside-down to the correct viewing orientation.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#auto-pilot-mode"><h3 class="user-guide-title">AutoPilot Playback Mode</h3></a>
                <div id="auto-pilot-mode" class="auto-pilot-mode collapse user-guide-subsection">
            
                    <p>The <strong>360fly 4K</strong> includes an <strong>AutoPilot</strong> mode that sets your app to automatically track the area within your 360° footage that has the highest degree of activity, allowing you to simply sit back and enjoy all of the action without the need to interact with your device.</p>
                    <p>To watch your footage using AutoPilot mode, just tap the AutoPilot icon <img src="<?php echo $skinUrl; ?>images/user-guide/autopilot.png" class="user-guide-img" alt="Autopilot"/> located at the top-right portion of your screen. Use the slider located on the left of your display to adjust the sensitivity level of the panning feature.</p>
                </div>
                
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#virtual-reality-mode"><h3 class="user-guide-title">Virtual Reality Goggle Playback</h3></a>
                <div id="virtual-reality-mode" class="virtual-reality-mode collapse user-guide-subsection">
                    
                    <p>Footage captured with your <strong>360fly 4K</strong> camera is designed to work seamlessly with most Google Cardboard VR viewers with just the touch of a button.</p>
                    <p>
                    To watch your footage using a Google Cardboard viewer, just tap the VR viewer icon <img src="<?php echo $skinUrl; ?>images/user-guide/vr-viewer.png" class="user-guide-img" alt="VR Viewer"/> located at the top-right while you’re in the video player screen. Next, simply place your smartphone into your VR headset and immerse yourself inside the incredible world of <strong>360fly 4K</strong> content.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#gen-setting"><h3 class="user-guide-title">General Camera Settings</h3></a>
                <div id="gen-setting" class="gen-setting collapse user-guide-subsection">

                    <p>Adjust your camera controls and general system settings by pressing the <strong>Settings</strong> icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display screen. Under this menu, you can check your camera’s battery life, memory capacity, and make changes to your camera’s name and password. The <strong>Settings</strong> menu also gives you the power to turn off your camera directly from the application.</p>
                    <p>
                    The team at 360fly is always working to provide the latest features and camera software upgrades. Be sure to use the <strong>Settings</strong> menu to periodically check for new updates to your camera’s software and new available features.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#image-tuning"><h3 class="user-guide-title">Image Tuning</h3></a>
                <div id="image-tuning" class="image-tuning collapse user-guide-subsection">

                    <p>The default settings of the <strong>360fly 4K</strong> camera are optimized to deliver the highest quality output within a wide range of environments and lighting conditions. To get the most out of your videos and images, the <strong>360fly 4K</strong> offers advanced options that will allow you to fine-tune your camera’s settings.</p>
                    <p>To access your camera’s fine-tuning options, tap the “Camera Tuning” icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-tuning.png" class="user-guide-img" alt="Camera Tuning Icon"/> located at the bottom right of your display screen.  A set of sliders will appear on screen, giving you options to make adjustments to the following tuning settings:</p>
                    <p><strong>Saturation:</strong> Use the <img src="<?php echo $skinUrl; ?>images/user-guide/camera-saturation.png" class="user-guide-img" alt="Camera Saturation"/> slider to adjust the intensity of the colors captured within your footage.</p>
                    <p><strong>Brightness:</strong> The <img src="<?php echo $skinUrl; ?>images/user-guide/camera-brightness.png" class="user-guide-img" alt="Camera Brightness"/> slider fine-tunes the brightness of the subjects within your image without affecting your camera’s exposure compensation.</p>
                    <p><strong>Exposure:</strong> Adjust the <img src="<?php echo $skinUrl; ?>images/user-guide/camera-exposure.png" class="user-guide-img" alt="Camera Exposure"/> slider to tune your camera image sensor’s sensitivity to light. For brighter environments (e.g., direct sunlight), use a lower exposure setting. Apply an increased exposure setting for darker environments. The slider also allows you to lock in a specific setting and override the camera from automatically adjusting to varying light conditions. The lock remains in place until you manually turn it off or the camera is powered down.</p>
                    <p><strong>Contrast:</strong> Increase the <img src="<?php echo $skinUrl; ?>images/user-guide/camera-contrast.png" class="user-guide-img" alt="Camera Contrast"/> setting to achieve a more vivid picture or lower the setting to deliver a slightly flatter appearance.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#edit-share-content"><h3 class="user-guide-title">Editing and Sharing Content</h3></a>
                <div id="edit-share-content" class="edit-share-content collapse user-guide-subsection">
            
                    <p>If you haven’t already, you will need to download your desired file from your camera library into your smart device’s memory in order to access the <strong>360fly app</strong> editing and sharing features.</p>
                    <p>You can access your camera’s library by selecting the “On My Camera” icon <img src="<?php echo $skinUrl; ?>images/user-guide/camera-store-icon.png" class="user-guide-img" alt="Camera Storage Icon"/> to view your camera’s storage library. After locating your selected video, tap the download icon <img src="<?php echo $skinUrl; ?>images/user-guide/download.png" class="user-guide-img" alt="Download Icon"/> to begin the file transfer process.</p>
                    <p>From the app’s main menu screen, select the “On My Phone” tab <img src="<?php echo $skinUrl; ?>images/user-guide/phone-content.png" class="user-guide-img" alt="View Phone Content"/> to view your stored content within your phone’s memory.</p>
                    <p>Select the video that you would like to edit to launch the file. As the video begins to play, tap the scissor icon <img src="<?php echo $skinUrl; ?>images/user-guide/scissor.png" class="user-guide-img" alt="Scissor"/> to enter into edit mode. There are three tools that enable you to edit and share your 360° footage: <strong>Clip Capture, Watch Me, and Still Capture</strong>.</p>
                    <p><img src="<?php echo $skinUrl; ?>images/user-guide/clip-capture.png" class="user-guide-img" alt="Clip Capture"/><strong> Clip Capture:</strong> Edit and share your clips in their native 360° format. Select this tool to trim your video by picking the parts of your 360° footage that you want to edit, store, and share.</p>
                    <p>After launching <strong>Clip Capture</strong>, select the “Play” icon to start playing the video. At the location that you would like to begin your clip, press the <img src="<?php echo $skinUrl; ?>images/user-guide/clip-capture.png" class="user-guide-img" alt="Clip Capture"/> icon to start capturing. You will notice a green status ring around the icon indicating the time you have left in your capture session. You can record up to five minutes in one session.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-1.png" class="img-responsive img-full-width" alt="Clip Capture 1"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Press the <img src="<?php echo $skinUrl; ?>images/user-guide/clip-capture.png" class="user-guide-img" alt="Clip Capture"/> icon again to stop your clip. You can start and stop multiple times to create one continuous clip with multiple segments.</p>
                    <p>Once you have captured your video, press the “Done” button in the top-right corner and allow a few seconds for your video to process.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-2.png" class="img-responsive img-full-width" alt="Clip Capture 2"/>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-3.png" class="img-responsive img-full-width" alt="Clip Capture 3"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Once your video completely processes, you can click to preview.  In the <strong>Preview</strong> menu you’ll have the ability to add music, color filters, or apply slow and fast motion to the video, to create an awesome, fully immersive 360° clip. See below for more details on adding music, filters, and playback speed adjustment.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-clip-capture-4.png" class="img-responsive img-full-width" alt="Clip Capture 4"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><img src="<?php echo $skinUrl; ?>images/user-guide/watch-me.png" class="user-guide-img" alt="Watch Me"/><strong> Watch Me:</strong> Create a standard 16:9 ratio clip from your original 360° footage. Use the <strong>Watch Me</strong> tool to record your movements as you pan left and right within the video. Wherever you swipe, shift and zoom while capturing in this mode, the resulting output will be cropped and saved as a shareable 16:9 video clip; capturing your unique point of view, ready to share with the world.</p>
                    <p>After launching the <strong>Watch Me</strong> tool, select the “Play” icon to start reviewing your video. At the location that you would like to begin your clip, press the <img src="<?php echo $skinUrl; ?>images/user-guide/watch-me.png" class="user-guide-img" alt="Watch Me"/> icon to start capturing. You’ll notice a green status ring around the icon indicating the time you have left in your capture session. You can record up to 10 minutes in one session.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-watch-me-1.png" class="img-responsive img-full-width" alt="Watch Me 1"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">As your video is recording, move the point of view by panning right, left, up, and down with your finger or by physically moving your device to pan via the gyroscope. Your resulting video clip will capture your point of view by following all of your movements.</p>
                    <p>You can also use the <strong>AutoPilot</strong> mode to automatically adjust the point of view within your clip by selecting the  <img src="<?php echo $skinUrl; ?>images/user-guide/autopilot.png" class="user-guide-img" alt="Autopilot"/> icon in the top right corner of the screen. <strong>AutoPilot</strong> will pan the point of view within your clip by automatically selecting the area within the video that contains the highest degree of activity.</p>
                    <p>When you’re done recording, click on the <img src="<?php echo $skinUrl; ?>images/user-guide/watch-me.png" class="user-guide-img" alt="Watch Me"/> icon to stop recording. You can start and stop multiple times in various locations of your video file to create a single clip.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-watch-me-2.png" class="img-responsive img-full-width" alt="Watch Me 2"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">When complete, click on the “Done” button and allow a few seconds for your video to process. You can now add some special effects like music, slow/fast motion, or change the image filter to apply a unique color scheme to your clip. See below for more details on adding music, filters, and playback speed adjustment.</p>
                    <p><strong>Note:</strong> Your app will remain in <strong>Preview</strong> mode after making adjustments to your clip until you select the “Save” button in the top right corner of your display. Once you have clicked the “Save” button, you’ll be prompted to name your <strong>Watch Me</strong> masterpiece and add a description.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-watch-me-3.png" class="img-responsive img-full-width" alt="Watch Me 3"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">Your Watch Me videos are stored in your Android “Movie” folder and can be viewed on your phone and shared to social media sites in the same manner as any other movie file stored on your phone.</p>
                    <p><strong>Adding Filters:</strong> Tap the <img src="<?php echo $skinUrl; ?>images/user-guide/filters.png" class="user-guide-img" alt="Filters"/> icon to select from an array of filters and color enhancements for your video clip. After selecting, you’ll see a preview of the filter applied over your footage. When you’ve decided on the perfect filter, hit “Apply” to add it, or select the back arrow to return to the original, unfiltered file.</p>
                    <p><strong>Playback Speed Adjustments:</strong> Tap the <img src="<?php echo $skinUrl; ?>images/user-guide/playback-speed-adjust.png" class="user-guide-img" alt="Playback Speed Adjust"/> icon to speed up or slow down a section of your clip. Select just a portion of your edit using the sliders on the playback bar, or select the full clip. You can slide the green bar back and forth to select the section of your video that you wish to adjust. Next, use the speed control bar to increase or decrease the playback speed faster or slower for that selection. As you adjust, you’ll see a preview of the playback speed adjustment applied to your footage. Once you’re happy with your selection, hit “Apply” to add your speed adjustment to your clip or select the back arrow to return to the original file.</p>
                    <p><strong>Adding Soundtracks:</strong> Use the <img src="<?php echo $skinUrl; ?>images/user-guide/add-soundtrack.png" class="user-guide-img" alt="Add SoundTrack"/> option to add a track to your clip by selecting from an array of music options. You can choose between a 50/50 mix of music and your video’s ambient sound or 100% music. Toggle between the two to see which option you like best. Then, simply select the perfect track from our large library of free music and hit “Apply” to add it to your video clip.</p>
                    <p><strong>Note:</strong> Your app will remain in <strong>Preview</strong> mode after making adjustments to your clip until you select the “Save” button in the top-right corner of your display.</p>
                    <p>Once you have clicked the “Save” button, you’ll be prompted to name your masterpiece and add a description. After saving you can elect to share your creation to your favorite social sites.</p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-soundtrack.png" class="img-responsive img-full-width" alt="Add SoundTrack"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20"><strong>Note:</strong> Your device will need an internet connection to upload the video and post to your desired social networking sites.  On some phones, if you are connected to the <strong>360fly app</strong>, you’ll need to disconnect and re-establish your internet service prior to posting.</p>
                    <p><img src="<?php echo $skinUrl; ?>images/user-guide/still-capture-mode.png" class="user-guide-img" alt="Still Capture Mode"/><strong> Still Capture Mode:</strong> Create and export photos from your captured video moments. You’re the photographer—select an area within your video, capture, and then save a still image to your phone’s image gallery.</p>
                    <p>
                    After launching the <strong>Photo Capture</strong> tool, you’ll be prompted to select your desired image ratio. Your app will allow you to select from 360° view, square, 16:9, or panoramic output for your photo capture.
                    </p>
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                            <img src="<?php echo $skinUrl; ?>images/user-guide/android/4k-android-still-capture-1.png" class="img-responsive img-full-width" alt="Still Capture Mode"/>
                        </div>
                    </div>
                    <p class="disp-inline-block mt20">After you have selected your image size, press the “Play” icon to begin playing the video. Pause the video player at the location that you would like to capture your photo and align your image to the desired orientation. You can also pinch to zoom in or out for a closer view within your image prior to capturing your photo.</p>
                    <p>Tap the <img src="<?php echo $skinUrl; ?>images/user-guide/still-capture-mode.png" class="user-guide-img" alt="Still Capture Mode"/> button to capture your shot. You will see a flash and hear a shutter click. Next, select from an array of filters and color enhancements for your new photo capture. Select and preview your desired filter and tap “Apply” to confirm it or click “None” if you do not wish to apply a filter. You can share your photo to any of your connected social media sites or store your image to your phone’s photo library in a .jpeg file format.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#triggered-recording-mode"><h3 class="user-guide-title">Triggered Recording Modes</h3></a>
                <div id="triggered-recording-mode" class="triggered-recording-mode collapse user-guide-subsection">

                    <p>The <strong>360fly 4K</strong> camera features an array of automatic “triggered” recording options. Using this feature, your camera can be set to automatically record when it senses audio, video motion, or movement of the camera via the built-in accelerometer.</p>
                    <p>To activate the triggered recording feature, tap the Settings icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display. Scroll down and locate the triggered recording options within the list of menu items and select your desired triggered recording function by moving the slider to the right.</p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#audio-based-triggered"><h3 class="user-guide-title">Audio-Based Triggered Recording</h3></a>
                <div id="audio-based-triggered" class="audio-based-triggered collapse user-guide-subsection">

                    <p>With this feature enabled, the camera will automatically launch a recording session when the camera senses an audible sound.</p>
                </div>
        
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#video-motion-based-triggered"><h3 class="user-guide-title">Video Motion-Based Triggered Recording</h3></a>
                <div id="video-motion-based-triggered" class="video-motion-based-triggered collapse user-guide-subsection">

                    <p>Within this setting, the camera’s image sensor will react to changes in pixel geography to detect movement. If a moving person or object is detected within the camera’s field of view, a recording session will automatically launch.</p>
                </div>
        
                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#accelerometer-based-triggered"><h3 class="user-guide-title">Accelerometer-Based Triggered Recording</h3></a>
                <div id="accelerometer-based-triggered" class="collapse user-guide-subsection">
            
                    <p>Using the camera’s built-in accelerometer, any physical movement of the device from a still position to a predetermined g-force level will automatically launch a recording session. Recordings captured within this mode also include a built-in 10-second pre-record option. When the accelerometer is activated, the camera will gather the last 10 seconds of video content recorded while the camera was in idle mode and automatically append it to the beginning of the recorded video.</p>
                    <p>
                    For each triggered recording option, you have the ability to set your desired recording period for each event to 30 seconds, 1, 3, 5, 10, 15, 30, 60, or 90 minutes in duration. You also have the option to set the delay/time-out duration for 5, 10, 30, or 60-second intervals between recordings.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#advance-camera-option"><h3 class="user-guide-title">Advanced Camera Operations</h3></a>
                <div id="advance-camera-option" class="advance-camera-option collapse">
            
                    <div class="bt-connectivity user-guide-subsection">
                        <h3>Bluetooth Audio Device Connectivity:</h3>
                        <p>Perfect for indoor recording environments or for real-time narration of action sports videos from the creator’s point of view - this feature allows the use of a Bluetooth microphone or headset in place of the camera’s built-in microphones.
                        To connect your camera to a Bluetooth microphone device, begin by placing your Bluetooth device into pairing mode. Once your Bluetooth device is ready to pair, tap the settings icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display. Scroll down and select the “Pair Bluetooth Microphone” option.
                        </p>
                        <p>Once selected, your app will automatically complete a scan of all of the Bluetooth devices available within range (for best results, place your camera and Bluetooth device 3-5 inches apart during the scan). When the scan is complete, locate and select your Bluetooth device from the list of available devices. When pairing is complete, your app will show that your Bluetooth device is connected within the list of paired devices. Your Bluetooth device will now record the audio for your recordings in place of the camera’s microphones.</p>
                        <p>To un-pair your Bluetooth device from your camera, locate your device within the list of paired devices and select the settings icon adjacent to it <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/>. Select the “Forget” option to release the Bluetooth connection between the camera and your device.</p>
                    </div>
                    <div class="video-chaptering-mode user-guide-subsection">
                        <h3>Video Chaptering Mode:</h3>
                        <p>This file storage option allows for easier file transfer and management for longer-duration video recordings. With chaptering activated, longer recordings are stored in fixed four-minute segments within the camera’s memory.</p>
                        <p>To activate Video Chaptering, tap the settings icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display. Scroll down and locate the “4 Minute Video Chaptering” option. Move the slider to the right to toggle the feature on.</p>
                        <p><strong>Note:</strong> The <strong>360fly desktop Director</strong> software provides advanced editing tools allowing you the to merge video files or create clips from multiple files into a single video output.</p>
                    </div>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#usb-connectivity"><h3 class="user-guide-title">USB Connectivity</h3></a>
                <div id="usb-connectivity" class="collapse">
            
                    <div id="transferring-content" class="user-guide-subsection">
                        <h3>Transferring Content to Your PC:</h3>
                        <p>Your <strong>360fly 4K</strong> camera doubles as a USB mass storage device when connected to your PC or Mac. To access your camera’s stored content, simply connect your USB cable to your computer and place your camera onto its power cradle. Locate your <strong>360fly</strong> camera within your computer’s folder browser to view and transfer your files to your desktop or the desired file folder.</p>
                    </div>
                    <div id="webcam-mode" class="user-guide-subsection">
                        <h3>Webcam Mode:</h3>
                        <p>Use your <strong>360fly 4K</strong> as a connected <strong>webcam</strong> by placing your camera into Webcam mode within your app’s settings menu. When enabled and plugged into a PC’s USB port, the <strong>360fly 4K</strong> camera will transmit a 360° live stream that can be broadcast over Skype, Facetime, GoToMeeting, or any other streaming webcam service that allows you to select an alternate camera as its video output source.</p>
                        <p>To enable Webcam mode, tap the settings icon <img src="<?php echo $skinUrl; ?>images/user-guide/setting-icon.png" class="user-guide-img" alt="Setting Icon"/> located at the top-right of your display. Scroll down and locate the “Webcam” option. Move the slider to the right to toggle the feature on. Next, place your camera onto its power cradle and ensure that the USB cable is plugged into your computer.</p>
                        <p><strong>Note:</strong> We recommend placing your camera into <strong>Webcam</strong> mode <u>before</u> docking the device onto its power cradle to activate the <strong>Webcam</strong> feature.</p>
                    </div>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#troubleshooting"><h3 class="user-guide-title">Troubleshooting</h3></a>
                <div id="troubleshooting" class="collapse user-guide-subsection">
                    
                    <h3>Resetting Your Camera:</h3>
                    <p>On rare occasions, it may become necessary to manually reset your <strong>360fly 4K</strong> camera if it becomes unresponsive.</p>
                    <p>
                    Your camera’s reset button is located inside the mount screw housing.</p>
                    <p>
                    Using a skinny dull pointed object, such as a paper clip, gently press and hold the reset button down for 5 seconds. The camera will vibrate and the LED will flash blue during the reset process. After approximately 30 seconds, the LED will turn solid blue, indicating that your camera is now ready for use.</p>
                    <p><strong>Note:</strong> Resetting will <u>not</u> delete videos stored within your camera’s memory.
                    </p>
                </div>

                <a class="collapsed user-guide-title" data-toggle="collapse" data-target="#tech-support-faq"><h3 class="user-guide-title">Tech Support and FAQs</h3></a>
                <div id="tech-support-faq" class="collapse user-guide-subsection">
                    <p>The 360fly team is always here to help. For all of your support needs, FAQ answers, or to report a bug, please visit us at <a href="https://support.360fly.com/hc/en-us">www.360fly.com/support</a>. Please be sure to check back regularly to learn more about new camera features and firmware upgrades.</p>
                </div>

            </div>
        </div>
    </div>
</div>
<style>
.other-guide-link {font-size: 14px; text-align: right; display: inline-block; position: absolute; right:55px; top: 34px;}
.other-guide-link:hover {color:#999;}

/* -minus */
a > h3.user-guide-title:before {
  font-family: FontAwesome;
  content:"\f068";
  font-size:18px;
  padding-right:10px;
}
/* +plus*/
a.collapsed > h3.user-guide-title:before {
    content:"\f067";
}

@media print {
    .img-full-width {width: 40%;}
    .user-guide-img {width: 15px;}
    .navbar, .header-account-links, footer, .user-guide-print-link-button, h3.user-guide-title:before {display: none;}
    .user-guide-subsection {display: block;}
    body, p, div {font-size: 13px!important;}
    p a:after {content: " (" attr(href) ")"; font-size: 80%;}
    .header+.body-wrapper { padding-top: 0px;}
    .other-guide-link {display: none;}

    .header {display: none;}
    h3.user-guide-title {padding: 5px 9px;}
}
</style>

