<p class="text04">We are available 24 hours x 7 days x 365 days a year.<br/>Contact us via phone, email or social networks</p>

<div class="module_contact">	
	<div class="module-inner">
		<div class="row">
			<div class="col-xs-12 col-sm-7 col-md-4">
				<dl class="by-email">
					<dt class="text06">New customers Questions</dt>
					<dd>
						<a href="mailto:plans@magemojo.com">plans@magemojo.com</a>
					</dd>
					<dt class="text06">Support</dt>
					<dd>
						<a href="mailto:support@magemojo.com">support@magemojo.com</a>
					</dd>
				</dl>
			</div>
			<div class="col-xs-12 col-sm-5 col-md-4">
				<dl class="by-phone">
					<dt class="text06">Phone</dt>
					<dd>
						+1 (800) 217-8142
					</dd>
					<dt class="text06">Fax</dt>
					<dd>
						+1 (917) 565-8991
					</dd>
				</dl>
			</div>
			<div class="col-xs-12 col-md-4">
				<dl class="by-mail">
					<dt class="text06">Mailing Address</dt>
					<dd>
						MageMojo, LLC<br/>
						428 Forbes Avenue<br/>
						Lawyers Building, Suite 2510<br/>
						Pittsburgh, PA 15219
					</dd>
				</dl>
			</div>
		</div>
	</div>
</div>
