<div id="plans">
	<div class="container">
		<h2>All Plans include Free Migration, 24/7 Magento Expert Support, Dedicated IP Addresses and SSH Access</h2>
		<div class="plans">
			<div class="plan">
				<h3>
					<a href="javascript:void(0);" class="specs-toggle collapsed" data-toggle="collapse" data-target=".specs-1">
						Mojo<span>Advanced</span><i class="pe-7s-angle-down">&nbsp;</i>
					</a>
				</h3>
				<div class="specs specs-1 collapse">
					<ul>
						<li>1 CPU</li>
						<li>4gb Memory</li>
						<li>50gb SSD Raid Disk Space</li>
						<li>250 gb Bandwidth</li>
						<li>Dedicated server</li>
					</ul>
				</div>
				<div class="actions">
					<span class="price">$58/mo</span>
					<a href="<?php echo $this->getUrl('checkout/cart');?>" class="btn-cart"><i class="pe-7s-cart">&nbsp;</i></a>
				</div>
			</div>
			<div class="plan most-popular">
				<h3>
					<a href="javascript:void(0);" class="specs-toggle collapsed" data-toggle="collapse" data-target=".specs-2">
						Mojo<span>Pro</span><i class="fa fa-star">&nbsp;</i><i class="pe-7s-angle-down">&nbsp;</i>
					</a>
				</h3>
				<div class="specs specs-2 collapse">
					<div class="badge">Most popular</div>
					<ul>
						<li>2 CPU</li>
						<li>8gb Memory</li>
						<li>100gb SSD Raid Disk Space</li>
						<li>375 gb Bandwidth</li>
						<li>Dedicated server</li>
					</ul>
				</div>
				<div class="actions">
					<span class="price">$98/mo</span>
					<a href="<?php echo $this->getUrl('checkout/cart');?>" class="btn-cart"><i class="pe-7s-cart">&nbsp;</i></a>
				</div>
			</div>
			<div class="plan">
				<h3>
					<a href="javascript:void(0);" class="specs-toggle collapsed" data-toggle="collapse" data-target=".specs-3">
						Mojo<span>Turbo</span><i class="pe-7s-angle-down">&nbsp;</i>
					</a>
				</h3>
				<div class="specs specs-3 collapse">
					<ul>
						<li>4 CPU</li>
						<li>16gb Memory</li>
						<li>200gb SSD Raid Disk Space</li>
						<li>1000 gb Bandwidth</li>
						<li>Dedicated server</li>
					</ul>
				</div>
				<div class="actions">
					<span class="price">$198/mo</span>
					<a href="<?php echo $this->getUrl('checkout/cart');?>" class="btn-cart"><i class="pe-7s-cart">&nbsp;</i></a>
				</div>
			</div>
		</div>
	
		<div class="icons">
			<div class="icons-businesses">
				<div class="icon-custom-small-business icon-left">
					Just<br/>Launched
				</div>
				<div class="arrow">&nbsp;<span class="fa fa-long-arrow-right"></span></div>
				<div class="icon-custom-big-business icon-right">
					Growing<br/>Business
				</div>
			</div>
		</div>
	</div>

	<div class="view-all">
		<a href="#" class="btn btn-default">View all plans</a>
	</div>
</div>