<div id="testimonials" class="featured hidden-xs">
	<div class="container">
		<h2 class="text01">Our clients say</h2>
		<div class="carousel slide" data-ride="carousel" data-wrap="false">
			<div class="module-testimonials carousel-inner" role="listbox">

				<div class="testimonial item active">
					<div class="highlight"><a href="http://www.shopperapproved.com/reviews/magemojo.com/page-0.html" target="_blank">Traffic spike from a Super Bowl commercial</a></div>
					<div class="quote">
						<div class="detail">
							<div class="avatar">
								<img src="<?php echo $this->getSkinUrl('images/testimonials/one-world-direct.png'); ?>" alt="One World Direct" />
							</div>
							<div class="name">Bob Fulkerson</div>
							<div class="company">One World Direct</div>
						</div>
						<div class="blockquote">
							<blockquote>
								<a href="testimonials.html">"It was an amazing thing to watch the traffic go from our normal site traffic to 100 times that in a space of one minute... The average page load time during the peak traffic was about 2 seconds..."</a>
							</blockquote>
						</div>
					</div>
				</div>

				<div class="testimonial item">
					<div class="highlight"><a href="http://www.shopperapproved.com/reviews/magemojo.com/page-0.html" target="_blank">Their support is extremely knowledgeable</a></div>
					<div class="quote">
						<div class="detail">
							<div class="avatar">
								<img src="<?php echo $this->getSkinUrl('images/testimonials/mastering-magento.jpg'); ?>" alt="Mastering Magento" />
							</div>
							<div class="name">Bret Williams</div>
							<div class="company">Author - Packt Publishing's Mastering Magento</div>
						</div>
						<div class="blockquote">
							<blockquote>
								<a href="testimonials.html">"After suffering the trials of using other hosting providers who said they supported Magento installation, we discovered MageMojo. We have been nothing short of amazed at the performance of our stores..."</a>
							</blockquote>
						</div>
					</div>
				</div>

			</div>
			<div class="slider-controls">
				<a class="left" href=".carousel" role="button" data-slide="prev">
				    <span class="pe-7s-angle-left" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				</a>
				<a class="right" href=".carousel" role="button" data-slide="next">
					<span class="pe-7s-angle-right" aria-hidden="true"></span>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
	</div>
</div>