<p class="text04">We are the only hosting provider that exclusively hosts Magento sites and we have highly knowledgeable support staff experienced with Magento all with an unprecedented Service Level Agreement.</p>

<div class="cms-hostings">	
	<div class="module_service">
		<div class="heading">
			<h2>Facility</h2>
		</div>
		<div class="module-inner">
			<div class="row">
				<div class="col-xs-12 col-sm-5 col-sm-push-7 service-img">
					<div class="image-wrapper"><img src="http://placehold.it/430x300"></div>
				</div>
				<div class="col-xs-12 col-sm-7 col-sm-pull-5 copy">
					<ul class="list-circle">
						<li><span class="fa fa-circle">&nbsp;</span>Colocated in state of the art carrier neutral datacenter with direct connections to end user networks</li>
						<li><span class="fa fa-circle">&nbsp;</span>N+1 redundant power, hvac and sas 70 type II security protection.</li>
						<li><span class="fa fa-circle">&nbsp;</span>Core network AS53902 running Cisco’s Performance Routing technology </li>
						<li><span class="fa fa-circle">&nbsp;</span>Built to ensure lowest latency path to your customers</li>
						<li><span class="fa fa-circle">&nbsp;</span>Extreme measures are taken to provide 100% up time for your sites while providing the highest level of performance</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="module_service">
		<div class="heading">
			<h2>Support</h2>
		</div>
		<div class="module-inner">
			<div class="row">
				<div class="col-xs-12 col-sm-5 service-img">
					<div class="image-wrapper"><img src="http://placehold.it/430x300"></div>
				</div>
				<div class="col-xs-12 col-sm-7 copy">
					<ul class="list-circle">
						<li><span class="fa fa-circle">&nbsp;</span>Managed 24/7 Magento expert support</li>
						<li><span class="fa fa-circle">&nbsp;</span>15 minute support response time</li>
						<li><span class="fa fa-circle">&nbsp;</span>Proactive performance monitoring and tuning</li>
						<li><span class="fa fa-circle">&nbsp;</span>Technicians are Magento experts</li>
						<li><span class="fa fa-circle">&nbsp;</span>Free Migration</li>
					</ul>
					<p>
						<a href="sla.html" class="btn btn-default">View SLA</a>
					</p>
				</div>
			</div>
		</div>
	</div>

	<div class="module_service">
		<div class="heading">
			<h2>Servers</h2>
		</div>
		<div class="module-inner">
			<div class="row">
				<div class="col-xs-12 col-sm-5 col-sm-push-7 service-img">
					<div class="image-wrapper"><img src="http://placehold.it/430x300"></div>
				</div>
				<div class="col-xs-12 col-sm-7 col-sm-pull-5 copy">
					<ul class="list-circle">
						<li><span class="fa fa-circle">&nbsp;</span>Intel® Xeon® E5-2600v3 2.6 Ghz Cpu Core</li>
						<li><span class="fa fa-circle">&nbsp;</span>Memory is DDR3 1600Mhz</li>
						<li><span class="fa fa-circle">&nbsp;</span>Storage SSD</li>
						<li><span class="fa fa-circle">&nbsp;</span>Bandwidth 2xGigE</li>
						<li><span class="fa fa-circle">&nbsp;</span>Nginx or Apache, PHP-FPM, Memcache, Redis, Percona, Varnish, HHVM</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>