<div class="module_kbase">
	<div class="module-inner">
		<div class="row">
			<div class="col-xs-12 col-sm-6">
				<div class="box-info box-services">
					<div class="service-img">
						<div class="image-wrapper"><img src="<?php echo $this->getSkinUrl('images/support.jpg'); ?>"></div>
					</div>
					<h2 class="text05">Services</h2>
					<ul class="list-circle">
						<li><span class="fa fa-circle">&nbsp;</span>Managed 24/7 Magento expert support</li>
						<li><span class="fa fa-circle">&nbsp;</span>15 minute support response time</li>
						<li><span class="fa fa-circle">&nbsp;</span>Proactive performance monitoring and tuning</li>
						<li><span class="fa fa-circle">&nbsp;</span>Technicians are Magento experts</li>
						<li><span class="fa fa-circle">&nbsp;</span>Free Migration</li>
					</ul>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6">
				<div class="box-info box-kbase">
					<h2 class="text05">Knowledge Base</h2>
					<div class="kbase-main-search">
					    <p class="kbase-block-title">Have a question? Search our knowledge base</p>
					        <form class="aui aui-dd-parent" name="livesearchForm" method="POST" action="http://10.10.106.66:8090/dosearchsite.action">
					            <fieldset class="search-macro-fields">
					                <input class="form-control" type="text" name="queryString" autocomplete="off" placeholder="Search for a solution">
									<button class="btn btn-primary form-button" title="Search" type="submit">
									<span class="pe-7s-search"></span><span class="text">Search</span>
									</button>
					                 <input type="hidden" name="where" value="CK">
					                <input type="hidden" name="additional" value="page excerpt">
					                <input type="hidden" name="labels" value="">
					                <input type="hidden" name="contentType" value="page">
					            </fieldset>
   						 </form>
					    <p class="kbase-block-title"><a href="http://10.10.106.66:8090/display/CK/Magemojo+Hosting+Knowledge+Base"Browse Knowledge Base</a></p>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>