<div id="testimonials">
	<div class="module-testimonials">
		<div class="testimonial">
			<div class="quote">
				<div class="detail">
					<div class="avatar">
						<img src="<?php echo $this->getSkinUrl('images/testimonials/one-world-direct.png'); ?>" alt="One World Direct" />
					</div>
					<div class="name">Bob Fulkerson</div>
					<div class="company">One World Direct</div>
					<a href="javascript:void(0);" class="quote-toggle" data-toggle="collapse" data-target=".blockquote-1"><span class="pe-7s-angle-down">&nbsp;</span></a>
				</div>
				<div class="blockquote blockquote-1 collapse in">
					<blockquote>
						<p>
							We had a major client come to us and let us know they wanted to update the look of their Magento site. This isn't that uncommon and we wanted to take the opportunity to look at other hosting options. We had been searching around for a better Magento hosting solution for some time.</p>
						<p>
							We had narrowed it down to a few when the client sprung on us that not only do they want an entire redesign but they will have a commercial during the "Big Game" - you know the one that everyone watches for the commercials! This wasn't just a local commercial, either. It was nation wide. This was in less than 30 days. Our list of hosting solutions for Magento quickly came down to MageMojo.
						</p>
						<p class="quote-big"><q>The solution they provided worked exactly as planned</q></p>
						<p>
							I have to say they went above and beyond any expectations we had set for them. The support we received during the process was the best I have ever seen. They put as much effort into it as any member of our own team would have. The solution they provided us to handle the kind of spike traffic you get from this kind of exposure worked exactly as planned.
						</p>
						<p class="quote-big"><q>The average page load time during the peak traffic was about 2 seconds</q></p>
						<p>
							To top it off we didn't have a finalized server configuration decision from the client until 8 days before the day and they pulled it off flawlessly. It was an amazing thing to watch the traffic go from our normal site traffic to 100 times that in a space of one minute and see the site just click along as if nothing was going on. The average page load time during the peak traffic was about 2 seconds which if you know Magento is amazing!
						</p>
						<p class="quote-big">
							<q>The right team for the Super Bowl ad</q>
						</p>
						<p>
							I can not say enough good things about MageMojo. The best testimony I can give is they conducted themselves like their jobs depended on getting this right. When any other host would have told us to take a hike they put in the long hours and got it done. Simply put Magemojo was the right team for the "Big Game" ad. I am now a card carrying believer in them and we are moving all of our Magento hosting to their services.
						</p>
					</blockquote>
				</div>
			</div>
		</div>

		<div class="testimonial">
			<div class="quote">
				<div class="detail">
					<div class="avatar">
						<img src="<?php echo $this->getSkinUrl('images/testimonials/mastering-magento.jpg'); ?>" alt="Mastering Magento" />
					</div>
					<div class="name">Bret Williams</div>
					<div class="company">Author - Packt Publishing's Mastering Magento</div>
					<a href="javascript:void(0);" class="quote-toggle collapsed" data-toggle="collapse" data-target=".blockquote-2"><span class="pe-7s-angle-down">&nbsp;</span></a>
				</div>
				<div class="blockquote blockquote-2 collapse">
					<blockquote>
						<p>After suffering the trials of using other hosting providers who said they supported Magento installation, we discovered MageMojo. We have been nothing short of amazed at the performance of our stores.</p>
						<p class="quote-big">
							<q>Their support is both very responsive and extremely knowledgeable</q>
						</p>
						<p>Furthermore, their support is both very responsive and extremely knowledgeable. As a company that teaches niche marketing to its clients, it is encouraging to find a hosting provider who not only focuses on the niche of Magento-powered stores, but excels in the delivery to its market</p>
					</blockquote>
				</div>
			</div>
		</div>

		<div class="testimonial">
			<div class="quote">
				<div class="detail">
					<div class="avatar">
						<img src="<?php echo $this->getSkinUrl('images/testimonials/homeperfect.png'); ?>" alt="Home Perfect" />
					</div>
					<div class="name">Maier Bianchi</div>
					<div class="company">Homeperfect.com</div>
					<a href="javascript:void(0);" class="quote-toggle collapsed" data-toggle="collapse" data-target=".blockquote-3"><span class="pe-7s-angle-down">&nbsp;</span></a>
				</div>
				<div class="blockquote blockquote-3 collapse">
					<blockquote>
						<p>We made the switch to MageMojo from one of the main dedicated hosting companies that are Magento Platinum Hosting Partners. We were looking for a more hands on hosting experience.</p>
						<p class="quote-big">
							<q>We needed a host that understood quality builds for Magento</q>
						</p>
						<p>It was not enough that our hosts were experts at quality Linux builds, we needed a host that understood quality builds for Magento as well as supporting the software ecosystem. Magemojo went above and beyond to ensure our transition was smooth and efficient. The real difference maker was that when minor issues come up, we didn't have to sit there waiting for days for the issues to be resolved by Magento support but rather the friendly staff at Magemojo was willing to step in and get their hands dirty and make sure the problems were solved right away.</p>
						<p class="quote-big">
							<q>They get you up and running as fast as possible</q>
						</p>
						<p>We have also been able to cut costs which is definitely important in this current economic landscape. All in all I would recommend choosing MageMojo for any Magento project going forward. They are willing to not only provide you with functional hosting at a low cost, but also install, configure and get you up and running as fast as possible with new deployments.</p>
					</blockquote>
				</div>
			</div>
		</div>
	</div>
</div>