<div class="padder">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="page-head">
	    <h3><?php echo $this->__('My Payment Profiles') ?></h3>
	</div>

	<div class="box simple_contact">
	<form id="rebill_manage_edit" name="rebill_manage_edit" action="/magento/rebill/manage/save" method="post">
	<script type="text/javascript">
	//< ![CDATA[
	var customForm = new VarienForm('rebill_manage_edit');
	//]]>
	</script>
	<input type="hidden" name="id" value="<?php echo  $this->getRequest()->getParam('id', null) ?>">
	    <fieldset class="group-select">
	        <h4 class="legend">Update Payment Profile</h4>
	        <p></p>

<div class="payment-methods">


        <dl id="checkout-payment-method-load">
                        <dd id="container_payment_method_authorizenetcim" class="payment-method" style="">
                <fieldset class="form-list">
        <ul id="payment_form_authorizenetcim" style="">
        <li>
            <div class="input-box">
                <label for="authorizenetcim_cc_owner">Name on Card <span class="required">*</span></label><br>
                <input type="text" title="Name on Card" class="required-entry input-text" id="authorizenetcim_cc_owner" name="payment[cc_owner]" value="">
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="authorizenetcim_cc_type">Credit Card Type <span class="required">*</span></label><br>
                <select id="authorizenetcim_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                    <option value="">--Please Select--</option>
					<option value="AE">American Express</option>
                    <option value="VI">Visa</option>
                    <option value="MC">MasterCard</option>
                    <option value="DI">Discover</option>
                </select>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="authorizenetcim_cc_number">Credit Card Number <span class="required">*</span></label><br>
                <input type="text" id="authorizenetcim_cc_number" name="payment[cc_number]" title="Credit Card Number" class="input-text validate-cc-number validate-cc-type" value="">
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="authorizenetcim_expiration">Expiration Date <span class="required">*</span></label><br>
                <div class="v-fix">
	                <select id="authorizenetcim_expiration" style="width:145px;" name="payment[cc_exp_month]" class="required-entry validate-cc-exp">
	                	<option value="">Month</option>
	                    <option value="1">01 - January</option>
	                    <option value="2">02 - February</option>
	                    <option value="3">03 - March</option>
	                    <option value="4">04 - April</option>
	                    <option value="5">05 - May</option>
	                    <option value="6">06 - June</option>
	                    <option value="7">07 - July</option>
	                    <option value="8">08 - August</option>
	                    <option value="9">09 - September</option>
	                    <option value="10">10 - October</option>
	                    <option value="11">11 - November</option>
	                    <option value="12">12 - December</option>
	                </select>
                </div>
                <div class="v-fix" style="padding-left:6px;">
                	<select id="authorizenetcim_expiration_yr" style="width:105px;" name="payment[cc_exp_year]" class="required-entry">
                    	<option value="">Year</option>
                        <?php
                        $curyear = date('Y');
			for ($i=$curyear; $i<=($curyear+10); $i++) {
                          print '<option value="'.$i.'">'.$i.'</option>';
                        }
		        ?>

                	</select>
                </div>
            </div>
        </li>
                <li>
            <div class="input-box">
                <label for="authorizenetcim_cc_cid">Card Verification Number <span class="required">*</span></label><br>
                <div class="v-fix"><input type="text" title="Card Verification Number" class="required-entry input-text validate-cc-cvn" id="authorizenetcim_cc_cid" name="payment[cc_cid]" style="width:3em;" value=""></div>
            </div>
        </li>
            </ul>
</fieldset>            </dd>
                            </dl>
    </div>


	    </fieldset>
	        <p style="margin-left:25px;" class="required">* Required Fields</p>
	        <input style="margin-left:25px;" type="image" src="<?php echo $this->getSkinUrl('images/btn_submit.gif') ?>" alt="<?php echo $this->__('Submit') ?>"/>
	</form>
	</div>
</div>
