<script type='text/javascript' src='https://www.google.com/jsapi'></script>
<div class="padder">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->getCollection()->count() > 0) { ?>

<div class="page-head">
    <h3><?php echo $this->__('My Services') ?></h3>
</div>

    <ul style="list-style-type: disc;">
    <li><b>To update your payment method select a different payment profile from the drop down under Billing Profiles.</b></li>
    <li><b>To cancel your service click Request Cancelation for the service you wish to cancel. Cancellations are processed the following day.</b></li>
    </ul>

        <div class="content">
            <table width="100%">

                <?php
                  $rebillarray = array();
                  foreach ($this->getCollection() as $rebill) {
                        $rebillarray[count($rebillarray)] = $rebill->getRebillId();
			$profiles = Mage::getModel('authorizenetcim/profile')->getCollection()->addFieldToFilter('customer_id', $rebill->getCustomerId())->load();
                	$servers = Mage::getModel('noc/server')->getCollection()->addFieldToFilter('order_increment_id', $rebill->getOrderIncrementId());
                	$servernames = '';
                	foreach ($servers as $server)
                	{
                		$servernames = $servernames . '<a href="/magento/noc/server/index/">' . $server->getHostName() . '</a>, ';
                	}
                	$servernames = rtrim($servernames, ', ');
                ?>

		            <thead style="font-weight:bold">
		            	<tr>
		            		<td>Service</td>
		            		<td style="padding-right:5px;">Last&nbsp;Billing</td>

		            		<?php if ($rebill->getCanceled() == 0) { ?>
		            		<td style="padding-right:5px;">Next&nbsp;Billing</td>
		            		<td style="padding-right:5px;">Billing&nbsp;Profile</td>
		            		<?php } ?>

		            		<td style="padding-right:5px;">Status</td>

		            		<?php if ($rebill->getCanceled() == 0) { ?>
		            		<td>Action</td>
		            		<?php } ?>
		            	</tr>
		            </thead>
					<tbody>
                   <tr>
	            		<?php
                                if ($rebill->getSku() == 'mods-disk-ssd') {
                                	print '<td style="padding-right:5px;">'.$rebill->getDiskSize().'GB Additional SSD Space</td>';
				} else if ($rebill->getSku() == 'mods-disk-sas') {
					print '<td style="padding-right:5px;">'.$rebill->getDiskSize().'GB Additional SSD Space</td>';
				} else if ($rebill->getSku() == 'mods-disk-sata') {
                                        print '<td style="padding-right:5px;">'.$rebill->getDiskSize().'GB Additional SATA Space</td>';
                                } else {
                                	print '<td style="padding-right:5px;">'.$servernames.'</td>';
                                }
                                ?>
	            		<td><?php echo $rebill->getDateLast() ?></td>

	            		<?php if ($rebill->getCanceled() == 0) { ?>

	            		<td style="padding-right:5px;"><?php echo $rebill->getDateNext() ?></td>
				<td style="padding-right:5px;">
                                <select id="rebill_<?php print $rebill->getRebillId(); ?>" onChange="updaterebill(<?php print $rebill->getRebillId(); ?>)">
                                <option value="">None</option>
                                <?php
                                foreach($profiles as $profile) {
                                  $card = $profile->getCardType().' '.$profile->getLastFour().' '.$profile->getExpMonth().'/'.$profile->getExpYear();
                                  if ($profile->getAuthorizenetcimprofileId() == $rebill->getAuthorizenetcimprofileId()) {
                                    print '<option value="'.$profile->getAuthorizenetcimprofileId().'" selected>'.$card.'</option>';
                                  } else {
                                    print '<option value="'.$profile->getAuthorizenetcimprofileId().'">'.$card.'</option>';
                                  }
                                }
                                ?>
                                </select>
                                </td>

	            		<?php } ?>

	            		<td style="padding-right:5px;"><?php if ($rebill->getCanceled() == 0) { echo "Active"; } else { echo "Canceled"; } ?></td>

						<?php if ($rebill->getCanceled() == 0) { ?>
                   		<td style="padding-right:5px;"><a href="#" onclick="return cancelProfile('<?php echo $rebill->getId()?>');">Request&nbsp;Cancelation</a></td>
<script type="text/javascript">
    function updaterebill(rebillId) {
      profileId = document.getElementById("rebill_" + rebillId).options[document.getElementById("rebill_" + rebillId).selectedIndex].value;
      window.location="/magento/rebill/manage/update/id/" + rebillId + "/profileid/" + profileId;
    }
    function cancelProfile(profileId) {
        if(confirm('Are you sure you want to cancel this service?')) {
            reason = prompt('Please indicate the reason for cancelation.');
            window.location='/magento/rebill/manage/cancel/id/' + profileId + '/reason/' + encodeURIComponent(reason);

        }
        return false;
    }
</script>
						<?php } ?>
                   	</tr>

                   	<tr>
                   		<td colspan="8" style="height:20px;"></td>
                   	</tr>
                	</tbody>
                <?php } ?>
            </tbody>
            </table>

        </div>
<div class="page-head">
    <h3><?php echo $this->__('My Payment Profiles') ?></h3>
</div>


    <ul style="list-style-type: disc;">
    <li><b>To remove a payment method click on Delete for the method you wish to remove.</b></li>
    <li><b>To add a payment method click Add Additional Payment Method.</b></li>
    </ul>

    <div class="content">
            <table width="100%">
            <thead style="font-weight:bold">
            <tr>
            <td>Name on Card</td>
            <td>Type</td>
            <td>Last Four</td>
            <td>Expires</td>
            <td>Action</td>
            </tr>
            </thead>
    <?php
    $rebill = $this->getCollection()->getFirstItem();
    $profiles = Mage::getModel('authorizenetcim/profile')->getCollection()->addFieldToFilter('customer_id', $rebill->getCustomerId())->load();
    foreach($profiles as $profile) {
      #print_r($profile);
      print '<tr>';
      print '<td>'.$profile->getNameOnCard().'</td>';
      print '<td>'.$profile->getCardType().'</td>';
      print '<td>'.$profile->getLastFour().'</td>';
      print '<td>'.$profile->getExpMonth().'/'.$profile->getExpYear().'</td>';
      print '<td><a href="/magento/rebill/manage/delete/id/'.$profile->getAuthorizenetcimprofileId().'">Delete</td>';
      print '</tr>';
    }
    ?>
    <tr>
    <td colspan="5"><a href="/magento/rebill/manage/edit/">Add Payment Method</td>
    </tr>
    </table>
    </div>


<?php } else { ?>

    <p><?php echo $this->__('You have not signed up for hosting yet.') ?></p>

    <?php }  ?>


<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="f-left">&laquo; <?php echo $this->__('Back') ?></a>
</div>
</div>
<script language="javascript">
<!--
paymentmissing=false;
<?php
foreach ($rebillarray as $rebill) {
  print "if (document.getElementById('rebill_".$rebill."').selectedIndex == 0) {
";
  print "  paymentmissing=true;";
  print "}";
}
?>
if (paymentmissing) {
  alert('You are missing payment profiles for one or more of your services.');
}
//-->
</script>
