<?php
/**
 * @brief Defines the html for show Payment Information Block on Frontend (Tokenized Post)
 * @category Magento CardConnect Payment Module
 * @author CardConnect
 * @copyright Portions copyright 2014 CardConnect
 * @copyright Portions copyright Magento 2014
 * @license GPL v2, please see LICENSE.txt
 * @access public
 * @version $Id: $
 *
 * */
/**
  Magento
 *
  NOTICE OF LICENSE
 *
  This source file is subject to the Open Software License (OSL 3.0)
  that is bundled with this package in the file LICENSE.txt.
  It is also available through the world-wide-web at this URL:
  http://opensource.org/licenses/osl-3.0.php
  If you did not receive a copy of the license and are unable to
  obtain it through the world-wide-web, please send an email
  to license@magentocommerce.com so we can send you a copy immediately.
 *
  @category Cardconnect
  @package Cardconnect_Ccgateway
  @copyright Copyright (c) 2014 CardConnect (http://www.cardconnect.com)
  @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
if(Mage::getModel('ccgateway/standard')->getConfigData('active')==1){
?>
<style>
#fade{ width:100%; height:100%; background:rgba(0,0,0,0.1); position:fixed; top:0px; left:0px; display:none;}
.loader{position:absolute; top:80%; left:50%;}

.input-text {
    -moz-appearance: none;
    border-radius: 2px;
    border: 1px solid #C0C0C0;
    background: #FFF none repeat scroll 0% 0%;
    font-size: 15px;
    font-weight:300;
    width: 365px;
    font-family: "Helvetica Neue",Verdana,Arial,sans-serif;
}

    </style>
    <fieldset class="form-list">
        <?php
        $_code = $this->getMethodCode();
        $isTestMode = $this->isTransactionModeTest();
        $siteName = Mage::helper('ccgateway')->getSiteName();
        $quote = Mage::getSingleton('checkout/session')->getQuote();
        $billingAddress = $quote->getBillingAddress();

	$requestUrl = Mage::getUrl('ccgateway/payment/getprofiledata',array('_secure'=>true));
    $billingStreet = $billingAddress->getStreet(1);
    $billingCity = $billingAddress->getCity();
    $billingRegion = $billingAddress->getRegion();
    $billingCountry = $billingAddress->getCountryId();
    $billingPostCode = $billingAddress->getPostcode();
    $billingTelephone = $billingAddress->getTelephone();
    $errorLogURL = Mage::getUrl('ccgateway/log/logfrontenderrors',array('_secure'=>true));

    ?>

    <ul id="payment_form_<?php echo $_code ?>" style="display:none">

        <?php if ($this->getCheckoutType() == "payment_page") { ?>
            <li>
                <?php echo Mage::helper('ccgateway')->__('You will be redirected to CardConnect website when you place an order.') ?>
            </li>
        <?php } else { ?>


            <?php
            if ($this->hasCCProfile() == true) {
                $response = $this->getDefaultCCProfileId();

				if($response !="CardConnect_Error"){
                    if(isset($response[0]['token'])){
                        $maskedToken = substr_replace($response[0]['token'], str_repeat("*", 12), 0, 12);

                    }else{
                        $maskedToken = "";
                    }
                ?>

                <li class="wide">
                    <label for="<?php echo $_code ?>_cc_profile_name" class="required"><em>*</em><?php echo $this->__('Choose Your Card For Payment') ?></label>
                    <div class="input-box">
                        <select id="payment[profile_name]" name="payment[profile_name]" onchange="javascript:return callGetProfileWebserviceController(<?php echo '\'' . $requestUrl . '\''; ?>, this.value, <?php echo '\'' . $errorLogURL . '\''; ?> );"  title="<?php echo $this->__('Select Your Card') ?>" class="required-entry validate-select">
                            <option value=""><?php echo $this->__('--Please Select--') ?></option>
                            <?php foreach ($this->getCCProfileName() as $data): ?>
                                <option value="<?php echo $data->getData('CC_PROFILEID'); ?>"
                                <?php $profileId = (isset($response[0]['profileid'])) ? $response[0]['profileid'] : null;
                                if ($data->getData('CC_PROFILEID') === $profileId) { ?>
                                            selected="selected"
                                        <?php } ?> >
                                            <?php echo $data->getData('CC_CARD_NAME'); ?>
                                </option>
                            <?php endforeach ?>
                            <option value="<?php echo "Checkout with new card"; ?>" ><?php echo "Checkout with new card"; ?></option>
                        </select>

                    </div>
                </li>
            <?php }else{ ?>
				<ul class="messages">
					<li class="error-msg"><ul><li><span>Unable to perform requested action, please contact customer service.</span></li></ul></li>
				</ul>
			<?php 	} } ?>

            <div id="payment_info" <?php if ($this->hasCCProfile() == true) { ?> style="display: none;" <?php } ?> >
                <li>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]"
                               value="<?php echo $name = (isset($response[0]['name'])) ? $response[0]['name'] : null;  ?>"  />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_type" class="required validate-cc-type "><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
                    <div class="input-box" >


                        <select readonly id="ccgateway_cc_type" name="payment[cc_type]"  title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-select" onchange="resetcardinfo();">
                            <option value=""><?php echo $this->__('--Please Select--') ?></option>
                            <?php $accttype = (isset($response[0]['accttype'])) ? $response[0]['accttype'] : null;
                            foreach ($this->getCcTypes() as $ccType): ?>
                                <option value="<?php echo $ccType['value']; ?>"<?php if ($ccType['value'] == $accttype ): ?> selected="selected"<?php endif ?> ><?php echo $ccType['label']; ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </li>
            </div>

            <li <?php if($response == "CardConnect_Error"){?> style="display: none;" <?php } ?>>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <?php if ($this->hasCCProfile() == true) { ?>
                        <label id="cc_number_label" for="<?php echo $_code ?>_cc_number" class="input-text required-entry"><?php echo $maskedToken; ?></label>

                            <input type="text" hidden onchange="valid_credit_card(value , '<?php echo $isTestMode; ?>', '<?php echo $siteName; ?>', '<?php echo $errorLogURL; ?>' , '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>', '<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/cart') ?>')"  onkeypress="javascript:return validate(event, 'ccgateway_cc_number_org'); blockNonNumbers(this, event, false, false)" id="ccgateway_cc_number_org" name="payment[cc_number_org]" title="<?php echo $this->__('Credit Card Number') ?>" maxlength="16"  class="input-text required-entry" value="<?php echo $maskedToken; ?>"  />

                        <?php } else { ?>
                        <label id="cc_number_label" hidden for="<?php echo $_code ?>_cc_number" class="input-text required-entry"><?php echo $maskedToken; ?></label>

                        <input type="text" onchange="valid_credit_card(value , '<?php echo $isTestMode; ?>', '<?php echo $siteName; ?>', '<?php echo $errorLogURL; ?>' , '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>', '<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/cart') ?>', 'guest')"  onkeypress="javascript:return validate(event, 'ccgateway_cc_number_org'); blockNonNumbers(this, event, false, false)" id="ccgateway_cc_number_org" name="payment[cc_number_org]" title="<?php echo $this->__('Credit Card Number') ?>" maxlength="16"  class="input-text required-entry" value="<?php echo $maskedToken; ?>"  />

                    <?php } ?>
                    <input type="text" hidden  id="ccgateway_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text"
                           value="<?php echo $token = (isset($response[0]['token'])) ? $response[0]['token'] : null; ?>" />
                    <div class="validation-advice" id="testError" style="display: none;"></div>
                </div>

            </li>
            <li><div id="response"></div></li>

                <div id="fade" style="display:none;">
                    <div id="loading_box" class="loader"></div>
                </div>


            <div id="payment_info1" <?php if ($this->hasCCProfile() == true) { ?> style="display: none;" <?php } ?> >
                <li>
                    <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                                <?php if (isset($response[0]['expiry'])){  $_ccExpMonth = substr($response[0]['expiry'], 0, 2); }  else { $_ccExpMonth = ""; } ?>
                                <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="v-fix">
                            <?php if (isset($response[0]['expiry'])){  $_ccExpYear = substr($response[0]['expiry'], 2, 4); }  else { $_ccExpYear = ""; } ?>
                            <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                                <?php foreach ($this->getCcYears() as $k => $v): ?>
                                    <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == "20" . $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>

                    </div>
                </li>
            </div>
            <li <?php if($response =="CardConnect_Error"){?> style="display: none;" <?php } ?>>
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" onkeypress="javascript:return validate(event, 'ccgateway_cc_cid');
                                    blockNonNumbers(this, event, false, false)" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="ccgateway_cc_cid" name="payment[cc_cid]" value="" maxlength="4" />
                    </div>
                    <div style="font-size: 12px; margin-top: 10px; text-decoration: underline;">
                        <?php echo $this->__('Card Verification Number not stored.') ?>
                    </div>
    <!--                    <a href="#" class="cvv-what-is-this"><?php // echo $this->__('What is this?')    ?></a> -->
                </div>
            </li>

<?php if (Mage::getSingleton('customer/session')->isLoggedIn()) { ?>
            <div id="save_card_4future" <?php if ($this->hasCCProfile() == true) { ?> style="display:none;"  <?php } ?>>
                <li>
                    <span style="margin-bottom: 10px;">
                        <input type="checkbox" title="<?php echo $this->__('Save Card details for future use') ?>"  id="ccgateway_cc_wallet" name="payment[cc_wallet]" value="checked" onclick="javascript:return showAliseField()"  />
                    </span>
                    <label for="<?php echo $_code ?>_cc_wallet"><?php echo $this->__('Save Card details for future use') ?></label>
                </li>
            </div>
<?php } ?>


            <div id="save_card" style="display:none;">

                <li>
                    <label for="<?php echo $_code ?>_cc_Billing"><strong><?php echo $this->__('Billing Information') ?></strong></label>
                </li>

                <li>
                    <span style="margin-bottom: 10px;">
                        <input type="checkbox" title="<?php echo $this->__('Use default bill to address') ?>"  id="ccgateway_default_address" name="payment[cc_default_address]" value="checked"
                               onclick="javascript:return showDefaultAddress('<?php echo $billingStreet; ?>', '<?php echo $billingCity; ?>', '<?php echo $billingRegion; ?>', '<?php echo $billingCountry; ?>', '<?php echo $billingPostCode; ?>', '<?php echo $billingTelephone; ?>')"  />
                    </span>
                    <label for="<?php echo $_code ?>_default_address"><?php echo $this->__('Use default bill to address') ?></label>
                </li>


                <li>
                    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                    <label for="<?php echo $_code ?>_cc_profile_name" class="required"><em>*</em><?php echo $this->__('Card Name (Alias)') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('Card Name (Alias)') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_profile_name" name="payment[cc_profile_name]" value=""  />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_street" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('Street Address') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_street" name="payment[cc_street]" value=""  />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_city" name="payment[cc_city]" value=""  />
                    </div>
                </li>

                <li>

                    <label for="<?php echo $_code ?>_cc_region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <?php $regionCollection = Mage::getModel('directory/region_api')->items("US"); ?>
                        <select name='payment[cc_region]' id='<?php echo $_code ?>_cc_region' class="validate-select" >
                            <option value="">Please select region, state or province</option>
                            <?php
                            foreach ($regionCollection as $region) {
                                ?>
                                <option value="<?php echo $region['name'] ?>" ><?php echo $region['name'] ?></option>
                                <?php
                            }
                            ?>

                        </select>
                    </div>

                </li>



                <li>
                    <div class="field">
                        <label for="<?php echo $_code ?>_cc_country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php
                            $_countries = Mage::getResourceModel('directory/country_collection')
                                    ->loadData()
                                    ->toOptionArray(false)
                            ?>
                            <?php if (count($_countries) > 0): ?>
                                <select name="payment[cc_country]" id="<?php echo $_code ?>_cc_country">
                                    <option value="">-- Please Select --</option>
                                    <?php foreach ($_countries as $_country): ?>
                                        <option value="<?php echo $_country['value'] ?>" >
                                            <?php echo $_country['label'] ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            <?php endif; ?>

                        </div>
                    </div>
                </li>

                <li>
                    <label for="<?php echo $_code ?>_cc_postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('Zip/Postal Code') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_postcode" name="payment[cc_postcode]" value=""  />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <input type="text"  title="<?php echo $this->__('telephone') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_telephone" name="payment[cc_telephone]" value=""  />
                    </div>
                </li>

            </div>


            <?php echo $this->getChildHtml() ?>
        <?php } ?>

    </ul>

</fieldset>
<?php } ?>

