<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

?>
<?php 
	$isProd = count(Mage::getModel('core/variable')->loadByCode('is_production')->getValue('plain')) > 0 ? (int) Mage::getModel('core/variable')->loadByCode('is_production')->getValue('plain') : 0;
	//var_dump($isProd);exit;
?>
<div class="main-container faq faq-container">
    <h1 class="container"> Frequently Asked Questions </h1>
    <div class="container faq-content">
        <strong>
	    	<p class="question">When will my device ship?</p>
	    </strong>
        <p class="answer">
            <strong>Orders are shipping daily. Get your order in now!
		    </strong> Your order will ship in 1-2 business days after it’s received. With standard ground shipping, your order will arrive in 4–7 days. Standard ground shipping is FREE with the purchase of a 360fly camera. If you paid for&nbsp;expedited shipping, you’ll be happily opening your package in 2–3 business days.
        </p>

        <strong>
		    <p class="question">
		    Can I cancel my order?
		    </p>
		</strong>
        <p class="answer">
            We’d rather see you give your 360fly a test run first, but if you must absolutely cancel your order, use the link in your confirmation email. (If you are a registered user, you can also access the order through the order history tab in your profile.) If your order has not yet been processed, you can cancel it from that page. We have a very limited 4-hour window in which you can cancel your order before it is processed. If you’re unable to cancel within the aforementioned time frame, do not fear, call us at 844-HELP-FLY and we can issue a RMA#, and you can return the device for a full refund.
        </p>

        <strong>
	    	<p class="question">What’s the return policy for my 360fly.com&nbsp;purchase?</p>
	    </strong>
        <p class="answer">
            We want to make sure you love your 360fly. If you purchased your&nbsp;device directly from 360fly.com, you can return it for credit or exchange it within 30&nbsp;days from the date the unit shipped from our distribution center.
        </p>

        <strong>
	    	<p class="question">How do I return my device?</p>
	    </strong>
        <p class="answer">
            If you wish to return products purchased direct from&nbsp;360fly.com, just send an email with your order number to orders@360fly.com or call 844-HELP-FLY. We’ll issue a return authorization with all the instructions for shipping the order back to us. Your refund is issued when we receive the returned product.
        </p>

        <strong>
	    	<p class="question">What is the warranty on 360fly products?</p>
	    </strong>
        <p class="answer faq-last-para">
            360fly products come with a 1-year warranty from date of purchase. If something goes wrong with the device and it does not function as it should, please contact us at support@360fly.com or call 844-HELP-FLY and one of our Fly Experts will do everything he or she can to make things right.
        </p>
    </div>

</div>