<?php
/**
 * @brief Defines the html for show Payment Information Block on Reorder
 * @category Magento CardConnect Payment Module
 * @author CardConnect
 * @copyright Portions copyright 2014 CardConnect
 * @copyright Portions copyright Magento 2014
 * @license GPL v2, please see LICENSE.txt
 * @access public
 * @version $Id: $
 *
 * */
/**
  Magento
 *
  NOTICE OF LICENSE
 *
  This source file is subject to the Open Software License (OSL 3.0)
  that is bundled with this package in the file LICENSE.txt.
  It is also available through the world-wide-web at this URL:
  http://opensource.org/licenses/osl-3.0.php
  If you did not receive a copy of the license and are unable to
  obtain it through the world-wide-web, please send an email
  to license@magentocommerce.com so we can send you a copy immediately.
 *
  @category Cardconnect
  @package Cardconnect_Ccgateway
  @copyright Copyright (c) 2014 CardConnect (http://www.cardconnect.com)
  @license http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<style>
    #fade{ width:100%; height:100%; background:rgba(0,0,0,0.1); position:fixed; top:0px; left:0px; display:none;}
    .loader{position:absolute; top:80%; left:50%;}
</style>
<fieldset class="form-list">
    <?php $_code = $this->getMethodCode();
    $isTestMode = $this->isTransactionModeTest();
    $siteName = Mage::helper('ccgateway')->getSiteName();
    $errorLogURL = Mage::getUrl('ccgateway/log/logfrontenderrors',array('_secure'=>true));
    ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <?php if ($this->getCheckoutType() == "payment_page") { ?>
            <li>
                <?php echo Mage::helper('ccgateway')->__('You will be redirected to CardConnect website when you place an order.') ?>
            </li>
        <?php } else { ?>

            <li>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <div class="input-box">
                    <input type="text"  title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->escapeHtml($this->getInfoData('cc_owner')) ?>"  />
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_type" class="required validate-cc-type "><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
                <div class="input-box">

                    <select id="ccgateway_cc_type" name="payment[cc_type]"  title="<?php echo $this->__('Credit Card Type') ?>" class="required-entry validate-select" onchange="resetcardinfo();">
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                        <?php  $_ccType = $this->getInfoData('cc_type'); ?>
                        <?php foreach ($this->getCcTypes() as $ccType): ?>
                            <option value="<?php  echo $ccType['value'];   ?>"<?php if ($ccType['value'] == $_ccType): ?> selected="selected"<?php endif ?>><?php  echo $ccType['label'];   ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>

            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input type="text" onchange="valid_credit_card(value, '<?php echo $isTestMode; ?>', '<?php echo $siteName; ?>', '<?php echo $errorLogURL; ?>')"  onkeypress="javascript:return validate(event , 'ccgateway_cc_number_org'); blockNonNumbers(this, event, false, false)" id="ccgateway_cc_number_org" name="payment[cc_number_org]" title="<?php echo $this->__('Credit Card Number') ?>" maxlength="16"  class="input-text required-entry" value="<?php if($this->getInfoData('cc_number')){ echo substr_replace($this->getInfoData('cc_number'), str_repeat('*', 12), 0, 12); } ?>" />
                    <input type="hidden"   id="<?php // echo $_code ?>ccgateway_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text" value="<?php echo $this->getInfoData('cc_number')?>" />
                    <div class="validation-advice" id="testError" style="display: none;"></div>
                </div>

</li>
            <li><div id="response"></div></li>
            <div id="fade" style="display:none;">
                <div id="loading_box" class="loader"></div>
            </div>

            <li>
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                            <?php foreach ($this->getCcYears() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"<?php if ($k == $_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                        </select>
                    </div>

                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" onkeypress="javascript:return validate(event , 'ccgateway_cc_cid' ); blockNonNumbers(this, event, false, false)" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" id="ccgateway_cc_cid" name="payment[cc_cid]" value="<?php echo $this->getInfoData('cc_cid') ?>" />
                    </div>
                    <!--                    <a href="#" class="cvv-what-is-this"><?php // echo $this->__('What is this?') ?></a> -->
                </div>
            </li>

            <?php echo $this->getChildHtml() ?>
        <?php } ?>

    </ul>

</fieldset>

