<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
$communityIndex = 'chad-reed';
$athleteName = 'Chad Reed';

?>


<div class="wrapper-width">
	<?php echo $this->getLayout()->createBlock('core/template')
				->setData('ci', $communityIndex)
				->setData('athlete_name', $athleteName)
				->setTemplate('page/html/pages/community/community-dropdown.phtml')
				->toHtml(); 
	?>
</div>
<div class=" community-inner chad-reed" id="athlete-marketing">
	<div class="chad-container" id="">
		<div class="container wrapper-width">
			<div class="covertext text-contain ">
				<h1 class="extreme-headline">
					<b>Chad Reed</b>
				</h1>
                <h2 class="extreme-headline">Motocross </h2>
			</div>
		</div>
	</div>
	<div class="bio-container">
		<div class="bio-left greybg ">
			<div class="bio-left-child-1 bio-left-child-x">
				<div class="bio-left-child-container">
					<h3>Chad's Bio</h3>
					<div class="stats-box">
						<span class="stats pull-left">Age:</span><span class="pull-left ">33</span>
						<span class="clear"></span>
						<span class="stats pull-left">Location:</span><span class="pull-left "> Kurri Kurri, Australia</span>
						<span class="clear"></span>
						<span class="stats pull-left">Sport:</span><span class="pull-left ">Motocross</span>
						<span class="clear"></span>
					</div>
					<p>Since making the move to America in 2002, Chad Reed has amassed one of the most impressive careers in motocross history. Reed has achieved a majority of his success as a Supercross competitor, including a 2002 Lites Championship and Supercross Championship finishes of second, first, second, third, second, first and second from 2003-2009.
					</p>&nbsp;
					<p>Reed made a triumphant return to the outdoor season in 2009 and ended up with his first AMA Motocross Championship under the guidance of legendary team manager Roger DeCoster, a title that had eluded him throughout his eight-year career.
					</p>&nbsp;
					<p>Aside from racing, Reed is an avid Supercross promoter in his home country of Australia. &nbsp;Reed was an accomplished Supercross rider down under, winning two national championships before his move to the U.S.A. Reed and his wife Ellie have 3 children: Tate, Kiah and Pace. The couple lives in Florida where Reed trains in the off-season and regularly hosts fellow riders to get some work in around his compound in the Sunshine State.
					</p>
				</div>
			</div>
			<div class="bio-left-child-2 bio-left-child-x">
			</div>
		</div>
		<div class="bio-right greenbg">
			<div class="">
				<div class="athlete_highlight_text">
					<h4>Career Highlights</h4>
					<div class="bio-right-content">
						<p class="date-highlight">2009</p>
						<p class="indent">Australian Supercross Champion</p>
						<p class="indent">AMA Athlete of the Year</p>
						<p class="indent">AMA National Motocross Champion</p>
						<p class="indent">Monster Energy Triple Crown MX Champion</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2008</p>
						<p class="indent">Australian Supercross Champion</p>
						<p class="indent">AMA/FIM World Supercross Champion</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2007</p>
						<p class="indent">King of Bercy Supercross Champion</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2005</p>
						<p class="indent">X-Games Supermoto- Bronze Medal</p>
					</div>
      			</div>									
			</div>
		</div>
	</div>
</div>
<div class=" athlete-social">
	<div class="athlete-wrapper wrapper-width">
		<div class="col-sm-12 col-md-12 col-lg-12 icons-wrapper">
	        <div class="athlete-social-name"><p class="pull-left follow">Follow Chad</p></div>
	      	<div class="pull-left icons">
		        <a href="https://twitter.com/crtwotwo" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
		        <a href="https://www.facebook.com/TwoTwoMotorsports" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
		        <a href="https://instagram.com/crtwotwo/" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
	        </div>
      	</div>
	</div>
</div>
