<?php 
	$baseUrl = $this->getBaseUrl();
?>


<ul class="nav nav-pills community-btn hidden-xs">
  <li class="community-first-dd">
    <a class="dropdown-toggle2" href="#">
		<?php echo $this->athlete_name;?><span class=" icon-drop-arrow sub-menu-arrow"></span>
  	</a>
    <ul class="dropdown-menu community-dropdown">
		<li class="<?php if($this->ci == 'terry-adams'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>terry-adams/">Terry Adams</a></li>
		<li class="<?php if($this->ci == 'matt-cordova'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>matt-cordova/">Matt Cordova</a></li>
		<li class="<?php if($this->ci == 'sunny-garcia'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>sunny-garcia/">Sunny Garcia</a></li>
		<li class="<?php if($this->ci == 'jorge-lorenzo'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>jorge-lorenzo/">Jorge Lorenzo</a></li>
		<li class="<?php if($this->ci == 'chad-reed'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>chad-reed/">Chad Reed</a></li>
		<li class="<?php if($this->ci == 'cannondale'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>cannondale/">Cannondale</a></li>
		<li class="<?php if($this->ci == 'pro-circuit'){echo 'active';}?>"><a tabindex="-1" href="<?php echo $baseUrl;?>pro-circuit/">Pro Circuit Kawasaki</a></li>
    </ul>
  </li>
</ul>