<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
$communityIndex = 'jorge-lorenzo';
$athleteName = 'Jorge Lorenzo';

?>


<div class="wrapper-width">
	<?php echo $this->getLayout()->createBlock('core/template')
				->setData('ci', $communityIndex)
				->setData('athlete_name', $athleteName)
				->setTemplate('page/html/pages/community/community-dropdown.phtml')
				->toHtml(); 
	?>
</div>
<div class="community-inner jorge-lorenzo" id="athlete-marketing">
	<div class="jorge-container" id="">
		<div class="container wrapper-width">
			<div class="covertext text-contain ">
				<h1 class="extreme-headline">
					<b>Jorge Lorenzo</b>
				</h1>
                <h2 class="extreme-headline">MotoGP Champion</h2>
				<p class="col-sm-12 col-md-5">“360fly is really impressive to me: the image quality, the originality of the camera, because it allows you to capture what’s happening in every direction, without limits and uncropped. It doesn’t miss anything.”</p>
			</div>
		</div>
	</div>
	<div class="bio-container">
		<div class="bio-left greybg ">
			<div class="bio-left-child-1">
	          <h3>Jorge's Bio</h3>
	            <div class="stats-box">
					<span class="stats pull-left">Age:</span><span class="pull-left ">28</span>
					<span class="clear"></span>
					<span class="stats pull-left">Location:</span><span class="pull-left ">Majorca, Spain</span>
					<span class="clear"></span>
					<span class="stats pull-left">Sport:</span><span class="pull-left ">MotoGP</span>
					<span class="clear"></span>
					<span class="stats pull-left">Team:</span><span class="pull-left ">Movistar Yamaha</span>
					<span class="clear"></span>
	            </div>
				<p>Jorge Lorenzo Guerrero is a Spanish motorcycle prodigy and international racing icon. He is the 2006 and 2007 250cc World Champion, the 2010 and 2012 Moto GP World Champion, and is hot in the hunt for the for this year’s MotoGP championship. Jorge began racing at the tender age of three and took his first checkered flag at eight. He currently races MotoGP for the Yamaha factory team.
				</p>
			</div>
			<div class="bio-left-child-2">
			</div>
		</div>
		<div class="bio-right greenbg">
			<div class="">
				<div class="athlete_highlight_text">
					<h4>Career Highlights</h4>
					<div class="bio-right-content">
						<p class="date-highlight">2012</p>
						<p class="indent">MotoGP World Champion</p>						
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2010</p>
						<p class="indent">MotoGP World Champion</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2007</p>
						<p class="indent">MotoGP World Champion</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2006</p>
						<p class="indent">MotoGP World Champion</p>						
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="athlete-social">
	<div class="athlete-wrapper">
		<div class="col-sm-12 col-md-12 col-lg-6 icons-wrapper">
	        <div class="athlete-social-name"><p class="pull-left follow">Follow Jorge</p></div>
	      	<div class="pull-left icons">
		        <a href="https://twitter.com/lorenzo99" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
		        <a href="https://www.facebook.com/Jorge.Lorenzo.Official" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
		        <a href="https://instagram.com/jorgelorenzo99" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
	        </div>
      	</div>
	</div>
</div>