<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
$communityIndex = 'terry-adams';
$athleteName = 'Terry Adams';
?>

<div class="wrapper-width">
	<?php echo $this->getLayout()->createBlock('core/template')
				->setData('ci', $communityIndex)
				->setData('athlete_name', $athleteName)
				->setTemplate('page/html/pages/community/community-dropdown.phtml')
				->toHtml(); 
	?>
</div>

<div class="community-inner terry-adams" id="athlete-marketing">
	<div class="ta-container" id="">
		<div class="container-fluid athlete-summary">
			<div class="covertext text-contain">
				<h1 class="extreme-headline">
					<b>Terry Adams</b>
				</h1>
                <h2 class="extreme-headline">BMX Flatland</h2>
				<p class="col-xs-8 col-sm-6 col-md-6">"My success has been driven by innovation and doing things that have never been done before, which is exactly what 360fly is doing with their incredible camera.”</p>
			</div>
		</div>
	</div>
	<div class="bio-container">
		<div class="bio-left greybg ">
			<div class="bio-left-child-1">
	          <h3>Terry's Bio</h3>
	            <div class="stats-box">
	              <span class="stats pull-left">Age:</span><span class="pull-left ">31</span>
	              <span class="clear"></span>
	              <span class="stats pull-left">Location:</span><span class="pull-left ">Hammond, Louisiana</span>
	              <span class="clear"></span>
	              <span class="stats pull-left">Sport:</span><span class="pull-left ">BMX Flatland</span>
	              <span class="clear"></span>
	            </div>
				<p>Hailing from a small town outside of New Orleans, Terry Adams was just 12 years old when found his passion for flatland; and by the time he was 16, Terry was entering flatland contests as a professional.</p>
				<p>It was on the professional contest circuit that Terry began to make a name for himself, winning contest after contest all around the world. After winning an X Games gold medal in 2005, Terry received the most prestigious awards in his sport—Ride BMX Magazine's Number One Ride Award. He has since gone on to win the NORA Cup a second time in 2008.</p>
				<p>Over the past few years Terry has graced the covers of and had feature interviews in all of the world's leading BMX magazines and been showcased on national television numerous times. His skills and success in flatland are unmatched, and many of his peers refer to him as 'the ambassador for flatland'.</p>
				<p>Today Terry continues to push himself and the limits of his riding while representing his sponsors to the fullest. Although his travel schedule is packed with demos all across the country and contests in various corners the globe, Terry remains grounded in his roots that stem from a passion for flatland that began so many years ago.</p>
			</div>
			<div class="bio-left-child-2">
	          <h3>Q &amp; A</h3>
	          <p class="question col-xs-1 col-sm-1 pull-left">Q.</p> <p class="question col-xs-11 col-sm-11 pull-left space-left">What inspired you to start riding?</p>
	          <p class="col-xs-1 col-sm-1">A.</p> <p class="answer col-xs-11 col-sm-11 ">I love the feeling I get from riding BMX. The feeling of freedom is why I started riding bikes. I was motivated by the fact that I could create my own tricks and the sport has no rules as well. </p><p class="question col-xs-1 col-sm-1 pull-left">Q.</p> <p class="question col-xs-11 col-sm-11 pull-left">Favorite trick?</p>
	          <p class="col-xs-1 col-sm-1">A.</p> <p class="answer col-xs-11 col-sm-11">My favorite trick is called 'the katrina' I invented it during hurricane Katrina here in Louisiana.</p>
			  <p class="question col-xs-1 pull-left">Q.</p><p class=" question col-xs-11 col-sm-11 pull-left">When you're not riding what are you up to?</p>
	          <p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">My other interest besides BMX is marketing, business, and real-estate. </p></div>
		</div>
		<div class="bio-right greenbg">
			<div class="">
				<div class="athlete_highlight_text">
					<h4>Career Highlights</h4>
					<div class="bio-right-content">
						<p class="date-highlight">2013</p>
						<p class="indent">3rd Place: Dew Tour Ocean City - BMX Flatland,
						<br> Ocean City, Maryland, USA</p>
						<p class="indent">4th Place: BMX Worlds - Pro Flatland,<br>Cologne, Germany</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2012</p>
						<p class="indent">2nd Place: Dew Tour Ocean City, BMX Flatland,<br> Ocean City, Maryland, USA</p>
						<p class="indent"> 3rd Place: Flatland Voodoo Jam,<br> New Orleans, USA</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2011</p>
						<p class="indent">Winner: JoMoPro BMX Flatland<br>Champion, Missouri, USA</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2008</p>
						<p class="indent">Winner: NORA cup, Number One Flatride,<br>Award, USA</p>
					</div>
					<div class="bio-right-content">
						<p class="date-highlight">2005</p>
						<p class="indent">1st place: X Games, Seoul, South Korea</p>
						<p class="indent">Winner: NORA Cup - Number One Flatrider<br>Award, USA</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="athlete-social">
	<div class="athlete-wrapper">
		<div class="col-sm-12 col-md-12 col-lg-6 icons-wrapper">
	        <div class="athlete-social-name"><p class="pull-left follow">Follow Terry</p></div>
	      	<div class="pull-left icons">
		        <a href="https://twitter.com/terryadamsbmx" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
		        <a href="https://www.facebook.com/terryadamsflatland" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
		        <a href="https://instagram.com/terryadamsbmx" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
	        </div>
      	</div>
	</div>
</div>

