<?php 

/**
* @category Mage
* @package Mage_Page
* @copyright Copyright (c) 2016 MageNYC-AhyConsulting for 360Fly.com
*/

$baseUrl = $this->getBaseUrl();
$mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
$skinUrl = $this->getSkinUrl();
$communityIndex = 'todd-wells';
$athleteName = 'Todd Wells';

?>


<div class="wrapper-width">
	<?php echo $this->getLayout()->createBlock('core/template')
				->setData('ci', $communityIndex)
				->setData('athlete_name', $athleteName)
				->setTemplate('page/html/pages/community/community-dropdown.phtml')
				->toHtml(); 
	?>
</div>
<div class="community-inner todd-wells" id="athlete-marketing">
  <div class="todd-container" id="">
    <div class="container wrapper-width">
      <div class="covertext text-contain ">
        <h1 class="extreme-headline">
          <b>Todd Wells</b>
        </h1>
		<h2 class="extreme-headline">Mountain Biking</h2>
      </div>
    </div>
  </div>
  <div class="bio-container">
    <div class="bio-left greybg ">
      <div class="bio-left-child-1 bio-left-child-x">
          <div class="bio-left-child-container">
            <h3>Todds's Bio</h3>
            <div class="stats-box">
              <span class="stats pull-left">Age:</span><span class="pull-left ">39</span>
              <span class="clear"></span>
              <span class="stats pull-left">Location:</span><span class="pull-left ">Durango, Colorado</span>
              <span class="clear"></span>
              <span class="stats pull-left">Sport:</span><span class="pull-left ">Cyclo-cross and mountain bike</span>
              <span class="clear"></span>
            </div>
            <p>Todd Wells&nbsp;fell in love with a bicycle at an early age starting with BMX from the age of five through sixteen. After graduating high school he picked up his first mountain bike and has been on a tear ever since. He found his way out to Durango, CO where he attended Fort Lewis College and began a pursuit of his career in cycling.</p>
            <p>Wells won two Cross Country Mountain Bike Collegiate titles for Fort Lewis College and the inaugural Semi Pro NORBA National Series title in 1996 before taking a break from his studies to become a full time professional cyclist.</p>
            <p>His initial professional career was short lived as he decided to hang up his wheels at the end of the 1998 season and finish his collegiate studies at the University of Arizona. In 2000 he graduated from the University of Arizona with a B.S. in Management Information Systems and immediately started working for I.B.M., a company he interned with during his time as a student.</p>
            <p>Wells quickly realized that being a bike racer was better than having a “real” job and started training once again with his sights set on returning to the professional ranks.</p>
            <p>By 2008 he was back where he started with the Specialized team and his results seem to get better with age. He has won fourteen National Championship titles across four disciplines. In 2011 he took on some endurance races and racked up wins in both the Leadville 100 and La Ruta de Los Conquistadors.</p>
            <p>2012 might have been his best season yet with his third trip to the Olympic Games where he placed a career best 10th. He also managed to win his second PROXCT series title, second Pan American Championship title and stood on the podium at the Windham World Cup.</p>
            <p>When Todd isn’t racing all over the world you can find him in one of three places; hanging out with his wife Meg, son Cooper and dog Winston, grinding it out on the golf course or hitting the dirt jump trails around Durango or Tucson, AZ.</p>
          </div>
      </div>
      <div class="bio-left-child-2 bio-left-child-x">
          <div class="bio-left-child-container">
                <h3>Q &amp; A</h3>
                <p class="question col-xs-1 col-sm-1 pull-left">Q.</p>
                <p class="question col-xs-11 col-sm-11 pull-left ">Biggest  accomplishment?</p>
                <p class="col-xs-1 col-sm-1">A.</p>
                <p class="answer col-xs-11 col-sm-11 ">Becoming a Dad, all you Dad's out there know what I'm talking about. Race wise there are a few, my first big win was the Collegiate National Champs in Durango in 1995, that really started my career and got me a factory ride on the Specialized Mountain Dew Team. Making my first Olympic Team was huge in 2004. Winning the Leadville 100 in 2011 was also a highlight.  </p>
                <p class="question col-xs-1 col-sm-1 pull-left">Q.</p>
                <p class="question col-xs-11 col-sm-11 pull-left">Coolest place you've ever been?</p>
                <p class="col-xs-1 col-sm-1">A.</p>
                <p class="answer col-xs-11 col-sm-11">Racing has taken me all over the world but I would have to say either my first international trip to World Champs in Cairns Australia or racing across Costa Rica in the La Ruta de los Conquistadores. Both are amazingly lush tropical paradises.</p>

                <p class="question col-xs-1 col-sm-1 pull-left">Q.</p>
                <p class="question col-xs-11 col-sm-11 pull-left">What music is playing in your car?</p>
                <p class="col-xs-1 col-sm-1">A.</p>
                <p class="answer col-xs-11 col-sm-11">I usually listen to Pandora so it's either some hip hop stations like Jay-Z or Biggie Smalls. Or, I also listen to quite a bit of country either modern or old school Willie Nelson stations.</p>
                <p class="question col-xs-1 pull-left">Q.</p>
                <p class=" question col-xs-11 col-sm-11 pull-left">Never leave home without?</p>
                <p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">When traveling I always have to have a fresh tooth brush and set of ear plugs. </p>
                <p class="question col-xs-1 pull-left">Q.</p>
                <p class=" question col-xs-11 col-sm-11 pull-left">Favorite riding trails or area?</p>
                <p class="col-xs-1 col-sm-1">A.</p>
                <p class="answer col-xs-11 col-sm-11">I love riding in my hometown of Durango, CO. I would have to say I've never had a bad ride on the Colorado Trail, flowy, fun and always beautiful.</p>
                <p class="question col-xs-1 pull-left">Q.</p>
                <p class=" question col-xs-11 col-sm-11 pull-left">What inspires you?</p>
                <p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">I love setting a goal and trying to accomplish it. I don't always achieve what I set out to but having a goal gives me motivation to do everything I can at the time to accomplish it and get the most out of myself. It's amazing what you can do when you put your mind to something.
                </p>

                <p class="question col-xs-1 pull-left">Q.</p>
                <p class=" question col-xs-11 col-sm-11 pull-left">Favorite Food? </p>
                <p class="col-xs-1 col-sm-1">A.</p><p class="answer col-xs-11 col-sm-11">Nutella, I can and do eat it by the jar full.
                </p>
          </div>
      </div>
    </div>
    <div class="bio-right greenbg">
     
        <div class="athlete_highlight_text">
          <h4>Career Highlights</h4>
          <div class="bio-right-content">
              <p class="date-highlight">2015</p><p class="indent">1st, USA Cycling Marathon National Championship</p>
              <p class="indent">1st, Fontana PROXCT STXC</p>
              <p class="indent">2nd, Bonelli #2 PROXCT STXC</p>
              <p class="indent">2nd, Sea Otter Classic STXC</p>
          </div>
          <div class="bio-right-content">
            <p class="date-highlight">2014</p>
            <p class="indent">1st,USA Cycling Cross Country National Championship</p>
            <p class="indent">1st, USA Cycling Marathon National Championship</p>
            <p class="indent">2nd, USA Cycling Short Track National Championship</p>
            <p class="indent">PROXCT Overall Champion</p>
            <p class="indent">1st, Leadville Trail 100</p>
            <p class="indent">1st, Colorado Springs PROXCT XC</p>
            <p class="indent">1st, Subaru Cup PROXCT XC</p>
            <p class="indent">1st, Missoula PROXCT STXC</p>
            <p class="indent">1st, Sea Otter Classic STXC</p>
            <p class="indent">1st, La Ruta Stage 3</p>
            <p class="indent">2nd, Whiskey 50</p>
          </div>
          <div class="bio-right-content"> 
            <p class="date-highlight">2013</p>
            <p class="indent">1st, USA Cycling Marathon National Championship</p>
            <p class="indent">1st, USA Cycling Short Track National Championship</p>
            <p class="indent">2nd, USA Cycling Cross Country National Championship</p>
            <p class="indent">1st, PROXCT Overall Champion</p>
            <p class="indent">1st, Breck Epic Stage Race Overall</p>
            <p class="indent">1st, Breck Epic Stage 1</p>
            <p class="indent">1st, Breck Epic Stage 2</p>
            <p class="indent">1st, Breck Epic Stage 3</p>
            <p class="indent">1st, Breck Epic Stage 5</p>
            <p class="indent">1st, Fontana PROXCT XC</p>
            <p class="indent">1st, Fontana PROXCT STXC</p>
            <p class="indent">1st, Bump and Grind PROXCT XC</p>
            <p class="indent">1st, Subaru Cup PROXCT XC1st, Subaru Cup PROXCT STXC</p>
            <p class="indent">1st, Subaru Cup PROXCT STXC</p>
          </div>
          <div class="bio-right-content">
            <p class="date-highlight">2012</p>
            <p class="indent">Member USA Olympic Mountain Bike Team London</p>
            <p class="indent">1st, USA Cycling Marathon National Championship</p>
            <p class="indent">1st, USA Cycling Short Track National Championship</p>
            <p class="indent">1st, Pan Am Championships</p>
            <p class="indent">2nd, USA Cycling Cross Country National Championship</p>
            <p class="indent">1st, PROXCT Overall Champion</p>
            <p class="indent">10th, London Olympic MTB</p>
            <p class="indent">4th, UCI World Cup Wyndham</p>
          </div>
          <div class="bio-right-content">           
            <p class="date-highlight">2011</p>
            <p class="indent">1st, USA Cycling Cross Country National Championship</p>
            <p class="indent">2nd, USA Cycling Short Track National Championship</p>
            <p class="indent">1st, Sea Otter Classic XC</p>
            <p class="indent">7th, UCI Mountain Bike World Championship Switzerland</p>
            <p class="indent">1st Leadville Trail 100</p>
            <p class="indent">1st La Ruta de los Conquistadores</p>
            <p class="indent">1st, La Ruta de los Conquistadores Stage 1</p>
          </div>
          <div class="bio-right-content">
            <p class="date-highlight">2010</p>
            <p class="indent">1st, USA Cycling Cyclocross National Championships</p>
            <p class="indent">1st, USA Cycling Short Track National Championships</p>
            <p class="indent">1st, USA Cycling Cross Country National Championships</p>
            <p class="indent">1st, Pan America Championship Guatemala</p>
            <p class="indent">1st, Fontana US Cup XC</p>
          </div>
        </div>
    </div>
</div>
<div class=" athlete-social">
  <div class="athlete-wrapper wrapper-width">
    <div class="col-sm-12 col-md-12 col-lg-12 icons-wrapper">
          <div class="athlete-social-name"><p class="pull-left follow">Follow Todd</p></div>
          <div class="pull-left icons">
            <a href="https://twitter.com/yotwells" target="_blank"><span class="icon-twitter-jul15 social-links"></span></a>
            <a href="https://www.facebook.com/todd.wells.980" target="_blank"><span class="icon-facebook-jul15 social-links"></span></a>
            <a href="https://instagram.com/yotwells/" target="_blank"><span class="icon-instagram-jul15 social-links"></span></a>
          </div>
        </div>
  </div>
</div>

