<?php
    $baseUrl = $this->getBaseUrl();
    $mediaUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
    $skinUrl = $this->getSkinUrl();
?>

	<div class="container wrapper-width">
		<div class="col-lg-4 col-lg-offset-2 col-md-5 col-md-offset-1 col-sm-6 col-xs-12">
	        <h3>360fly HD Mounts</h3>
	        <p>Stick your 360fly where your life happens. And make sure you have the right 360fly mounts to make sure it stays there.</p>
		</div>
	</div>
