<script type='text/javascript' src='https://www.google.com/jsapi'></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script type="text/javascript">
  $.noConflict();
</script>

<div class="padder">
<script language="javascript">
<!--
function patchtoggle(server) {
  patch=document.getElementById(server + "_patch").checked;
  if (patch) {
    window.location='<?php print Mage::helper('adminhtml')->getUrl("noc/server/patchtoggle"); ?>server/' + server + '/patch/1';
  } else {
    window.location='<?php print Mage::helper('adminhtml')->getUrl("noc/server/patchtoggle"); ?>server/' + server + '/patch/0';
  }
}
//-->
</script>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-head">
    <h3><?php echo $this->__('My Servers') ?></h3>
</div>
<?php if($this->getCollection()->count() > 0) { ?>

    <!-- <p><?php echo $this->__('') ?></p>-->

        <div class="content">
            <table width="100%" style="margin-top:-50px;">


                <?php foreach ($this->getCollection() as $server) { ?>
                  <?php if ($server->getStatus() == 1 or $server->getStatus() == 5 or $server->getStatus() == 6) {  ?>
                	<tr>
                		<td colspan="8"><div class="button-set"></div></td>
                	</tr>

	            	<tr>
	            		<td style="font-weight: bold;">HOSTNAME&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">IP&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">UPTIME&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">LEVEL&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">CPU&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">RAM&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">SSD&nbsp;&nbsp;</td>
	            		<td style="font-weight: bold;">BANDWIDTH&nbsp;&nbsp;</td>
	            	</tr> 



                   <tr>
                   		<td><?php echo $server->getHostName(); ?>&nbsp;&nbsp;</td>
                   		<td><?php echo $server->getHostIp()?>&nbsp;&nbsp;</td>
                   		<td><div id="divUptime<?php echo $server->getServerId(); ?>"><?//php echo $server->getUptime()?></div>&nbsp;&nbsp;</td>
                   		<td><?php echo $server->getLevel()?>&nbsp;&nbsp;</td>
                   		<td><?php echo $server->getLevel()?>&nbsp;&nbsp;</td>
                   		<td><? if ($server->getLevel() == 32) { echo '120'; } else { echo ($server->getLevel() * 4); } ?>GB&nbsp;&nbsp;</td>

									<? if($server->getPanel() == 'cpanel') { ?>
										<td><?php echo $server->getLevel() * 7.5?>GB&nbsp;&nbsp;</td>
									<? } ?>
									<? if ($server->getPanel() == 'mhm') { ?>
										<td><? if ($server->getLevel() == 32) { echo '1300'; } else { echo ($server->getLevel() * 50); } ?>GB&nbsp;&nbsp;</td>
									<? } ?>

                   		<td><?php echo $server->getLevel() * 250 + 250?>GB&nbsp;&nbsp;</td>
                   	</tr>
                   	<tr>
			                        <td colspan="8" style="font-weight: bold;">Automatically Patch Magento Installs
			<?php
			if ($server->getAutopatching()) {
			  print '<input type="checkbox" name="patch" id="'.$server->getHostName().'_patch" value="Y" onClick="patchtoggle(\''.$server->getHostName().'\')" checked/>';
			} else {
			  print '<input type="checkbox" name="patch" id="'.$server->getHostName().'_patch" value="Y" onClick="patchtoggle(\''.$server->getHostName().'\')" />';
			}
			?>
			<br/><br/></td>
                        </tr>

									<tr>
										<td colspan="8" style="font-weight: bold;">CONTROL PANEL</td>
									</tr>
									<? if($server->getPanel() == 'cpanel') { ?>
										<tr>
											<td colspan="8"><a target="_blank" href="https://<?php echo $server->getHostName(); ?>:2083">https://<?php echo $server->getHostName(); ?>:2083</a></td>
										</tr>
									<? } ?>
									<? if ($server->getPanel() == 'mhm') { ?>
									<tr>
										<td colspan="8"><a target="_blank" href="https://magemojo.com/mhm/app/#/host/<?php echo $server->getHostName(); ?>/help">https://magemojo.com/mhm/app/#/host/<?php echo $server->getHostName(); ?>/help</a></td>
									</tr>
									<? } ?>

									<tr>
										<td colspan="8">&nbsp;</td>
									</tr>

									<!--  real time gauages section -->
                   	<tr>
                   		<td colspan="8">
                   			<strong>Animated Real Time Performance</strong>
                   			<br/>
                   			<a href="/magento/noc/server/view/id/<?php echo $server->getServerId(); ?>">View Performance History Graphs</a>
                   		</td>
                   	</tr>

                   	<tr>
                   		<td colspan="8">

					    <script type='text/javascript'>
					      google.load('visualization', '1', {packages:['gauge']});
					      google.setOnLoadCallback(drawChart);
					      function drawChart() {
					        var data<?php echo $server->getServerId(); ?> = google.visualization.arrayToDataTable([
					          ['Label', 'Value'],
					          ['CPU', 0],
					          ['MEMORY', 0],
					          ['SWAP', 0],
					          ['DISK', 0],
							  ['NET-OUT', 0],
							  ['NET-IN', 0],
					        ]);

					        var options<?php echo $server->getServerId(); ?> = {
					          width: 550, height: 100,
					          redFrom: 90, redTo: 100,
					          yellowFrom:75, yellowTo: 90,
					          minorTicks: 5
					        };

					        var chart<?php echo $server->getServerId(); ?> = new google.visualization.Gauge(document.getElementById('chart_div<?php echo $server->getServerId(); ?>'));
					        chart<?php echo $server->getServerId(); ?>.draw(data<?php echo $server->getServerId(); ?>, options<?php echo $server->getServerId(); ?>);

							function drawChart<?php echo $server->getServerId(); ?>()
							{
						        jQuery.post(
						                //'/noc/snmp/view/id/<?php echo $server->getHostName(); ?>',
						                '/mojo_scripts/animatedgraphsnmp.php?id=<?php echo $server->getHostName(); ?>',
						                { 'foo' : 'bar' },
						                function (response) {

						                    // parse response
						                    var retObj = eval('(' + response + ')');;
											//alert(retObj['cpu']);

											data<?php echo $server->getServerId(); ?> = google.visualization.arrayToDataTable([
												['Label', 'Value'],
											    ['CPU', (retObj['cpu']/1)],
											    ['MEMORY', (retObj['memory']/1)],
											    ['SWAP', (retObj['swap']/1)],
											    ['DISK', (retObj['homePercent']/1)],
											    ['NET-OUT', (retObj['net-out-percent']/1)],
											    ['NET-IN', (retObj['net-in-percent']/1)],
											]);
									        chart<?php echo $server->getServerId(); ?>.draw(data<?php echo $server->getServerId(); ?>, options<?php echo $server->getServerId(); ?>);
									        jQuery("#divUptime<?php echo $server->getServerId(); ?>").html(retObj['uptime']);
									        //alert(retObj['homeSize']);
									        jQuery("#spanDiskTotal<?php echo $server->getServerId(); ?>").html( Math.ceil(((retObj['homeTotal'] / 1024 / 1024)*100))/100 );
									        jQuery("#spanDiskUsed<?php echo $server->getServerId(); ?>").html( Math.ceil(((retObj['homeUsed'] / 1024 / 1024)*100))/100 );
									        jQuery("#spanDiskAvailable<?php echo $server->getServerId(); ?>").html( Math.ceil(((retObj['homeAvailable'] / 1024 / 1024)*100))/100 );

									        jQuery("#spanNetIn<?php echo $server->getServerId(); ?>").html(retObj['net-in-kbps']);
									        jQuery("#spanNetOut<?php echo $server->getServerId(); ?>").html(retObj['net-out-kbps']);
						                }
						            );
					            setTimeout(drawChart<?php echo $server->getServerId(); ?>, 2500);
							}
							drawChart<?php echo $server->getServerId(); ?>();

					      }
					    </script>
    					<div style="margin-bottom:10px;" id='chart_div<?php echo $server->getServerId(); ?>'></div>

    					<div>
    						<b>Disk Size:</b> <span id="spanDiskTotal<?php echo $server->getServerId(); ?>"></span> GB&nbsp;&nbsp;
    						<b>Used:</b> <span id="spanDiskUsed<?php echo $server->getServerId(); ?>"></span> GB&nbsp;&nbsp;
    						<b>Available:</b> <span id="spanDiskAvailable<?php echo $server->getServerId(); ?>"></span> GB&nbsp;&nbsp;
    						<b>Network Out:</b> <span id="spanNetOut<?php echo $server->getServerId(); ?>"></span> kbps&nbsp;&nbsp;
    						<b>Network In:</b> <span id="spanNetIn<?php echo $server->getServerId(); ?>"></span> kbps&nbsp;&nbsp;
    					</div>

    					</td>
                   	</tr>
                	<tr>
                		<td colspan="8">&nbsp;</td>
                	</tr>

                	<!--  server alerts section -->
                	<tr>
                		<td colspan="8"><i>Includes high cpu, low swap, low disk and unavailability notifications.</i></td>
                	</tr>
                   	<tr>
                   		<td><strong>Server Alert Contacts</strong></td>
                   		<td><strong>Name</strong></td>
                   		<td><strong>Email</strong></td>
                   		<td colspan="4"><strong>Action</strong></td>
                   	</tr>
                   	<?php $zalerts = $this->getZalerts($server); ?>
                   	<?php foreach ($zalerts as $zalert) { ?>
                	<tr>
                		<td>Contact</td>
                		<td><?php echo $zalert->getContactName(); ?></td>
                		<td><?php echo $zalert->getContactEmail(); ?></td>
                		<td colspan="4"><a href="/magento/noc/zalert/delete/id/<?php echo $zalert->getZalertId(); ?>">Delete</a></td>
                	</tr>
                	<?php } ?>
                	<?php  if ($zalerts->count() == 0) { ?>
                	<tr>
                		<td colspan="8">No contacts added.</td>
                	</tr>
                	<?php } ?>
                	<tr>
                		<td colspan="8"><a href="/magento/noc/zalert/new/?server_id=<?php echo $server->getServerId(); ?>">Add Contact</a></td>
                	</tr>
                	<tr>
                		<td colspan="8">&nbsp;</td>
                	</tr>
                	<tr>
                		<td colspan="8"><strong>NOTE:</strong> These are copies of OUR internal alerts.  We've already been notified.  Please do not open tickets because you received an alert as we have already been notified.</td>
                	</tr>
                	<tr>
                		<td colspan="8">&nbsp;</td>
                	</tr>

                	<!--  domains section -->
                   	<tr>
                   		<td colspan="1"><strong>Domains</strong></td>
                   		<td colspan="7"><strong>IPs</strong></td>
                   	</tr>
                   	<?php foreach ($this->getDomains($server) as $domain) { ?>
                	<tr>
                		<td colspan="1"><a href="http://<?php echo $domain->getName(); ?>">http://<?php echo $domain->getName(); ?></a></td>
                		<td colspan="7"><a href="http://<?php echo $domain->getIp()?>"><?php echo $domain->getIp()?></a></td>
                	</tr>
                	<?php } ?>
                	<tr>
                		<td colspan="8">&nbsp;</td>
                	</tr>

                	<!-- general information section -->
                   	<tr>
                   		<td colspan="8"><strong>General Information</strong></td>
                   	</tr>


									<? if($server->getPanel() == 'cpanel') { ?>
										<tr>
											<td>DNS 1</td>
											<td colspan="7">ns1.magemojo.com</td>
										</tr>
										<tr>
											<td>DNS 2</td>
											<td colspan="7">ns2.magemojo.com</td>
										</tr>
									<? } ?>
									<? if ($server->getPanel() == 'mhm') { ?>
										<tr>
											<td>DNS 1</td>
											<td colspan="7">ns1.mojohostmanager.com</td>
										</tr>
										<tr>
											<td>DNS 2</td>
											<td colspan="7">ns2.mojohostmanager.com</td>
										</tr>
									<? } ?>




									<? if($server->getPanel() == 'cpanel') { ?>
										<tr>
											<td>cPanel Url</td>
											<td colspan="7"><a href="https://<?php echo $server->getHostName(); ?>:2083">http://<?php echo $server->getHostName(); ?>:2083</a></td>
										</tr>
										<tr>
											<td>WHM Url</td>
											<td colspan="7"><a href="https://<?php echo $server->getHostName(); ?>:2087">http://<?php echo $server->getHostName(); ?>:2087</a></td>
										</tr>
										<tr>
											<td>Webmail Url</td>
											<td colspan="7"><a href="https://<?php echo $server->getHostName(); ?>:2096">http://<?php echo $server->getHostName(); ?>:2096</a></td>
										</tr>
									<? } ?>
									<? if ($server->getPanel() == 'mhm') { ?>
										<tr>
											<td>MHM Control Panel Url</td>
											<td colspan="7"><a target="_blank" href="https://magemojo.com/mhm/app/#/host/<?php echo $server->getHostName(); ?>/help">https://magemojo.com/mhm/app/#/host/<?php echo $server->getHostName(); ?>/help</a></td>
										</tr>
										<tr>
											<td>phpMyAdmin Url</td>
											<td colspan="7"><a target="_blank" href="https://<?php echo $server->getHostName(); ?>:2087">https://<?php echo $server->getHostName(); ?>:2087</a></td>
										</tr>
									<? } ?>




                	<tr>
                		<td>Mail Incoming/Outgoing Server</td>
                		<td colspan="7"><?php echo $server->getHostName(); ?></td>
                	</tr>
                	<tr>
                		<td>SMTP Port</td>
                		<td colspan="7">25</td>
                	</tr>
                	<tr>
                		<td>Alternate SMTP Port</td>
                		<td colspan="7">26</td>
                	</tr>
                	<tr>
                		<td>SMTP Port w/SSL</td>
                		<td colspan="7">465</td>
                	</tr>
                	<tr>
                		<td>SMTP Authentication</td>
                		<td colspan="7">Enabled (same as pop/imap user and pass)</td>
                	</tr>
                	<tr>
                		<td>POP3 Port (no encryption)</td>
                		<td colspan="7">110</td>
                	</tr>
                	<tr>
                		<td>POP3 Port w/SSL</td>
                		<td colspan="7">995</td>
                	</tr>
                	<tr>
                		<td>IMAP (no encryption)</td>
                		<td colspan="7">143</td>
                	</tr>
                	<tr>
                		<td>IMAP w/TLS</td>
                		<td colspan="7">585</td>
                	</tr>
                	<tr>
                		<td>IMAP w/SSL</td>
                		<td colspan="7">993</td>
                	<tr>
                		<td colspan="8">&nbsp;</td>
                	</tr>
                	</tr>                  	                      	           	              	               	                 	                	                                 					<tr>
                		<td colspan="8"><strong>NOTE:</strong> You must use your full email address as the username when configuring your email.</td>
                	</tr>
                	<tr>
                		<td colspan="8">&nbsp;</td>
                	</tr>
 <?php } ?>
                <?php } ?>
            </table>

        </div>

<?php } else { ?>

    <p><?php echo $this->__('You do not have any servers provisioned yet.') ?></p>

    <?php }  ?>

<div class="button-set">
    <a href="<?php echo $this->getBackUrl() ?>" class="f-left">&laquo; <?php echo $this->__('Back') ?></a>
</div>
</div>
